`ifndef SYNTHESIS // Added by Core.scala Verification Wrapper

// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1
`ifndef layers_RvvCoreMiniAxi_Verification_Cover
`define layers_RvvCoreMiniAxi_Verification_Cover
`endif // layers_RvvCoreMiniAxi_Verification_Cover

`endif // Added by Core.scala Verification Wrapper
