// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module AxiSlave(
  input          clock,
                 reset,
  output         io_axi_write_addr_ready,
  input          io_axi_write_addr_valid,
  input  [31:0]  io_axi_write_addr_bits_addr,
  input  [2:0]   io_axi_write_addr_bits_prot,
  input  [5:0]   io_axi_write_addr_bits_id,
  input  [7:0]   io_axi_write_addr_bits_len,
  input  [2:0]   io_axi_write_addr_bits_size,
  input  [1:0]   io_axi_write_addr_bits_burst,
  input          io_axi_write_addr_bits_lock,
  input  [3:0]   io_axi_write_addr_bits_cache,
                 io_axi_write_addr_bits_qos,
                 io_axi_write_addr_bits_region,
  output         io_axi_write_data_ready,
  input          io_axi_write_data_valid,
  input  [127:0] io_axi_write_data_bits_data,
  input          io_axi_write_data_bits_last,
  input  [15:0]  io_axi_write_data_bits_strb,
  input          io_axi_write_resp_ready,
  output         io_axi_write_resp_valid,
  output [5:0]   io_axi_write_resp_bits_id,
  output [1:0]   io_axi_write_resp_bits_resp,
  output         io_axi_read_addr_ready,
  input          io_axi_read_addr_valid,
  input  [31:0]  io_axi_read_addr_bits_addr,
  input  [2:0]   io_axi_read_addr_bits_prot,
  input  [5:0]   io_axi_read_addr_bits_id,
  input  [7:0]   io_axi_read_addr_bits_len,
  input  [2:0]   io_axi_read_addr_bits_size,
  input  [1:0]   io_axi_read_addr_bits_burst,
  input          io_axi_read_addr_bits_lock,
  input  [3:0]   io_axi_read_addr_bits_cache,
                 io_axi_read_addr_bits_qos,
                 io_axi_read_addr_bits_region,
  input          io_axi_read_data_ready,
  output         io_axi_read_data_valid,
  output [127:0] io_axi_read_data_bits_data,
  output [5:0]   io_axi_read_data_bits_id,
  output [1:0]   io_axi_read_data_bits_resp,
  output         io_axi_read_data_bits_last,
                 io_fabric_readDataAddr_valid,
  output [31:0]  io_fabric_readDataAddr_bits,
  input          io_fabric_readData_valid,
  input  [127:0] io_fabric_readData_bits,
  output         io_fabric_writeDataAddr_valid,
  output [31:0]  io_fabric_writeDataAddr_bits,
  output [127:0] io_fabric_writeDataBits,
  output [15:0]  io_fabric_writeDataStrb,
  input          io_fabric_writeResp,
                 io_periBusy
);

  wire        _readDataQueue_io_enq_ready;
  wire [1:0]  _readDataQueue_io_count;
  wire        _io_axi_write_resp_q_io_enq_ready;
  wire        _writeData_q_io_deq_valid;
  wire        _writeData_q_io_deq_bits_last;
  wire        _axiAddrCmd_q_io_enq_ready;
  wire        _axiAddrCmd_q_io_deq_valid;
  wire [31:0] _axiAddrCmd_q_io_deq_bits_addr_addr;
  wire [5:0]  _axiAddrCmd_q_io_deq_bits_addr_id;
  wire [7:0]  _axiAddrCmd_q_io_deq_bits_addr_len;
  wire [2:0]  _axiAddrCmd_q_io_deq_bits_addr_size;
  wire [1:0]  _axiAddrCmd_q_io_deq_bits_addr_burst;
  wire        _axiAddrCmd_q_io_deq_bits_write;
  wire        _addrArbiter_io_in_1_q_io_deq_valid;
  wire [31:0] _addrArbiter_io_in_1_q_io_deq_bits_addr;
  wire [2:0]  _addrArbiter_io_in_1_q_io_deq_bits_prot;
  wire [5:0]  _addrArbiter_io_in_1_q_io_deq_bits_id;
  wire [7:0]  _addrArbiter_io_in_1_q_io_deq_bits_len;
  wire [2:0]  _addrArbiter_io_in_1_q_io_deq_bits_size;
  wire [1:0]  _addrArbiter_io_in_1_q_io_deq_bits_burst;
  wire        _addrArbiter_io_in_1_q_io_deq_bits_lock;
  wire [3:0]  _addrArbiter_io_in_1_q_io_deq_bits_cache;
  wire [3:0]  _addrArbiter_io_in_1_q_io_deq_bits_qos;
  wire [3:0]  _addrArbiter_io_in_1_q_io_deq_bits_region;
  wire        _addrArbiter_io_in_0_q_io_deq_valid;
  wire [31:0] _addrArbiter_io_in_0_q_io_deq_bits_addr;
  wire [2:0]  _addrArbiter_io_in_0_q_io_deq_bits_prot;
  wire [5:0]  _addrArbiter_io_in_0_q_io_deq_bits_id;
  wire [7:0]  _addrArbiter_io_in_0_q_io_deq_bits_len;
  wire [2:0]  _addrArbiter_io_in_0_q_io_deq_bits_size;
  wire [1:0]  _addrArbiter_io_in_0_q_io_deq_bits_burst;
  wire        _addrArbiter_io_in_0_q_io_deq_bits_lock;
  wire [3:0]  _addrArbiter_io_in_0_q_io_deq_bits_cache;
  wire [3:0]  _addrArbiter_io_in_0_q_io_deq_bits_qos;
  wire [3:0]  _addrArbiter_io_in_0_q_io_deq_bits_region;
  wire        _addrArbiter_io_in_0_ready;
  wire        _addrArbiter_io_in_1_ready;
  wire        _addrArbiter_io_out_valid;
  wire [31:0] _addrArbiter_io_out_bits_addr;
  wire [2:0]  _addrArbiter_io_out_bits_prot;
  wire [5:0]  _addrArbiter_io_out_bits_id;
  wire [7:0]  _addrArbiter_io_out_bits_len;
  wire [2:0]  _addrArbiter_io_out_bits_size;
  wire [1:0]  _addrArbiter_io_out_bits_burst;
  wire        _addrArbiter_io_out_bits_lock;
  wire [3:0]  _addrArbiter_io_out_bits_cache;
  wire [3:0]  _addrArbiter_io_out_bits_qos;
  wire [3:0]  _addrArbiter_io_out_bits_region;
  wire        _addrArbiter_io_chosen;
  wire        writeActive = _axiAddrCmd_q_io_deq_valid & _axiAddrCmd_q_io_deq_bits_write;
  wire        readActive = _axiAddrCmd_q_io_deq_valid & ~_axiAddrCmd_q_io_deq_bits_write;
  reg  [31:0] cmdAddr;
  wire        maybeWriteData =
    writeActive & _writeData_q_io_deq_valid & _io_axi_write_resp_q_io_enq_ready;
  wire        writeData_q_io_deq_ready = maybeWriteData & ~io_periBusy;
  wire        writeResponse_valid =
    writeData_q_io_deq_ready & _writeData_q_io_deq_bits_last;
  reg         readIssued_valid;
  reg  [5:0]  readIssued_bits_id;
  reg         readIssued_bits_last;
  reg  [8:0]  readsIssued;
  wire [1:0]  _maybeIssueRead_T = 2'h3 - _readDataQueue_io_count;
  wire        maybeIssueRead = readActive & _maybeIssueRead_T[1];
  wire        issueRead = maybeIssueRead & ~io_periBusy;
  wire        lastRead = readsIssued == {1'h0, _axiAddrCmd_q_io_deq_bits_addr_len};
  wire        _addrNext_T = _axiAddrCmd_q_io_deq_bits_addr_burst == 2'h0;
  wire        _addrNext_T_2 = _axiAddrCmd_q_io_deq_bits_addr_burst == 2'h1;
  wire        _addrNext_T_7 = _axiAddrCmd_q_io_deq_bits_addr_burst == 2'h2;
  wire        validBurst =
    _axiAddrCmd_q_io_deq_valid & (_addrNext_T | _addrNext_T_2 | _addrNext_T_7);
  wire        _addrNext_T_1 = validBurst & _addrNext_T;
  wire        _addrNext_T_3 = validBurst & _addrNext_T_2;
  wire        _addrNext_T_8 = validBurst & _addrNext_T_7;
  wire        axiAddrCmd_q_io_deq_ready =
    writeActive ? writeResponse_valid : readActive & issueRead & lastRead;
  wire [31:0] cmdAddrBase =
    _axiAddrCmd_q_io_deq_bits_addr_addr
    & {25'h1FFFFFF,
       _axiAddrCmd_q_io_deq_bits_addr_size != 3'h7,
       _axiAddrCmd_q_io_deq_bits_addr_size[2:1] != 2'h3,
       _axiAddrCmd_q_io_deq_bits_addr_size < 3'h5,
       ~(_axiAddrCmd_q_io_deq_bits_addr_size[2]),
       _axiAddrCmd_q_io_deq_bits_addr_size < 3'h3,
       _axiAddrCmd_q_io_deq_bits_addr_size < 3'h2,
       _axiAddrCmd_q_io_deq_bits_addr_size == 3'h0};
  wire [31:0] _GEN = {24'h0, 8'h1 << _axiAddrCmd_q_io_deq_bits_addr_size};
  wire [31:0] _addrNext_newAddr_T_1 = cmdAddr + _GEN;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      cmdAddr <= 32'h0;
      readIssued_valid <= 1'h0;
      readIssued_bits_id <= 6'h0;
      readIssued_bits_last <= 1'h0;
      readsIssued <= 9'h0;
    end
    else begin
      if (_axiAddrCmd_q_io_enq_ready & _addrArbiter_io_out_valid)
        cmdAddr <= _addrArbiter_io_out_bits_addr;
      else if (maybeWriteData & ~io_periBusy | maybeIssueRead & ~io_periBusy)
        cmdAddr <=
          (_addrNext_T_1 ? cmdAddr : 32'h0) | (_addrNext_T_3 ? cmdAddr + _GEN : 32'h0)
          | (_addrNext_T_8
               ? (_addrNext_newAddr_T_1 >= cmdAddrBase + 32'h10
                    ? cmdAddrBase
                    : _addrNext_newAddr_T_1)
               : 32'h0)
          | (_addrNext_T_1 | _addrNext_T_3 | _addrNext_T_8 ? 32'h0 : cmdAddr);
      readIssued_valid <= issueRead;
      readIssued_bits_id <= _axiAddrCmd_q_io_deq_bits_addr_id;
      readIssued_bits_last <= lastRead;
      readsIssued <=
        axiAddrCmd_q_io_deq_ready & _axiAddrCmd_q_io_deq_valid
          ? 9'h0
          : readsIssued + {8'h0, issueRead};
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:1];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;
        end
        cmdAddr = _RANDOM[1'h0];
        readIssued_valid = _RANDOM[1'h1][0];
        readIssued_bits_id = _RANDOM[1'h1][6:1];
        readIssued_bits_last = _RANDOM[1'h1][7];
        readsIssued = _RANDOM[1'h1][16:8];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        cmdAddr = 32'h0;
        readIssued_valid = 1'h0;
        readIssued_bits_id = 6'h0;
        readIssued_bits_last = 1'h0;
        readsIssued = 9'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  CoralNPURRArbiter_1 addrArbiter (
    .clock               (clock),
    .reset               (reset),
    .io_in_0_ready       (_addrArbiter_io_in_0_ready),
    .io_in_0_valid       (_addrArbiter_io_in_0_q_io_deq_valid),
    .io_in_0_bits_addr   (_addrArbiter_io_in_0_q_io_deq_bits_addr),
    .io_in_0_bits_prot   (_addrArbiter_io_in_0_q_io_deq_bits_prot),
    .io_in_0_bits_id     (_addrArbiter_io_in_0_q_io_deq_bits_id),
    .io_in_0_bits_len    (_addrArbiter_io_in_0_q_io_deq_bits_len),
    .io_in_0_bits_size   (_addrArbiter_io_in_0_q_io_deq_bits_size),
    .io_in_0_bits_burst  (_addrArbiter_io_in_0_q_io_deq_bits_burst),
    .io_in_0_bits_lock   (_addrArbiter_io_in_0_q_io_deq_bits_lock),
    .io_in_0_bits_cache  (_addrArbiter_io_in_0_q_io_deq_bits_cache),
    .io_in_0_bits_qos    (_addrArbiter_io_in_0_q_io_deq_bits_qos),
    .io_in_0_bits_region (_addrArbiter_io_in_0_q_io_deq_bits_region),
    .io_in_1_ready       (_addrArbiter_io_in_1_ready),
    .io_in_1_valid       (_addrArbiter_io_in_1_q_io_deq_valid),
    .io_in_1_bits_addr   (_addrArbiter_io_in_1_q_io_deq_bits_addr),
    .io_in_1_bits_prot   (_addrArbiter_io_in_1_q_io_deq_bits_prot),
    .io_in_1_bits_id     (_addrArbiter_io_in_1_q_io_deq_bits_id),
    .io_in_1_bits_len    (_addrArbiter_io_in_1_q_io_deq_bits_len),
    .io_in_1_bits_size   (_addrArbiter_io_in_1_q_io_deq_bits_size),
    .io_in_1_bits_burst  (_addrArbiter_io_in_1_q_io_deq_bits_burst),
    .io_in_1_bits_lock   (_addrArbiter_io_in_1_q_io_deq_bits_lock),
    .io_in_1_bits_cache  (_addrArbiter_io_in_1_q_io_deq_bits_cache),
    .io_in_1_bits_qos    (_addrArbiter_io_in_1_q_io_deq_bits_qos),
    .io_in_1_bits_region (_addrArbiter_io_in_1_q_io_deq_bits_region),
    .io_out_ready        (_axiAddrCmd_q_io_enq_ready),
    .io_out_valid        (_addrArbiter_io_out_valid),
    .io_out_bits_addr    (_addrArbiter_io_out_bits_addr),
    .io_out_bits_prot    (_addrArbiter_io_out_bits_prot),
    .io_out_bits_id      (_addrArbiter_io_out_bits_id),
    .io_out_bits_len     (_addrArbiter_io_out_bits_len),
    .io_out_bits_size    (_addrArbiter_io_out_bits_size),
    .io_out_bits_burst   (_addrArbiter_io_out_bits_burst),
    .io_out_bits_lock    (_addrArbiter_io_out_bits_lock),
    .io_out_bits_cache   (_addrArbiter_io_out_bits_cache),
    .io_out_bits_qos     (_addrArbiter_io_out_bits_qos),
    .io_out_bits_region  (_addrArbiter_io_out_bits_region),
    .io_chosen           (_addrArbiter_io_chosen)
  );
  Queue2_AxiAddress addrArbiter_io_in_0_q (
    .clock              (clock),
    .reset              (reset),
    .io_enq_ready       (io_axi_read_addr_ready),
    .io_enq_valid       (io_axi_read_addr_valid),
    .io_enq_bits_addr   (io_axi_read_addr_bits_addr),
    .io_enq_bits_prot   (io_axi_read_addr_bits_prot),
    .io_enq_bits_id     (io_axi_read_addr_bits_id),
    .io_enq_bits_len    (io_axi_read_addr_bits_len),
    .io_enq_bits_size   (io_axi_read_addr_bits_size),
    .io_enq_bits_burst  (io_axi_read_addr_bits_burst),
    .io_enq_bits_lock   (io_axi_read_addr_bits_lock),
    .io_enq_bits_cache  (io_axi_read_addr_bits_cache),
    .io_enq_bits_qos    (io_axi_read_addr_bits_qos),
    .io_enq_bits_region (io_axi_read_addr_bits_region),
    .io_deq_ready       (_addrArbiter_io_in_0_ready),
    .io_deq_valid       (_addrArbiter_io_in_0_q_io_deq_valid),
    .io_deq_bits_addr   (_addrArbiter_io_in_0_q_io_deq_bits_addr),
    .io_deq_bits_prot   (_addrArbiter_io_in_0_q_io_deq_bits_prot),
    .io_deq_bits_id     (_addrArbiter_io_in_0_q_io_deq_bits_id),
    .io_deq_bits_len    (_addrArbiter_io_in_0_q_io_deq_bits_len),
    .io_deq_bits_size   (_addrArbiter_io_in_0_q_io_deq_bits_size),
    .io_deq_bits_burst  (_addrArbiter_io_in_0_q_io_deq_bits_burst),
    .io_deq_bits_lock   (_addrArbiter_io_in_0_q_io_deq_bits_lock),
    .io_deq_bits_cache  (_addrArbiter_io_in_0_q_io_deq_bits_cache),
    .io_deq_bits_qos    (_addrArbiter_io_in_0_q_io_deq_bits_qos),
    .io_deq_bits_region (_addrArbiter_io_in_0_q_io_deq_bits_region)
  );
  Queue2_AxiAddress addrArbiter_io_in_1_q (
    .clock              (clock),
    .reset              (reset),
    .io_enq_ready       (io_axi_write_addr_ready),
    .io_enq_valid       (io_axi_write_addr_valid),
    .io_enq_bits_addr   (io_axi_write_addr_bits_addr),
    .io_enq_bits_prot   (io_axi_write_addr_bits_prot),
    .io_enq_bits_id     (io_axi_write_addr_bits_id),
    .io_enq_bits_len    (io_axi_write_addr_bits_len),
    .io_enq_bits_size   (io_axi_write_addr_bits_size),
    .io_enq_bits_burst  (io_axi_write_addr_bits_burst),
    .io_enq_bits_lock   (io_axi_write_addr_bits_lock),
    .io_enq_bits_cache  (io_axi_write_addr_bits_cache),
    .io_enq_bits_qos    (io_axi_write_addr_bits_qos),
    .io_enq_bits_region (io_axi_write_addr_bits_region),
    .io_deq_ready       (_addrArbiter_io_in_1_ready),
    .io_deq_valid       (_addrArbiter_io_in_1_q_io_deq_valid),
    .io_deq_bits_addr   (_addrArbiter_io_in_1_q_io_deq_bits_addr),
    .io_deq_bits_prot   (_addrArbiter_io_in_1_q_io_deq_bits_prot),
    .io_deq_bits_id     (_addrArbiter_io_in_1_q_io_deq_bits_id),
    .io_deq_bits_len    (_addrArbiter_io_in_1_q_io_deq_bits_len),
    .io_deq_bits_size   (_addrArbiter_io_in_1_q_io_deq_bits_size),
    .io_deq_bits_burst  (_addrArbiter_io_in_1_q_io_deq_bits_burst),
    .io_deq_bits_lock   (_addrArbiter_io_in_1_q_io_deq_bits_lock),
    .io_deq_bits_cache  (_addrArbiter_io_in_1_q_io_deq_bits_cache),
    .io_deq_bits_qos    (_addrArbiter_io_in_1_q_io_deq_bits_qos),
    .io_deq_bits_region (_addrArbiter_io_in_1_q_io_deq_bits_region)
  );
  Queue1_RWAxiAddress axiAddrCmd_q (
    .clock                   (clock),
    .reset                   (reset),
    .io_enq_ready            (_axiAddrCmd_q_io_enq_ready),
    .io_enq_valid            (_addrArbiter_io_out_valid),
    .io_enq_bits_addr_addr   (_addrArbiter_io_out_bits_addr),
    .io_enq_bits_addr_prot   (_addrArbiter_io_out_bits_prot),
    .io_enq_bits_addr_id     (_addrArbiter_io_out_bits_id),
    .io_enq_bits_addr_len    (_addrArbiter_io_out_bits_len),
    .io_enq_bits_addr_size   (_addrArbiter_io_out_bits_size),
    .io_enq_bits_addr_burst  (_addrArbiter_io_out_bits_burst),
    .io_enq_bits_addr_lock   (_addrArbiter_io_out_bits_lock),
    .io_enq_bits_addr_cache  (_addrArbiter_io_out_bits_cache),
    .io_enq_bits_addr_qos    (_addrArbiter_io_out_bits_qos),
    .io_enq_bits_addr_region (_addrArbiter_io_out_bits_region),
    .io_enq_bits_write       (_addrArbiter_io_chosen),
    .io_deq_ready            (axiAddrCmd_q_io_deq_ready),
    .io_deq_valid            (_axiAddrCmd_q_io_deq_valid),
    .io_deq_bits_addr_addr   (_axiAddrCmd_q_io_deq_bits_addr_addr),
    .io_deq_bits_addr_id     (_axiAddrCmd_q_io_deq_bits_addr_id),
    .io_deq_bits_addr_len    (_axiAddrCmd_q_io_deq_bits_addr_len),
    .io_deq_bits_addr_size   (_axiAddrCmd_q_io_deq_bits_addr_size),
    .io_deq_bits_addr_burst  (_axiAddrCmd_q_io_deq_bits_addr_burst),
    .io_deq_bits_write       (_axiAddrCmd_q_io_deq_bits_write)
  );
  Queue3_AxiWriteData writeData_q (
    .clock            (clock),
    .reset            (reset),
    .io_enq_ready     (io_axi_write_data_ready),
    .io_enq_valid     (io_axi_write_data_valid),
    .io_enq_bits_data (io_axi_write_data_bits_data),
    .io_enq_bits_last (io_axi_write_data_bits_last),
    .io_enq_bits_strb (io_axi_write_data_bits_strb),
    .io_deq_ready     (writeData_q_io_deq_ready),
    .io_deq_valid     (_writeData_q_io_deq_valid),
    .io_deq_bits_data (io_fabric_writeDataBits),
    .io_deq_bits_last (_writeData_q_io_deq_bits_last),
    .io_deq_bits_strb (io_fabric_writeDataStrb)
  );
  Queue2_AxiWriteResponse io_axi_write_resp_q (
    .clock            (clock),
    .reset            (reset),
    .io_enq_ready     (_io_axi_write_resp_q_io_enq_ready),
    .io_enq_valid     (writeResponse_valid),
    .io_enq_bits_id   (_axiAddrCmd_q_io_deq_bits_addr_id),
    .io_enq_bits_resp ({~io_fabric_writeResp, 1'h0}),
    .io_deq_ready     (io_axi_write_resp_ready),
    .io_deq_valid     (io_axi_write_resp_valid),
    .io_deq_bits_id   (io_axi_write_resp_bits_id),
    .io_deq_bits_resp (io_axi_write_resp_bits_resp)
  );
  Queue3_AxiReadData readDataQueue (
    .clock            (clock),
    .reset            (reset),
    .io_enq_ready     (_readDataQueue_io_enq_ready),
    .io_enq_valid     (readIssued_valid),
    .io_enq_bits_data (io_fabric_readData_bits),
    .io_enq_bits_id   (readIssued_bits_id),
    .io_enq_bits_resp ({~io_fabric_readData_valid, 1'h0}),
    .io_enq_bits_last (readIssued_bits_last),
    .io_deq_ready     (io_axi_read_data_ready),
    .io_deq_valid     (io_axi_read_data_valid),
    .io_deq_bits_data (io_axi_read_data_bits_data),
    .io_deq_bits_id   (io_axi_read_data_bits_id),
    .io_deq_bits_resp (io_axi_read_data_bits_resp),
    .io_deq_bits_last (io_axi_read_data_bits_last),
    .io_count         (_readDataQueue_io_count)
  );
  assign io_fabric_readDataAddr_valid = maybeIssueRead;
  assign io_fabric_readDataAddr_bits = cmdAddr;
  assign io_fabric_writeDataAddr_valid = maybeWriteData;
  assign io_fabric_writeDataAddr_bits = cmdAddr;
endmodule

