// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module DebugModule(
  input          clock,
                 reset,
  output         io_ext_req_ready,
  input          io_ext_req_valid,
  input  [31:0]  io_ext_req_bits_address,
                 io_ext_req_bits_data,
  input  [1:0]   io_ext_req_bits_op,
  input          io_ext_rsp_ready,
  output         io_ext_rsp_valid,
  output [31:0]  io_ext_rsp_bits_data,
  output [1:0]   io_ext_rsp_bits_op,
  output         io_csr_valid,
  output [4:0]   io_csr_bits_addr,
  output [11:0]  io_csr_bits_index,
  output [4:0]   io_csr_bits_rs1,
  output [1:0]   io_csr_bits_op,
  output [31:0]  io_csr_rs1,
  input          io_csr_rd_valid,
  input  [31:0]  io_csr_rd_bits,
  input          io_scalar_rd_ready,
  output         io_scalar_rd_valid,
  output [4:0]   io_scalar_rd_bits_addr,
  output [31:0]  io_scalar_rd_bits_data,
  output [4:0]   io_scalar_rs_idx,
  input  [31:0]  io_scalar_rs_data,
  output         io_float_rd_valid,
  output [4:0]   io_float_rd_addr,
  output [22:0]  io_float_rd_data_mantissa,
  output [7:0]   io_float_rd_data_exponent,
  output         io_float_rd_data_sign,
                 io_float_rs_valid,
  output [4:0]   io_float_rs_addr,
  input  [22:0]  io_float_rs_data_mantissa,
  input  [7:0]   io_float_rs_data_exponent,
  input          io_float_rs_data_sign,
  output         io_itcm_readDataAddr_valid,
  output [31:0]  io_itcm_readDataAddr_bits,
  input          io_itcm_readData_valid,
  input  [127:0] io_itcm_readData_bits,
  output         io_itcm_writeDataAddr_valid,
  output [31:0]  io_itcm_writeDataAddr_bits,
  output [127:0] io_itcm_writeDataBits,
  output [15:0]  io_itcm_writeDataStrb,
  input          io_itcm_writeResp,
  output         io_dtcm_readDataAddr_valid,
  output [31:0]  io_dtcm_readDataAddr_bits,
  input          io_dtcm_readData_valid,
  input  [127:0] io_dtcm_readData_bits,
  output         io_dtcm_writeDataAddr_valid,
  output [31:0]  io_dtcm_writeDataAddr_bits,
  output [127:0] io_dtcm_writeDataBits,
  output [15:0]  io_dtcm_writeDataStrb,
  input          io_dtcm_writeResp,
  output         io_haltreq_0,
                 io_resumereq_0,
  input          io_resumeack_0,
  output         io_ndmreset,
  input          io_halted_0,
                 io_running_0,
                 io_havereset_0
);

  wire             io_float_rd_valid_0;
  wire             io_scalar_rd_valid_0;
  wire             _io_ext_rsp_q_io_enq_ready;
  wire             _req_q_io_deq_valid;
  wire [31:0]      _req_q_io_deq_bits_address;
  wire [31:0]      _req_q_io_deq_bits_data;
  wire [1:0]       _req_q_io_deq_bits_op;
  reg              haltreq_0;
  reg              resumereq_0;
  reg              resumeack_0;
  reg  [31:0]      dmcontrol;
  reg  [31:0]      data0;
  reg  [31:0]      data1;
  reg  [31:0]      cmderr;
  wire             _rsp_map_bits_rspBits_data_T_6 = _req_q_io_deq_bits_address == 32'h10;
  wire             _rsp_map_bits_rspBits_op_T_53 = _req_q_io_deq_bits_op == 2'h2;
  wire             _rsp_map_bits_rspBits_data_T_21 = _req_q_io_deq_bits_address == 32'h17;
  wire             abstractCmdValid =
    _req_q_io_deq_valid & _rsp_map_bits_rspBits_op_T_53 & _rsp_map_bits_rspBits_data_T_21;
  wire             cmdtypeIsAccessMemory = _req_q_io_deq_bits_data[31:24] == 8'h2;
  wire             regnoIsCsr = _req_q_io_deq_bits_data[15:0] < 16'h1000;
  wire             regnoIsScalar =
    (|(_req_q_io_deq_bits_data[15:12])) & _req_q_io_deq_bits_data[15:0] < 16'h1020;
  wire             regnoIsFloat =
    _req_q_io_deq_bits_data[15:0] > 16'h101F & _req_q_io_deq_bits_data[15:0] < 16'h1040;
  wire             regnoInvalid =
    (|(_req_q_io_deq_bits_data[15:12])) & ~regnoIsScalar & ~regnoIsFloat;
  wire             itcm = data1 < 32'h2000;
  wire             dtcm = (|(data1[31:16])) & data1 < 32'h18000;
  wire             _cmderr_T_17 = itcm | dtcm;
  wire             _abstractCmdCompleteFloat_T_3 =
    ~(|(_req_q_io_deq_bits_data[31:24])) & regnoIsFloat;
  wire             _abstractCmdComplete_T_8 =
    ~(|(_req_q_io_deq_bits_data[31:24])) & regnoIsScalar;
  wire             abstractCmdComplete =
    abstractCmdValid
    & (~(|(_req_q_io_deq_bits_data[31:24])) & regnoInvalid
       | ~(|(_req_q_io_deq_bits_data[31:24])) & regnoIsCsr & io_csr_rd_valid
       | _abstractCmdComplete_T_8 & io_scalar_rd_ready & io_scalar_rd_valid_0
       | _abstractCmdComplete_T_8 & ~(_req_q_io_deq_bits_data[16]) | cmdtypeIsAccessMemory
       & io_itcm_readData_valid | cmdtypeIsAccessMemory & io_dtcm_readData_valid
       | cmdtypeIsAccessMemory & _req_q_io_deq_bits_data[16] | cmdtypeIsAccessMemory
       & ~_cmderr_T_17 | _abstractCmdCompleteFloat_T_3 & io_float_rd_valid_0
       | _abstractCmdCompleteFloat_T_3 & ~(_req_q_io_deq_bits_data[16])) | ~io_halted_0;
  wire             _io_float_rs_valid_T = io_halted_0 & abstractCmdValid;
  wire             _rsp_map_bits_rspBits_data_T_15 = _req_q_io_deq_bits_address == 32'h16;
  wire             _rsp_map_bits_rspBits_data_T_22 = _req_q_io_deq_bits_op == 2'h1;
  assign io_scalar_rd_valid_0 =
    _io_float_rs_valid_T & ~(|(_req_q_io_deq_bits_data[31:24])) & regnoIsScalar
    & _req_q_io_deq_bits_data[16];
  assign io_float_rd_valid_0 =
    _io_float_rs_valid_T & ~(|(_req_q_io_deq_bits_data[31:24])) & regnoIsFloat
    & _req_q_io_deq_bits_data[16];
  wire             _rsp_map_bits_rspBits_data_T = _req_q_io_deq_bits_address == 32'h4;
  wire             _rsp_map_bits_rspBits_data_T_3 = _req_q_io_deq_bits_address == 32'h5;
  wire             _rsp_map_bits_rspBits_data_T_9 = _req_q_io_deq_bits_address == 32'h11;
  wire             _rsp_map_bits_rspBits_data_T_12 = _req_q_io_deq_bits_address == 32'h12;
  wire             req_q_io_deq_ready =
    _io_ext_rsp_q_io_enq_ready & (~abstractCmdValid | abstractCmdComplete);
  wire             _io_dtcm_writeDataAddr_valid_T =
    abstractCmdValid & cmdtypeIsAccessMemory;
  wire [16:0]      _strobe_T_6 = 17'h3 << data1[3:0];
  wire [18:0]      _strobe_T_9 = 19'hF << data1[3:0];
  wire [15:0]      strobe =
    _req_q_io_deq_bits_data[22:20] == 3'h0
      ? 16'h1 << data1[3:0]
      : _req_q_io_deq_bits_data[22:20] == 3'h1
          ? _strobe_T_6[15:0]
          : _req_q_io_deq_bits_data[22:20] == 3'h2 ? _strobe_T_9[15:0] : 16'hFFFF;
  wire [382:0]     writeDataBits = {351'h0, data0} << {376'h0, data1[3:0], 3'h0};
  wire [3:0][31:0] _GEN =
    {{io_itcm_readData_bits[127:96]},
     {io_itcm_readData_bits[95:64]},
     {io_itcm_readData_bits[63:32]},
     {32'h0}};
  wire [3:0][31:0] _GEN_0 =
    {{io_dtcm_readData_bits[127:96]},
     {io_dtcm_readData_bits[95:64]},
     {io_dtcm_readData_bits[63:32]},
     {32'h0}};
  wire             _data0_T_63 = abstractCmdComplete & cmdtypeIsAccessMemory;
  wire [31:0]      data0ItcmReadData =
    (|(data1[3:2])) ? _GEN[data1[3:2]] : io_itcm_readData_bits[31:0];
  wire [31:0]      _data0_T_57 =
    data1[0] ? {data0ItcmReadData[7:0], data0ItcmReadData[31:8]} : data0ItcmReadData;
  wire [31:0]      data0DtcmReadData =
    (|(data1[3:2])) ? _GEN_0[data1[3:2]] : io_dtcm_readData_bits[31:0];
  wire [31:0]      _data0_T_93 =
    data1[0] ? {data0DtcmReadData[7:0], data0DtcmReadData[31:8]} : data0DtcmReadData;
  wire             _data0_T_19 =
    abstractCmdComplete & ~(|(_req_q_io_deq_bits_data[31:24]));
  wire             _abstractcs_wvalid_T = req_q_io_deq_ready & _req_q_io_deq_valid;
  wire             dmcontrol_wvalid =
    _abstractcs_wvalid_T & _rsp_map_bits_rspBits_data_T_6 & _rsp_map_bits_rspBits_op_T_53;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      haltreq_0 <= 1'h0;
      resumereq_0 <= 1'h0;
      resumeack_0 <= 1'h0;
      dmcontrol <= 32'h1;
      data0 <= 32'h0;
      data1 <= 32'h0;
      cmderr <= 32'h0;
    end
    else begin
      if (dmcontrol_wvalid) begin
        haltreq_0 <= _req_q_io_deq_bits_data[31];
        dmcontrol <=
          {dmcontrol[31:26],
           _req_q_io_deq_bits_data[25:6] == 20'h0 ? _req_q_io_deq_bits_data[25:6] : 20'h1,
           dmcontrol[5:2],
           _req_q_io_deq_bits_data[1:0]};
      end
      resumereq_0 <=
        dmcontrol_wvalid ? _req_q_io_deq_bits_data[30] : ~io_resumeack_0 & resumereq_0;
      resumeack_0 <= ~haltreq_0 & (io_resumeack_0 | resumeack_0);
      if (_req_q_io_deq_valid & _rsp_map_bits_rspBits_data_T
          & _rsp_map_bits_rspBits_op_T_53)
        data0 <= _req_q_io_deq_bits_data;
      else if (_data0_T_19 & io_halted_0 & _req_q_io_deq_valid
               & ~(_req_q_io_deq_bits_data[16]) & regnoIsCsr & io_csr_rd_valid)
        data0 <= io_csr_rd_bits;
      else if (_data0_T_19 & io_halted_0 & _req_q_io_deq_valid
               & ~(_req_q_io_deq_bits_data[16]) & regnoIsScalar)
        data0 <= io_scalar_rs_data;
      else if (_data0_T_19 & io_halted_0 & _req_q_io_deq_valid
               & ~(_req_q_io_deq_bits_data[16]) & regnoIsFloat)
        data0 <=
          {io_float_rs_data_sign, io_float_rs_data_exponent, io_float_rs_data_mantissa};
      else if (_data0_T_63 & io_halted_0 & _req_q_io_deq_valid
               & ~(_req_q_io_deq_bits_data[16]) & io_itcm_readData_valid)
        data0 <= data1[1] ? {_data0_T_57[15:0], _data0_T_57[31:16]} : _data0_T_57;
      else if (_data0_T_63 & io_halted_0 & _req_q_io_deq_valid
               & ~(_req_q_io_deq_bits_data[16]) & io_dtcm_readData_valid)
        data0 <= data1[1] ? {_data0_T_93[15:0], _data0_T_93[31:16]} : _data0_T_93;
      else if (dmcontrol[0]) begin
      end
      else
        data0 <= 32'h0;
      if (_req_q_io_deq_valid & _rsp_map_bits_rspBits_data_T_3
          & _rsp_map_bits_rspBits_op_T_53)
        data1 <= _req_q_io_deq_bits_data;
      else if (_req_q_io_deq_valid & _req_q_io_deq_bits_data[19] & abstractCmdComplete
               & cmdtypeIsAccessMemory & io_halted_0)
        data1 <= data1 + {24'h0, 8'h1 << _req_q_io_deq_bits_data[22:20]};
      if (_abstractcs_wvalid_T & _rsp_map_bits_rspBits_data_T_15
          & _rsp_map_bits_rspBits_op_T_53)
        cmderr <= {29'h0, cmderr[2:0] & ~(_req_q_io_deq_bits_data[10:8])};
      else if (abstractCmdValid & ~io_halted_0)
        cmderr <= 32'h4;
      else if (abstractCmdValid & ~(|(_req_q_io_deq_bits_data[31:24]))
               & (|{_rsp_map_bits_rspBits_op_T_53, _rsp_map_bits_rspBits_data_T_22})
               & _req_q_io_deq_bits_data[22:20] != 3'h2)
        cmderr <= 32'h2;
      else if (abstractCmdValid & cmdtypeIsAccessMemory & ~_cmderr_T_17)
        cmderr <= 32'h5;
      else if (dmcontrol[0]) begin
      end
      else
        cmderr <= 32'h0;
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:4];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [2:0] i = 3'h0; i < 3'h5; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        haltreq_0 = _RANDOM[3'h0][0];
        resumereq_0 = _RANDOM[3'h0][1];
        resumeack_0 = _RANDOM[3'h0][2];
        dmcontrol = {_RANDOM[3'h0][31:3], _RANDOM[3'h1][2:0]};
        data0 = {_RANDOM[3'h1][31:3], _RANDOM[3'h2][2:0]};
        data1 = {_RANDOM[3'h2][31:3], _RANDOM[3'h3][2:0]};
        cmderr = {_RANDOM[3'h3][31:3], _RANDOM[3'h4][2:0]};
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        haltreq_0 = 1'h0;
        resumereq_0 = 1'h0;
        resumeack_0 = 1'h0;
        dmcontrol = 32'h1;
        data0 = 32'h0;
        data1 = 32'h0;
        cmderr = 32'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Queue1_DebugModuleReqIO req_q (
    .clock               (clock),
    .reset               (reset),
    .io_enq_ready        (io_ext_req_ready),
    .io_enq_valid        (io_ext_req_valid),
    .io_enq_bits_address (io_ext_req_bits_address),
    .io_enq_bits_data    (io_ext_req_bits_data),
    .io_enq_bits_op      (io_ext_req_bits_op),
    .io_deq_ready        (req_q_io_deq_ready),
    .io_deq_valid        (_req_q_io_deq_valid),
    .io_deq_bits_address (_req_q_io_deq_bits_address),
    .io_deq_bits_data    (_req_q_io_deq_bits_data),
    .io_deq_bits_op      (_req_q_io_deq_bits_op)
  );
  Queue1_DebugModuleRspIO io_ext_rsp_q (
    .clock            (clock),
    .reset            (reset),
    .io_enq_ready     (_io_ext_rsp_q_io_enq_ready),
    .io_enq_valid     (_req_q_io_deq_valid & (~abstractCmdValid | abstractCmdComplete)),
    .io_enq_bits_data
      (_rsp_map_bits_rspBits_data_T & _rsp_map_bits_rspBits_data_T_22
         ? data0
         : _rsp_map_bits_rspBits_data_T_3 & _rsp_map_bits_rspBits_data_T_22
             ? data1
             : _rsp_map_bits_rspBits_data_T_6 & _rsp_map_bits_rspBits_data_T_22
                 ? dmcontrol
                 : _rsp_map_bits_rspBits_data_T_9 & _rsp_map_bits_rspBits_data_T_22
                     ? {14'h0,
                        {2{resumeack_0}},
                        4'h0,
                        {2{io_running_0}},
                        {2{io_halted_0}},
                        8'h83}
                     : _rsp_map_bits_rspBits_data_T_12 & _rsp_map_bits_rspBits_data_T_22
                         ? 32'h2007B4
                         : _rsp_map_bits_rspBits_data_T_15
                           & _rsp_map_bits_rspBits_data_T_22
                             ? {cmderr[23:0], 8'h1}
                             : 32'h0),
    .io_enq_bits_op
      (_rsp_map_bits_rspBits_data_T
       & (|{_rsp_map_bits_rspBits_op_T_53, _rsp_map_bits_rspBits_data_T_22})
       | _rsp_map_bits_rspBits_data_T_3
       & (|{_rsp_map_bits_rspBits_op_T_53, _rsp_map_bits_rspBits_data_T_22})
       | _rsp_map_bits_rspBits_data_T_6
       & (|{_rsp_map_bits_rspBits_op_T_53, _rsp_map_bits_rspBits_data_T_22})
       | _rsp_map_bits_rspBits_data_T_9
       & (|{_rsp_map_bits_rspBits_op_T_53, _rsp_map_bits_rspBits_data_T_22})
       | _rsp_map_bits_rspBits_data_T_12
       & (|{_rsp_map_bits_rspBits_op_T_53, _rsp_map_bits_rspBits_data_T_22})
       | _rsp_map_bits_rspBits_data_T_15
       & (|{_rsp_map_bits_rspBits_op_T_53, _rsp_map_bits_rspBits_data_T_22})
       | _req_q_io_deq_bits_address == 32'h38
       & (|{_rsp_map_bits_rspBits_op_T_53, _rsp_map_bits_rspBits_data_T_22})
         ? 2'h0
         : _rsp_map_bits_rspBits_data_T_21 & ~(|(_req_q_io_deq_bits_data[31:24]))
           & (|{_rsp_map_bits_rspBits_op_T_53, _rsp_map_bits_rspBits_data_T_22})
           & regnoInvalid
             ? 2'h2
             : _rsp_map_bits_rspBits_data_T_21 & ~(|(_req_q_io_deq_bits_data[31:24]))
               & (|{_rsp_map_bits_rspBits_op_T_53, _rsp_map_bits_rspBits_data_T_22})
               | _rsp_map_bits_rspBits_data_T_21 & cmdtypeIsAccessMemory
                 ? 2'h0
                 : 2'h3),
    .io_deq_ready     (io_ext_rsp_ready),
    .io_deq_valid     (io_ext_rsp_valid),
    .io_deq_bits_data (io_ext_rsp_bits_data),
    .io_deq_bits_op   (io_ext_rsp_bits_op)
  );
  assign io_csr_valid =
    _io_float_rs_valid_T & ~(|(_req_q_io_deq_bits_data[31:24])) & regnoIsCsr;
  assign io_csr_bits_addr = 5'h0;
  assign io_csr_bits_index = _req_q_io_deq_bits_data[11:0];
  assign io_csr_bits_rs1 = 5'h0;
  assign io_csr_bits_op = {~(_req_q_io_deq_bits_data[16]), 1'h0};
  assign io_csr_rs1 = _req_q_io_deq_bits_data[16] ? data0 : 32'h0;
  assign io_scalar_rd_valid = io_scalar_rd_valid_0;
  assign io_scalar_rd_bits_addr = _req_q_io_deq_bits_data[4:0];
  assign io_scalar_rd_bits_data = data0;
  assign io_scalar_rs_idx =
    _io_float_rs_valid_T & ~(|(_req_q_io_deq_bits_data[31:24])) & regnoIsScalar
    & ~(_req_q_io_deq_bits_data[16])
      ? _req_q_io_deq_bits_data[4:0]
      : 5'h0;
  assign io_float_rd_valid = io_float_rd_valid_0;
  assign io_float_rd_addr = _req_q_io_deq_bits_data[4:0];
  assign io_float_rd_data_mantissa = data0[22:0];
  assign io_float_rd_data_exponent = data0[30:23];
  assign io_float_rd_data_sign = data0[31];
  assign io_float_rs_valid =
    _io_float_rs_valid_T & ~(|(_req_q_io_deq_bits_data[31:24])) & regnoIsFloat
    & ~(_req_q_io_deq_bits_data[16]);
  assign io_float_rs_addr = _req_q_io_deq_bits_data[4:0];
  assign io_itcm_readDataAddr_valid =
    _io_dtcm_writeDataAddr_valid_T & ~(_req_q_io_deq_bits_data[16]) & itcm;
  assign io_itcm_readDataAddr_bits = data1;
  assign io_itcm_writeDataAddr_valid =
    _io_dtcm_writeDataAddr_valid_T & _req_q_io_deq_bits_data[16] & itcm;
  assign io_itcm_writeDataAddr_bits = data1;
  assign io_itcm_writeDataBits = writeDataBits[127:0];
  assign io_itcm_writeDataStrb = strobe;
  assign io_dtcm_readDataAddr_valid =
    _io_dtcm_writeDataAddr_valid_T & ~(_req_q_io_deq_bits_data[16]) & dtcm;
  assign io_dtcm_readDataAddr_bits = data1;
  assign io_dtcm_writeDataAddr_valid =
    _io_dtcm_writeDataAddr_valid_T & _req_q_io_deq_bits_data[16] & dtcm;
  assign io_dtcm_writeDataAddr_bits = data1;
  assign io_dtcm_writeDataBits = writeDataBits[127:0];
  assign io_dtcm_writeDataStrb = strobe;
  assign io_haltreq_0 = haltreq_0;
  assign io_resumereq_0 = resumereq_0;
  assign io_ndmreset = dmcontrol[1];
endmodule

