`ifndef SYNTHESIS // Added by Core.scala Verification Wrapper

// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module DispatchV2_Verification_Assert(
  input decodedInsts_0_sub,
        _GEN,
        _GEN_0,
        _GEN_1,
        _GEN_2,
        _GEN_3,
        _GEN_4,
        _GEN_5,
        _GEN_6,
        _GEN_7,
        decodedInsts_0_orn,
        decodedInsts_0_xnor,
        decodedInsts_0_lui,
        decodedInsts_0_andn,
        decodedInsts_0_ctz,
        decodedInsts_0_cpop,
        decodedInsts_0_clz,
        decodedInsts_0_min,
        decodedInsts_0_minu,
        decodedInsts_0_max,
        decodedInsts_0_maxu,
        decodedInsts_0_rol,
        decodedInsts_0_ror,
        decodedInsts_0_sextb,
        decodedInsts_0_sexth,
        decodedInsts_0_zexth,
        decodedInsts_0_rori,
        decodedInsts_0_orcb,
        decodedInsts_0_rev8,
        reset,
        _GEN_8,
        decodedInsts_0_jalr,
        decodedInsts_0_beq,
        decodedInsts_0_jal,
        decodedInsts_0_blt,
        decodedInsts_0_bge,
        decodedInsts_0_bne,
        decodedInsts_0_bgeu,
        decodedInsts_0_ebreak,
        decodedInsts_0_bltu,
        decodedInsts_0_mret,
        decodedInsts_0_wfi,
        decodedInsts_0_ecall,
        decodedInsts_0_mpause,
        decodedInsts_0_mulhsu,
        decodedInsts_0_mulhu,
        decodedInsts_0_mul,
        decodedInsts_0_mulh,
        decodedInsts_0_rem,
        decodedInsts_0_remu,
        decodedInsts_0_div,
        decodedInsts_0_divu,
        decodedInsts_0_lbu,
        decodedInsts_0_lhu,
        decodedInsts_0_lw,
        decodedInsts_0_lb,
        decodedInsts_0_lh,
        decodedInsts_0_fencei,
        decodedInsts_0_sw,
        decodedInsts_0_sb,
        decodedInsts_0_sh,
        _GEN_9,
        _GEN_10,
        _GEN_11,
        decodedInsts_0_flushat,
        decodedInsts_0_flushall,
        _GEN_12,
        _GEN_13,
        _GEN_14,
        _GEN_15,
        _GEN_16,
        _GEN_17,
        decodedInsts_0_csrrs,
        decodedInsts_0_csrrc,
        decodedInsts_0_csrrw,
        decodedInsts_1_sub,
        _GEN_18,
        _GEN_19,
        _GEN_20,
        _GEN_21,
        _GEN_22,
        _GEN_23,
        _GEN_24,
        _GEN_25,
        _GEN_26,
        decodedInsts_1_orn,
        decodedInsts_1_xnor,
        decodedInsts_1_lui,
        decodedInsts_1_andn,
        decodedInsts_1_ctz,
        decodedInsts_1_cpop,
        decodedInsts_1_clz,
        decodedInsts_1_min,
        decodedInsts_1_minu,
        decodedInsts_1_max,
        decodedInsts_1_maxu,
        decodedInsts_1_rol,
        decodedInsts_1_ror,
        decodedInsts_1_sextb,
        decodedInsts_1_sexth,
        decodedInsts_1_zexth,
        decodedInsts_1_rori,
        decodedInsts_1_orcb,
        decodedInsts_1_rev8,
        decodedInsts_1_jalr,
        decodedInsts_1_beq,
        decodedInsts_1_jal,
        decodedInsts_1_blt,
        decodedInsts_1_bge,
        decodedInsts_1_bne,
        decodedInsts_1_bgeu,
        decodedInsts_1_bltu,
        decodedInsts_1_mulhsu,
        decodedInsts_1_mulhu,
        decodedInsts_1_mul,
        decodedInsts_1_mulh,
        decodedInsts_1_lbu,
        decodedInsts_1_lhu,
        decodedInsts_1_lw,
        decodedInsts_1_lb,
        decodedInsts_1_lh,
        decodedInsts_1_sw,
        decodedInsts_1_sb,
        decodedInsts_1_sh,
        _GEN_27,
        _GEN_28,
        _GEN_29,
        _GEN_30,
        _GEN_31,
        _GEN_32,
        _GEN_33,
        _GEN_34,
        decodedInsts_2_sub,
        _GEN_35,
        _GEN_36,
        _GEN_37,
        _GEN_38,
        _GEN_39,
        _GEN_40,
        _GEN_41,
        _GEN_42,
        _GEN_43,
        decodedInsts_2_orn,
        decodedInsts_2_xnor,
        decodedInsts_2_lui,
        decodedInsts_2_andn,
        decodedInsts_2_ctz,
        decodedInsts_2_cpop,
        decodedInsts_2_clz,
        decodedInsts_2_min,
        decodedInsts_2_minu,
        decodedInsts_2_max,
        decodedInsts_2_maxu,
        decodedInsts_2_rol,
        decodedInsts_2_ror,
        decodedInsts_2_sextb,
        decodedInsts_2_sexth,
        decodedInsts_2_zexth,
        decodedInsts_2_rori,
        decodedInsts_2_orcb,
        decodedInsts_2_rev8,
        decodedInsts_2_jalr,
        decodedInsts_2_beq,
        decodedInsts_2_jal,
        decodedInsts_2_blt,
        decodedInsts_2_bge,
        decodedInsts_2_bne,
        decodedInsts_2_bgeu,
        decodedInsts_2_bltu,
        decodedInsts_2_mulhsu,
        decodedInsts_2_mulhu,
        decodedInsts_2_mul,
        decodedInsts_2_mulh,
        decodedInsts_2_lbu,
        decodedInsts_2_lhu,
        decodedInsts_2_lw,
        decodedInsts_2_lb,
        decodedInsts_2_lh,
        decodedInsts_2_sw,
        decodedInsts_2_sb,
        decodedInsts_2_sh,
        _GEN_44,
        _GEN_45,
        _GEN_46,
        _GEN_47,
        _GEN_48,
        _GEN_49,
        _GEN_50,
        _GEN_51,
        decodedInsts_3_sub,
        _GEN_52,
        _GEN_53,
        _GEN_54,
        _GEN_55,
        _GEN_56,
        _GEN_57,
        _GEN_58,
        _GEN_59,
        _GEN_60,
        decodedInsts_3_orn,
        decodedInsts_3_xnor,
        decodedInsts_3_lui,
        decodedInsts_3_andn,
        decodedInsts_3_ctz,
        decodedInsts_3_cpop,
        decodedInsts_3_clz,
        decodedInsts_3_min,
        decodedInsts_3_minu,
        decodedInsts_3_max,
        decodedInsts_3_maxu,
        decodedInsts_3_rol,
        decodedInsts_3_ror,
        decodedInsts_3_sextb,
        decodedInsts_3_sexth,
        decodedInsts_3_zexth,
        decodedInsts_3_rori,
        decodedInsts_3_orcb,
        decodedInsts_3_rev8,
        decodedInsts_3_jalr,
        decodedInsts_3_beq,
        decodedInsts_3_jal,
        decodedInsts_3_blt,
        decodedInsts_3_bge,
        decodedInsts_3_bne,
        decodedInsts_3_bgeu,
        decodedInsts_3_bltu,
        decodedInsts_3_mulhsu,
        decodedInsts_3_mulhu,
        decodedInsts_3_mul,
        decodedInsts_3_mulh,
        decodedInsts_3_lbu,
        decodedInsts_3_lhu,
        decodedInsts_3_lw,
        decodedInsts_3_lb,
        decodedInsts_3_lh,
        decodedInsts_3_sw,
        decodedInsts_3_sb,
        decodedInsts_3_sh,
        _GEN_61,
        _GEN_62,
        _GEN_63,
        _GEN_64,
        _GEN_65,
        _GEN_66,
        _GEN_67,
        _GEN_68,
        _GEN_69,
        _GEN_70,
        _GEN_71,
        clock
);

  `ifndef SYNTHESIS
    wire [1:0] _alu_bitsUInt_T_31 = {1'h0, decodedInsts_0_sub} + {1'h0, _GEN};
    wire [1:0] _GEN_72 = {1'h0, _GEN_0};
    wire [2:0] _GEN_73 = {1'h0, {1'h0, _GEN_3} + {1'h0, _GEN_4}};
    wire [2:0] _GEN_74 = {1'h0, {1'h0, _GEN_1} + {1'h0, _GEN_2}};
    wire [1:0] _alu_bitsUInt_T_43 = {1'h0, _GEN_5} + {1'h0, _GEN_6};
    wire [1:0] _GEN_75 = {1'h0, _GEN_7};
    wire [2:0] _GEN_76 = {1'h0, {1'h0, decodedInsts_0_lui} + {1'h0, decodedInsts_0_andn}};
    wire [2:0] _GEN_77 = {1'h0, {1'h0, decodedInsts_0_orn} + {1'h0, decodedInsts_0_xnor}};
    wire [1:0] _alu_bitsUInt_T_57 =
      {1'h0, decodedInsts_0_ctz} + {1'h0, decodedInsts_0_cpop};
    wire [1:0] _GEN_78 = {1'h0, decodedInsts_0_clz};
    wire [2:0] _GEN_79 = {1'h0, {1'h0, decodedInsts_0_max} + {1'h0, decodedInsts_0_maxu}};
    wire [2:0] _GEN_80 = {1'h0, {1'h0, decodedInsts_0_min} + {1'h0, decodedInsts_0_minu}};
    wire [2:0] _GEN_81 =
      {1'h0, {1'h0, decodedInsts_0_orcb} + {1'h0, decodedInsts_0_rev8}};
    wire [2:0] _GEN_82 =
      {1'h0, {1'h0, decodedInsts_0_zexth} + {1'h0, decodedInsts_0_rori}};
    wire [2:0] _GEN_83 =
      {1'h0, {1'h0, decodedInsts_0_sextb} + {1'h0, decodedInsts_0_sexth}};
    wire [2:0] _GEN_84 = {1'h0, {1'h0, decodedInsts_0_rol} + {1'h0, decodedInsts_0_ror}};
    wire [4:0] _GEN_85 = {4'h0, _GEN_8};
    wire [1:0] _bru_bitsUInt_T_15 =
      {1'h0, decodedInsts_0_jalr} + {1'h0, decodedInsts_0_beq};
    wire [1:0] _GEN_86 = {1'h0, decodedInsts_0_jal};
    wire [1:0] _bru_bitsUInt_T_19 =
      {1'h0, decodedInsts_0_blt} + {1'h0, decodedInsts_0_bge};
    wire [1:0] _GEN_87 = {1'h0, decodedInsts_0_bne};
    wire [1:0] _bru_bitsUInt_T_25 =
      {1'h0, decodedInsts_0_bgeu} + {1'h0, decodedInsts_0_ebreak};
    wire [1:0] _GEN_88 = {1'h0, decodedInsts_0_bltu};
    wire [1:0] _GEN_89 = {1'h0, decodedInsts_0_wfi};
    wire [2:0] _GEN_90 =
      {1'h0, {1'h0, decodedInsts_0_ecall} + {1'h0, decodedInsts_0_mpause}};
    wire [2:0] _GEN_91 = {1'h0, {1'h0, decodedInsts_0_mret} + _GEN_89};
    wire [3:0] _GEN_92 = {3'h0, _GEN_8};
    wire [2:0] _GEN_93 = {1'h0, {1'h0, decodedInsts_0_mul} + {1'h0, decodedInsts_0_mulh}};
    wire [2:0] _GEN_94 =
      {1'h0, {1'h0, decodedInsts_0_mulhsu} + {1'h0, decodedInsts_0_mulhu}};
    wire [2:0] _GEN_95 = {2'h0, _GEN_8};
    wire [2:0] _GEN_96 = {1'h0, {1'h0, decodedInsts_0_div} + {1'h0, decodedInsts_0_divu}};
    wire [2:0] _GEN_97 = {1'h0, {1'h0, decodedInsts_0_rem} + {1'h0, decodedInsts_0_remu}};
    wire [1:0] _lsu_bitsUInt_T_25 =
      {1'h0, decodedInsts_0_lbu} + {1'h0, decodedInsts_0_lhu};
    wire [1:0] _GEN_98 = {1'h0, decodedInsts_0_lw};
    wire [1:0] _lsu_bitsUInt_T_33 = _GEN_89 + {1'h0, decodedInsts_0_fencei};
    wire [1:0] _GEN_99 = {1'h0, decodedInsts_0_sw};
    wire [2:0] _GEN_100 = {1'h0, {1'h0, decodedInsts_0_sb} + {1'h0, decodedInsts_0_sh}};
    wire [2:0] _GEN_101 = {1'h0, {1'h0, decodedInsts_0_lb} + {1'h0, decodedInsts_0_lh}};
    wire [1:0] _lsu_bitsUInt_T_43 = {1'h0, _GEN_9} + {1'h0, _GEN_10};
    wire [1:0] _GEN_102 = {1'h0, _GEN_11};
    wire [1:0] _lsu_bitsUInt_T_49 = {1'h0, _GEN_12} + {1'h0, _GEN_13};
    wire [1:0] _GEN_103 = {1'h0, _GEN_14};
    wire [1:0] _lsu_bitsUInt_T_53 = {1'h0, _GEN_15} + {1'h0, _GEN_16};
    wire [1:0] _GEN_104 = {1'h0, _GEN_17};
    wire [2:0] _GEN_105 =
      {1'h0, {1'h0, decodedInsts_0_flushat} + {1'h0, decodedInsts_0_flushall}};
    wire [1:0] _csr_bitsUInt_T_5 =
      {1'h0, decodedInsts_0_csrrs} + {1'h0, decodedInsts_0_csrrc};
    wire [1:0] _GEN_106 = {1'h0, decodedInsts_0_csrrw};
    wire [1:0] _GEN_107 = {1'h0, _GEN_8};
    wire [1:0] _alu_bitsUInt_T_178 = {1'h0, decodedInsts_1_sub} + {1'h0, _GEN_18};
    wire [1:0] _GEN_108 = {1'h0, _GEN_19};
    wire [2:0] _GEN_109 = {1'h0, {1'h0, _GEN_22} + {1'h0, _GEN_23}};
    wire [2:0] _GEN_110 = {1'h0, {1'h0, _GEN_20} + {1'h0, _GEN_21}};
    wire [1:0] _alu_bitsUInt_T_190 = {1'h0, _GEN_24} + {1'h0, _GEN_25};
    wire [1:0] _GEN_111 = {1'h0, _GEN_26};
    wire [2:0] _GEN_112 =
      {1'h0, {1'h0, decodedInsts_1_lui} + {1'h0, decodedInsts_1_andn}};
    wire [2:0] _GEN_113 =
      {1'h0, {1'h0, decodedInsts_1_orn} + {1'h0, decodedInsts_1_xnor}};
    wire [1:0] _alu_bitsUInt_T_204 =
      {1'h0, decodedInsts_1_ctz} + {1'h0, decodedInsts_1_cpop};
    wire [1:0] _GEN_114 = {1'h0, decodedInsts_1_clz};
    wire [2:0] _GEN_115 =
      {1'h0, {1'h0, decodedInsts_1_max} + {1'h0, decodedInsts_1_maxu}};
    wire [2:0] _GEN_116 =
      {1'h0, {1'h0, decodedInsts_1_min} + {1'h0, decodedInsts_1_minu}};
    wire [2:0] _GEN_117 =
      {1'h0, {1'h0, decodedInsts_1_orcb} + {1'h0, decodedInsts_1_rev8}};
    wire [2:0] _GEN_118 =
      {1'h0, {1'h0, decodedInsts_1_zexth} + {1'h0, decodedInsts_1_rori}};
    wire [2:0] _GEN_119 =
      {1'h0, {1'h0, decodedInsts_1_sextb} + {1'h0, decodedInsts_1_sexth}};
    wire [2:0] _GEN_120 = {1'h0, {1'h0, decodedInsts_1_rol} + {1'h0, decodedInsts_1_ror}};
    wire [1:0] _bru_bitsUInt_T_82 =
      {1'h0, decodedInsts_1_jalr} + {1'h0, decodedInsts_1_beq};
    wire [1:0] _GEN_121 = {1'h0, decodedInsts_1_jal};
    wire [1:0] _bru_bitsUInt_T_86 =
      {1'h0, decodedInsts_1_blt} + {1'h0, decodedInsts_1_bge};
    wire [1:0] _GEN_122 = {1'h0, decodedInsts_1_bne};
    wire [1:0] _GEN_123 = {1'h0, decodedInsts_1_bgeu};
    wire [1:0] _GEN_124 = {1'h0, decodedInsts_1_bltu};
    wire [2:0] _GEN_125 =
      {1'h0, {1'h0, decodedInsts_1_mul} + {1'h0, decodedInsts_1_mulh}};
    wire [2:0] _GEN_126 =
      {1'h0, {1'h0, decodedInsts_1_mulhsu} + {1'h0, decodedInsts_1_mulhu}};
    wire [1:0] _lsu_bitsUInt_T_132 =
      {1'h0, decodedInsts_1_lbu} + {1'h0, decodedInsts_1_lhu};
    wire [1:0] _GEN_127 = {1'h0, decodedInsts_1_lw};
    wire [2:0] _GEN_128 = {1'h0, {1'h0, decodedInsts_1_sb} + {1'h0, decodedInsts_1_sh}};
    wire [2:0] _GEN_129 = {2'h0, decodedInsts_1_sw};
    wire [2:0] _GEN_130 = {1'h0, {1'h0, decodedInsts_1_lb} + {1'h0, decodedInsts_1_lh}};
    wire [1:0] _lsu_bitsUInt_T_156 = {1'h0, _GEN_27} + {1'h0, _GEN_28};
    wire [1:0] _GEN_131 = {1'h0, _GEN_29};
    wire [1:0] _lsu_bitsUInt_T_160 = {1'h0, _GEN_30} + {1'h0, _GEN_31};
    wire [1:0] _GEN_132 = {1'h0, _GEN_32};
    wire [3:0] _GEN_133 = {2'h0, {1'h0, _GEN_33} + {1'h0, _GEN_34}};
    wire [1:0] _alu_bitsUInt_T_325 = {1'h0, decodedInsts_2_sub} + {1'h0, _GEN_35};
    wire [1:0] _GEN_134 = {1'h0, _GEN_36};
    wire [2:0] _GEN_135 = {1'h0, {1'h0, _GEN_39} + {1'h0, _GEN_40}};
    wire [2:0] _GEN_136 = {1'h0, {1'h0, _GEN_37} + {1'h0, _GEN_38}};
    wire [1:0] _alu_bitsUInt_T_337 = {1'h0, _GEN_41} + {1'h0, _GEN_42};
    wire [1:0] _GEN_137 = {1'h0, _GEN_43};
    wire [2:0] _GEN_138 =
      {1'h0, {1'h0, decodedInsts_2_lui} + {1'h0, decodedInsts_2_andn}};
    wire [2:0] _GEN_139 =
      {1'h0, {1'h0, decodedInsts_2_orn} + {1'h0, decodedInsts_2_xnor}};
    wire [1:0] _alu_bitsUInt_T_351 =
      {1'h0, decodedInsts_2_ctz} + {1'h0, decodedInsts_2_cpop};
    wire [1:0] _GEN_140 = {1'h0, decodedInsts_2_clz};
    wire [2:0] _GEN_141 =
      {1'h0, {1'h0, decodedInsts_2_max} + {1'h0, decodedInsts_2_maxu}};
    wire [2:0] _GEN_142 =
      {1'h0, {1'h0, decodedInsts_2_min} + {1'h0, decodedInsts_2_minu}};
    wire [2:0] _GEN_143 =
      {1'h0, {1'h0, decodedInsts_2_orcb} + {1'h0, decodedInsts_2_rev8}};
    wire [2:0] _GEN_144 =
      {1'h0, {1'h0, decodedInsts_2_zexth} + {1'h0, decodedInsts_2_rori}};
    wire [2:0] _GEN_145 =
      {1'h0, {1'h0, decodedInsts_2_sextb} + {1'h0, decodedInsts_2_sexth}};
    wire [2:0] _GEN_146 = {1'h0, {1'h0, decodedInsts_2_rol} + {1'h0, decodedInsts_2_ror}};
    wire [1:0] _bru_bitsUInt_T_149 =
      {1'h0, decodedInsts_2_jalr} + {1'h0, decodedInsts_2_beq};
    wire [1:0] _GEN_147 = {1'h0, decodedInsts_2_jal};
    wire [1:0] _bru_bitsUInt_T_153 =
      {1'h0, decodedInsts_2_blt} + {1'h0, decodedInsts_2_bge};
    wire [1:0] _GEN_148 = {1'h0, decodedInsts_2_bne};
    wire [1:0] _GEN_149 = {1'h0, decodedInsts_2_bgeu};
    wire [1:0] _GEN_150 = {1'h0, decodedInsts_2_bltu};
    wire [2:0] _GEN_151 =
      {1'h0, {1'h0, decodedInsts_2_mul} + {1'h0, decodedInsts_2_mulh}};
    wire [2:0] _GEN_152 =
      {1'h0, {1'h0, decodedInsts_2_mulhsu} + {1'h0, decodedInsts_2_mulhu}};
    wire [1:0] _lsu_bitsUInt_T_239 =
      {1'h0, decodedInsts_2_lbu} + {1'h0, decodedInsts_2_lhu};
    wire [1:0] _GEN_153 = {1'h0, decodedInsts_2_lw};
    wire [2:0] _GEN_154 = {1'h0, {1'h0, decodedInsts_2_sb} + {1'h0, decodedInsts_2_sh}};
    wire [2:0] _GEN_155 = {2'h0, decodedInsts_2_sw};
    wire [2:0] _GEN_156 = {1'h0, {1'h0, decodedInsts_2_lb} + {1'h0, decodedInsts_2_lh}};
    wire [1:0] _lsu_bitsUInt_T_263 = {1'h0, _GEN_44} + {1'h0, _GEN_45};
    wire [1:0] _GEN_157 = {1'h0, _GEN_46};
    wire [1:0] _lsu_bitsUInt_T_267 = {1'h0, _GEN_47} + {1'h0, _GEN_48};
    wire [1:0] _GEN_158 = {1'h0, _GEN_49};
    wire [3:0] _GEN_159 = {2'h0, {1'h0, _GEN_50} + {1'h0, _GEN_51}};
    wire [1:0] _alu_bitsUInt_T_472 = {1'h0, decodedInsts_3_sub} + {1'h0, _GEN_52};
    wire [1:0] _GEN_160 = {1'h0, _GEN_53};
    wire [2:0] _GEN_161 = {1'h0, {1'h0, _GEN_56} + {1'h0, _GEN_57}};
    wire [2:0] _GEN_162 = {1'h0, {1'h0, _GEN_54} + {1'h0, _GEN_55}};
    wire [1:0] _alu_bitsUInt_T_484 = {1'h0, _GEN_58} + {1'h0, _GEN_59};
    wire [1:0] _GEN_163 = {1'h0, _GEN_60};
    wire [2:0] _GEN_164 =
      {1'h0, {1'h0, decodedInsts_3_lui} + {1'h0, decodedInsts_3_andn}};
    wire [2:0] _GEN_165 =
      {1'h0, {1'h0, decodedInsts_3_orn} + {1'h0, decodedInsts_3_xnor}};
    wire [1:0] _alu_bitsUInt_T_498 =
      {1'h0, decodedInsts_3_ctz} + {1'h0, decodedInsts_3_cpop};
    wire [1:0] _GEN_166 = {1'h0, decodedInsts_3_clz};
    wire [2:0] _GEN_167 =
      {1'h0, {1'h0, decodedInsts_3_max} + {1'h0, decodedInsts_3_maxu}};
    wire [2:0] _GEN_168 =
      {1'h0, {1'h0, decodedInsts_3_min} + {1'h0, decodedInsts_3_minu}};
    wire [2:0] _GEN_169 =
      {1'h0, {1'h0, decodedInsts_3_orcb} + {1'h0, decodedInsts_3_rev8}};
    wire [2:0] _GEN_170 =
      {1'h0, {1'h0, decodedInsts_3_zexth} + {1'h0, decodedInsts_3_rori}};
    wire [2:0] _GEN_171 =
      {1'h0, {1'h0, decodedInsts_3_sextb} + {1'h0, decodedInsts_3_sexth}};
    wire [2:0] _GEN_172 = {1'h0, {1'h0, decodedInsts_3_rol} + {1'h0, decodedInsts_3_ror}};
    wire [1:0] _bru_bitsUInt_T_216 =
      {1'h0, decodedInsts_3_jalr} + {1'h0, decodedInsts_3_beq};
    wire [1:0] _GEN_173 = {1'h0, decodedInsts_3_jal};
    wire [1:0] _bru_bitsUInt_T_220 =
      {1'h0, decodedInsts_3_blt} + {1'h0, decodedInsts_3_bge};
    wire [1:0] _GEN_174 = {1'h0, decodedInsts_3_bne};
    wire [1:0] _GEN_175 = {1'h0, decodedInsts_3_bgeu};
    wire [1:0] _GEN_176 = {1'h0, decodedInsts_3_bltu};
    wire [2:0] _GEN_177 =
      {1'h0, {1'h0, decodedInsts_3_mul} + {1'h0, decodedInsts_3_mulh}};
    wire [2:0] _GEN_178 =
      {1'h0, {1'h0, decodedInsts_3_mulhsu} + {1'h0, decodedInsts_3_mulhu}};
    wire [1:0] _lsu_bitsUInt_T_346 =
      {1'h0, decodedInsts_3_lbu} + {1'h0, decodedInsts_3_lhu};
    wire [1:0] _GEN_179 = {1'h0, decodedInsts_3_lw};
    wire [2:0] _GEN_180 = {1'h0, {1'h0, decodedInsts_3_sb} + {1'h0, decodedInsts_3_sh}};
    wire [2:0] _GEN_181 = {2'h0, decodedInsts_3_sw};
    wire [2:0] _GEN_182 = {1'h0, {1'h0, decodedInsts_3_lb} + {1'h0, decodedInsts_3_lh}};
    wire [1:0] _lsu_bitsUInt_T_370 = {1'h0, _GEN_61} + {1'h0, _GEN_62};
    wire [1:0] _GEN_183 = {1'h0, _GEN_63};
    wire [1:0] _lsu_bitsUInt_T_374 = {1'h0, _GEN_64} + {1'h0, _GEN_65};
    wire [1:0] _GEN_184 = {1'h0, _GEN_66};
    wire [3:0] _GEN_185 = {2'h0, {1'h0, _GEN_67} + {1'h0, _GEN_68}};
    always @(posedge clock) begin
      if (~reset
          & {1'h0,
             {1'h0, {1'h0, _GEN_72 + _alu_bitsUInt_T_31} + _GEN_73 + _GEN_74}
               + {1'h0, {1'h0, _GEN_75 + _alu_bitsUInt_T_43} + _GEN_76 + _GEN_77}}
          + {1'h0,
             {1'h0, {1'h0, _GEN_78 + _alu_bitsUInt_T_57} + _GEN_79 + _GEN_80}
               + {1'h0, _GEN_83 + _GEN_84} + {1'h0, _GEN_81 + _GEN_82}} > _GEN_85) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, {1'h0, _GEN_72 + _alu_bitsUInt_T_31} + _GEN_73 + _GEN_74}
               + {1'h0, {1'h0, _GEN_75 + _alu_bitsUInt_T_43} + _GEN_76 + _GEN_77}}
          + {1'h0,
             {1'h0, {1'h0, _GEN_78 + _alu_bitsUInt_T_57} + _GEN_79 + _GEN_80}
               + {1'h0, _GEN_83 + _GEN_84} + {1'h0, _GEN_81 + _GEN_82}} > _GEN_85) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, _GEN_86 + _bru_bitsUInt_T_15} + {1'h0, _GEN_87 + _bru_bitsUInt_T_19}}
          + {1'h0,
             {1'h0, _GEN_88 + _bru_bitsUInt_T_25} + _GEN_90 + _GEN_91} > _GEN_92) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, _GEN_86 + _bru_bitsUInt_T_15} + {1'h0, _GEN_87 + _bru_bitsUInt_T_19}}
          + {1'h0,
             {1'h0, _GEN_88 + _bru_bitsUInt_T_25} + _GEN_90 + _GEN_91} > _GEN_92) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _GEN_93 + _GEN_94 > _GEN_95) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _GEN_93 + _GEN_94 > _GEN_95) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _GEN_96 + _GEN_97 > _GEN_95) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _GEN_96 + _GEN_97 > _GEN_95) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, _GEN_101 + {1'h0, _GEN_98 + _lsu_bitsUInt_T_25}}
               + {1'h0, _GEN_100 + {1'h0, _GEN_99 + _lsu_bitsUInt_T_33}}}
          + {1'h0,
             {1'h0, _GEN_105 + {1'h0, _GEN_102 + _lsu_bitsUInt_T_43}}
               + {1'h0,
                  {1'h0, _GEN_103 + _lsu_bitsUInt_T_49}
                    + {1'h0, _GEN_104 + _lsu_bitsUInt_T_53}}} > _GEN_85) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, _GEN_101 + {1'h0, _GEN_98 + _lsu_bitsUInt_T_25}}
               + {1'h0, _GEN_100 + {1'h0, _GEN_99 + _lsu_bitsUInt_T_33}}}
          + {1'h0,
             {1'h0, _GEN_105 + {1'h0, _GEN_102 + _lsu_bitsUInt_T_43}}
               + {1'h0,
                  {1'h0, _GEN_103 + _lsu_bitsUInt_T_49}
                    + {1'h0, _GEN_104 + _lsu_bitsUInt_T_53}}} > _GEN_85) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _GEN_106 + _csr_bitsUInt_T_5 > _GEN_107) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _GEN_106 + _csr_bitsUInt_T_5 > _GEN_107) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, {1'h0, _GEN_108 + _alu_bitsUInt_T_178} + _GEN_109 + _GEN_110}
               + {1'h0, {1'h0, _GEN_111 + _alu_bitsUInt_T_190} + _GEN_112 + _GEN_113}}
          + {1'h0,
             {1'h0, {1'h0, _GEN_114 + _alu_bitsUInt_T_204} + _GEN_115 + _GEN_116}
               + {1'h0, _GEN_119 + _GEN_120}
               + {1'h0, _GEN_117 + _GEN_118}} > _GEN_85) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, {1'h0, _GEN_108 + _alu_bitsUInt_T_178} + _GEN_109 + _GEN_110}
               + {1'h0, {1'h0, _GEN_111 + _alu_bitsUInt_T_190} + _GEN_112 + _GEN_113}}
          + {1'h0,
             {1'h0, {1'h0, _GEN_114 + _alu_bitsUInt_T_204} + _GEN_115 + _GEN_116}
               + {1'h0, _GEN_119 + _GEN_120}
               + {1'h0, _GEN_117 + _GEN_118}} > _GEN_85) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, _GEN_121 + _bru_bitsUInt_T_82}
               + {1'h0, _GEN_122 + _bru_bitsUInt_T_86}}
          + {2'h0, _GEN_123 + _GEN_124} > _GEN_92) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, _GEN_121 + _bru_bitsUInt_T_82}
               + {1'h0, _GEN_122 + _bru_bitsUInt_T_86}}
          + {2'h0, _GEN_123 + _GEN_124} > _GEN_92) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _GEN_125 + _GEN_126 > _GEN_95) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _GEN_125 + _GEN_126 > _GEN_95) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, _GEN_130 + {1'h0, _GEN_127 + _lsu_bitsUInt_T_132}}
               + {1'h0, _GEN_128 + _GEN_129}}
          + {1'h0,
             _GEN_133
               + {1'h0,
                  {1'h0, _GEN_131 + _lsu_bitsUInt_T_156}
                    + {1'h0, _GEN_132 + _lsu_bitsUInt_T_160}}} > _GEN_85) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, _GEN_130 + {1'h0, _GEN_127 + _lsu_bitsUInt_T_132}}
               + {1'h0, _GEN_128 + _GEN_129}}
          + {1'h0,
             _GEN_133
               + {1'h0,
                  {1'h0, _GEN_131 + _lsu_bitsUInt_T_156}
                    + {1'h0, _GEN_132 + _lsu_bitsUInt_T_160}}} > _GEN_85) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, {1'h0, _GEN_134 + _alu_bitsUInt_T_325} + _GEN_135 + _GEN_136}
               + {1'h0, {1'h0, _GEN_137 + _alu_bitsUInt_T_337} + _GEN_138 + _GEN_139}}
          + {1'h0,
             {1'h0, {1'h0, _GEN_140 + _alu_bitsUInt_T_351} + _GEN_141 + _GEN_142}
               + {1'h0, _GEN_145 + _GEN_146}
               + {1'h0, _GEN_143 + _GEN_144}} > _GEN_85) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, {1'h0, _GEN_134 + _alu_bitsUInt_T_325} + _GEN_135 + _GEN_136}
               + {1'h0, {1'h0, _GEN_137 + _alu_bitsUInt_T_337} + _GEN_138 + _GEN_139}}
          + {1'h0,
             {1'h0, {1'h0, _GEN_140 + _alu_bitsUInt_T_351} + _GEN_141 + _GEN_142}
               + {1'h0, _GEN_145 + _GEN_146}
               + {1'h0, _GEN_143 + _GEN_144}} > _GEN_85) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, _GEN_147 + _bru_bitsUInt_T_149}
               + {1'h0, _GEN_148 + _bru_bitsUInt_T_153}}
          + {2'h0, _GEN_149 + _GEN_150} > _GEN_92) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, _GEN_147 + _bru_bitsUInt_T_149}
               + {1'h0, _GEN_148 + _bru_bitsUInt_T_153}}
          + {2'h0, _GEN_149 + _GEN_150} > _GEN_92) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _GEN_151 + _GEN_152 > _GEN_95) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _GEN_151 + _GEN_152 > _GEN_95) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, _GEN_156 + {1'h0, _GEN_153 + _lsu_bitsUInt_T_239}}
               + {1'h0, _GEN_154 + _GEN_155}}
          + {1'h0,
             _GEN_159
               + {1'h0,
                  {1'h0, _GEN_157 + _lsu_bitsUInt_T_263}
                    + {1'h0, _GEN_158 + _lsu_bitsUInt_T_267}}} > _GEN_85) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, _GEN_156 + {1'h0, _GEN_153 + _lsu_bitsUInt_T_239}}
               + {1'h0, _GEN_154 + _GEN_155}}
          + {1'h0,
             _GEN_159
               + {1'h0,
                  {1'h0, _GEN_157 + _lsu_bitsUInt_T_263}
                    + {1'h0, _GEN_158 + _lsu_bitsUInt_T_267}}} > _GEN_85) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, {1'h0, _GEN_160 + _alu_bitsUInt_T_472} + _GEN_161 + _GEN_162}
               + {1'h0, {1'h0, _GEN_163 + _alu_bitsUInt_T_484} + _GEN_164 + _GEN_165}}
          + {1'h0,
             {1'h0, {1'h0, _GEN_166 + _alu_bitsUInt_T_498} + _GEN_167 + _GEN_168}
               + {1'h0, _GEN_171 + _GEN_172}
               + {1'h0, _GEN_169 + _GEN_170}} > _GEN_85) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, {1'h0, _GEN_160 + _alu_bitsUInt_T_472} + _GEN_161 + _GEN_162}
               + {1'h0, {1'h0, _GEN_163 + _alu_bitsUInt_T_484} + _GEN_164 + _GEN_165}}
          + {1'h0,
             {1'h0, {1'h0, _GEN_166 + _alu_bitsUInt_T_498} + _GEN_167 + _GEN_168}
               + {1'h0, _GEN_171 + _GEN_172}
               + {1'h0, _GEN_169 + _GEN_170}} > _GEN_85) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, _GEN_173 + _bru_bitsUInt_T_216}
               + {1'h0, _GEN_174 + _bru_bitsUInt_T_220}}
          + {2'h0, _GEN_175 + _GEN_176} > _GEN_92) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, _GEN_173 + _bru_bitsUInt_T_216}
               + {1'h0, _GEN_174 + _bru_bitsUInt_T_220}}
          + {2'h0, _GEN_175 + _GEN_176} > _GEN_92) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _GEN_177 + _GEN_178 > _GEN_95) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _GEN_177 + _GEN_178 > _GEN_95) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, _GEN_182 + {1'h0, _GEN_179 + _lsu_bitsUInt_T_346}}
               + {1'h0, _GEN_180 + _GEN_181}}
          + {1'h0,
             _GEN_185
               + {1'h0,
                  {1'h0, _GEN_183 + _lsu_bitsUInt_T_370}
                    + {1'h0, _GEN_184 + _lsu_bitsUInt_T_374}}} > _GEN_85) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, _GEN_182 + {1'h0, _GEN_179 + _lsu_bitsUInt_T_346}}
               + {1'h0, _GEN_180 + _GEN_181}}
          + {1'h0,
             _GEN_185
               + {1'h0,
                  {1'h0, _GEN_183 + _lsu_bitsUInt_T_370}
                    + {1'h0, _GEN_184 + _lsu_bitsUInt_T_374}}} > _GEN_85) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & (|{_GEN_69, _GEN_70, _GEN_71})) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Decode.scala:885\n");
        if (`STOP_COND_)
          $fatal;
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
endmodule


`endif // Added by Core.scala Verification Wrapper
