`ifndef SYNTHESIS // Added by Core.scala Verification Wrapper

// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module FabricArbiter_Verification_Assert(
  input io_source_1_readDataAddr_valid,
        io_source_1_writeDataAddr_valid,
        io_source_0_readDataAddr_valid,
        io_source_0_writeDataAddr_valid,
        io_source_2_readDataAddr_valid,
        io_source_2_writeDataAddr_valid,
        reset,
        clock
);

  `ifndef SYNTHESIS
    always @(posedge clock) begin
      if (~reset
          & (io_source_0_readDataAddr_valid & io_source_0_writeDataAddr_valid
             | io_source_1_readDataAddr_valid & io_source_1_writeDataAddr_valid
             | io_source_2_readDataAddr_valid & io_source_2_writeDataAddr_valid)) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Fabric.scala:31\n");
        if (`STOP_COND_)
          $fatal;
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
endmodule


`endif // Added by Core.scala Verification Wrapper
