`ifndef SYNTHESIS // Added by Core.scala Verification Wrapper

// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module Mlu_Verification_Assert(
  input io_rs1_0_valid,
        stage2Input_q_io_deq_valid,
        _GEN,
        reset,
        io_rs2_0_valid,
        io_rs1_1_valid,
        _GEN_0,
        io_rs2_1_valid,
        io_rs1_2_valid,
        _GEN_1,
        io_rs2_2_valid,
        io_rs1_3_valid,
        _GEN_2,
        io_rs2_3_valid,
        clock
);

  `ifndef SYNTHESIS
    wire _GEN_3 = stage2Input_q_io_deq_valid & _GEN;
    wire _GEN_4 = stage2Input_q_io_deq_valid & _GEN_0;
    wire _GEN_5 = stage2Input_q_io_deq_valid & _GEN_1;
    wire _GEN_6 = stage2Input_q_io_deq_valid & _GEN_2;
    always @(posedge clock) begin
      if (~reset & _GEN_3 & ~io_rs1_0_valid) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Mlu.scala:124\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _GEN_3 & ~io_rs2_0_valid) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Mlu.scala:125\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _GEN_4 & ~io_rs1_1_valid) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Mlu.scala:124\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _GEN_4 & ~io_rs2_1_valid) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Mlu.scala:125\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _GEN_5 & ~io_rs1_2_valid) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Mlu.scala:124\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _GEN_5 & ~io_rs2_2_valid) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Mlu.scala:125\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _GEN_6 & ~io_rs1_3_valid) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Mlu.scala:124\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _GEN_6 & ~io_rs2_3_valid) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Mlu.scala:125\n");
        if (`STOP_COND_)
          $fatal;
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
endmodule


`endif // Added by Core.scala Verification Wrapper
