`ifndef SYNTHESIS // Added by Core.scala Verification Wrapper

// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module Regfile_Verification_Assert(
  input _GEN,
        _GEN_0,
        _GEN_1,
        _GEN_2,
        _GEN_3,
        _GEN_4,
        reset,
        _GEN_5,
        _GEN_6,
        _GEN_7,
        _GEN_8,
        _GEN_9,
        _GEN_10,
        _GEN_11,
        _GEN_12,
        _GEN_13,
        _GEN_14,
        _GEN_15,
        _GEN_16,
        _GEN_17,
        _GEN_18,
        _GEN_19,
        _GEN_20,
        _GEN_21,
        _GEN_22,
        _GEN_23,
        _GEN_24,
        _GEN_25,
        _GEN_26,
        _GEN_27,
        _GEN_28,
        _GEN_29,
        _GEN_30,
        _GEN_31,
        _GEN_32,
        _GEN_33,
        _GEN_34,
        _GEN_35,
        _GEN_36,
        _GEN_37,
        _GEN_38,
        _GEN_39,
        _GEN_40,
        _GEN_41,
        _GEN_42,
        _GEN_43,
        _GEN_44,
        _GEN_45,
        _GEN_46,
        _GEN_47,
        _GEN_48,
        _GEN_49,
        _GEN_50,
        _GEN_51,
        _GEN_52,
        _GEN_53,
        _GEN_54,
        _GEN_55,
        _GEN_56,
        _GEN_57,
        _GEN_58,
        _GEN_59,
        _GEN_60,
        _GEN_61,
        _GEN_62,
        _GEN_63,
        _GEN_64,
        _GEN_65,
        _GEN_66,
        _GEN_67,
        _GEN_68,
        _GEN_69,
        _GEN_70,
        _GEN_71,
        _GEN_72,
        _GEN_73,
        _GEN_74,
        _GEN_75,
        _GEN_76,
        _GEN_77,
        _GEN_78,
        _GEN_79,
        _GEN_80,
        _GEN_81,
        _GEN_82,
        _GEN_83,
        _GEN_84,
        _GEN_85,
        _GEN_86,
        _GEN_87,
        _GEN_88,
        _GEN_89,
        _GEN_90,
        _GEN_91,
        _GEN_92,
        _GEN_93,
        _GEN_94,
        _GEN_95,
        _GEN_96,
        _GEN_97,
        _GEN_98,
        _GEN_99,
        _GEN_100,
        _GEN_101,
        _GEN_102,
        _GEN_103,
        _GEN_104,
        _GEN_105,
        _GEN_106,
        _GEN_107,
        _GEN_108,
        _GEN_109,
        _GEN_110,
        _GEN_111,
        _GEN_112,
        _GEN_113,
        _GEN_114,
        _GEN_115,
        _GEN_116,
        _GEN_117,
        _GEN_118,
        _GEN_119,
        _GEN_120,
        _GEN_121,
        _GEN_122,
        _GEN_123,
        _GEN_124,
        _GEN_125,
        _GEN_126,
        _GEN_127,
        _GEN_128,
        _GEN_129,
        _GEN_130,
        _GEN_131,
        _GEN_132,
        _GEN_133,
        _GEN_134,
        _GEN_135,
        _GEN_136,
        _GEN_137,
        _GEN_138,
        _GEN_139,
        _GEN_140,
        _GEN_141,
        _GEN_142,
        _GEN_143,
        _GEN_144,
        _GEN_145,
        _GEN_146,
        _GEN_147,
        _GEN_148,
        _GEN_149,
        _GEN_150,
        _GEN_151,
        _GEN_152,
        _GEN_153,
        _GEN_154,
        _GEN_155,
        _GEN_156,
        _GEN_157,
        _GEN_158,
        _GEN_159,
        _GEN_160,
        _GEN_161,
        _GEN_162,
        _GEN_163,
        _GEN_164,
        _GEN_165,
        _GEN_166,
        _GEN_167,
        _GEN_168,
        _GEN_169,
        _GEN_170,
        _GEN_171,
        _GEN_172,
        _GEN_173,
        _GEN_174,
        _GEN_175,
        _GEN_176,
        _GEN_177,
        _GEN_178,
        _GEN_179,
        _GEN_180,
        _GEN_181,
        _GEN_182,
        _GEN_183,
        _GEN_184,
        _GEN_185,
        write_fail,
        write_fail_1,
        write_fail_2,
        write_fail_3,
        write_fail_4,
        write_fail_5,
        write_fail_6,
        write_fail_7,
        write_fail_8,
        write_fail_9,
        write_fail_10,
        write_fail_11,
        write_fail_12,
        write_fail_13,
        write_fail_14,
        scoreboard_error,
        clock
);

  `ifndef SYNTHESIS
    wire [2:0] _GEN_186 = {2'h0, _GEN_5};
    always @(posedge clock) begin
      if (~reset & {1'h0, {1'h0, _GEN_1} + {1'h0, _GEN} + {1'h0, _GEN_0}}
          + {1'h0, {1'h0, _GEN_4} + {1'h0, _GEN_2} + {1'h0, _GEN_3}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_8} + {1'h0, _GEN_6} + {1'h0, _GEN_7}}
          + {1'h0, {1'h0, _GEN_11} + {1'h0, _GEN_9} + {1'h0, _GEN_10}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_14} + {1'h0, _GEN_12} + {1'h0, _GEN_13}}
          + {1'h0, {1'h0, _GEN_17} + {1'h0, _GEN_15} + {1'h0, _GEN_16}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_20} + {1'h0, _GEN_18} + {1'h0, _GEN_19}}
          + {1'h0, {1'h0, _GEN_23} + {1'h0, _GEN_21} + {1'h0, _GEN_22}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_26} + {1'h0, _GEN_24} + {1'h0, _GEN_25}}
          + {1'h0, {1'h0, _GEN_29} + {1'h0, _GEN_27} + {1'h0, _GEN_28}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_32} + {1'h0, _GEN_30} + {1'h0, _GEN_31}}
          + {1'h0, {1'h0, _GEN_35} + {1'h0, _GEN_33} + {1'h0, _GEN_34}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_38} + {1'h0, _GEN_36} + {1'h0, _GEN_37}}
          + {1'h0, {1'h0, _GEN_41} + {1'h0, _GEN_39} + {1'h0, _GEN_40}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_44} + {1'h0, _GEN_42} + {1'h0, _GEN_43}}
          + {1'h0, {1'h0, _GEN_47} + {1'h0, _GEN_45} + {1'h0, _GEN_46}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_50} + {1'h0, _GEN_48} + {1'h0, _GEN_49}}
          + {1'h0, {1'h0, _GEN_53} + {1'h0, _GEN_51} + {1'h0, _GEN_52}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_56} + {1'h0, _GEN_54} + {1'h0, _GEN_55}}
          + {1'h0, {1'h0, _GEN_59} + {1'h0, _GEN_57} + {1'h0, _GEN_58}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_62} + {1'h0, _GEN_60} + {1'h0, _GEN_61}}
          + {1'h0, {1'h0, _GEN_65} + {1'h0, _GEN_63} + {1'h0, _GEN_64}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_68} + {1'h0, _GEN_66} + {1'h0, _GEN_67}}
          + {1'h0, {1'h0, _GEN_71} + {1'h0, _GEN_69} + {1'h0, _GEN_70}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_74} + {1'h0, _GEN_72} + {1'h0, _GEN_73}}
          + {1'h0, {1'h0, _GEN_77} + {1'h0, _GEN_75} + {1'h0, _GEN_76}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_80} + {1'h0, _GEN_78} + {1'h0, _GEN_79}}
          + {1'h0, {1'h0, _GEN_83} + {1'h0, _GEN_81} + {1'h0, _GEN_82}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_86} + {1'h0, _GEN_84} + {1'h0, _GEN_85}}
          + {1'h0, {1'h0, _GEN_89} + {1'h0, _GEN_87} + {1'h0, _GEN_88}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_92} + {1'h0, _GEN_90} + {1'h0, _GEN_91}}
          + {1'h0, {1'h0, _GEN_95} + {1'h0, _GEN_93} + {1'h0, _GEN_94}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_98} + {1'h0, _GEN_96} + {1'h0, _GEN_97}}
          + {1'h0,
             {1'h0, _GEN_101} + {1'h0, _GEN_99} + {1'h0, _GEN_100}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_104} + {1'h0, _GEN_102} + {1'h0, _GEN_103}}
          + {1'h0,
             {1'h0, _GEN_107} + {1'h0, _GEN_105} + {1'h0, _GEN_106}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_110} + {1'h0, _GEN_108} + {1'h0, _GEN_109}}
          + {1'h0,
             {1'h0, _GEN_113} + {1'h0, _GEN_111} + {1'h0, _GEN_112}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_116} + {1'h0, _GEN_114} + {1'h0, _GEN_115}}
          + {1'h0,
             {1'h0, _GEN_119} + {1'h0, _GEN_117} + {1'h0, _GEN_118}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_122} + {1'h0, _GEN_120} + {1'h0, _GEN_121}}
          + {1'h0,
             {1'h0, _GEN_125} + {1'h0, _GEN_123} + {1'h0, _GEN_124}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_128} + {1'h0, _GEN_126} + {1'h0, _GEN_127}}
          + {1'h0,
             {1'h0, _GEN_131} + {1'h0, _GEN_129} + {1'h0, _GEN_130}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_134} + {1'h0, _GEN_132} + {1'h0, _GEN_133}}
          + {1'h0,
             {1'h0, _GEN_137} + {1'h0, _GEN_135} + {1'h0, _GEN_136}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_140} + {1'h0, _GEN_138} + {1'h0, _GEN_139}}
          + {1'h0,
             {1'h0, _GEN_143} + {1'h0, _GEN_141} + {1'h0, _GEN_142}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_146} + {1'h0, _GEN_144} + {1'h0, _GEN_145}}
          + {1'h0,
             {1'h0, _GEN_149} + {1'h0, _GEN_147} + {1'h0, _GEN_148}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_152} + {1'h0, _GEN_150} + {1'h0, _GEN_151}}
          + {1'h0,
             {1'h0, _GEN_155} + {1'h0, _GEN_153} + {1'h0, _GEN_154}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_158} + {1'h0, _GEN_156} + {1'h0, _GEN_157}}
          + {1'h0,
             {1'h0, _GEN_161} + {1'h0, _GEN_159} + {1'h0, _GEN_160}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_164} + {1'h0, _GEN_162} + {1'h0, _GEN_163}}
          + {1'h0,
             {1'h0, _GEN_167} + {1'h0, _GEN_165} + {1'h0, _GEN_166}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_170} + {1'h0, _GEN_168} + {1'h0, _GEN_169}}
          + {1'h0,
             {1'h0, _GEN_173} + {1'h0, _GEN_171} + {1'h0, _GEN_172}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_176} + {1'h0, _GEN_174} + {1'h0, _GEN_175}}
          + {1'h0,
             {1'h0, _GEN_179} + {1'h0, _GEN_177} + {1'h0, _GEN_178}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_182} + {1'h0, _GEN_180} + {1'h0, _GEN_181}}
          + {1'h0,
             {1'h0, _GEN_185} + {1'h0, _GEN_183} + {1'h0, _GEN_184}} > _GEN_186) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:152\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & write_fail) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & write_fail_1) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & write_fail_2) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & write_fail_3) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & write_fail_4) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & write_fail_5) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & write_fail_6) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & write_fail_7) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & write_fail_8) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & write_fail_9) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & write_fail_10) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & write_fail_11) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & write_fail_12) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & write_fail_13) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & write_fail_14) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & scoreboard_error) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Regfile.scala:242\n");
        if (`STOP_COND_)
          $fatal;
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
endmodule


`endif // Added by Core.scala Verification Wrapper
