// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Alu(
  input         clock,
                reset,
                io_req_valid,
  input  [4:0]  io_req_bits_addr,
                io_req_bits_op,
  input         io_rs1_valid,
  input  [31:0] io_rs1_data,
  input         io_rs2_valid,
  input  [31:0] io_rs2_data,
  output        io_rd_valid,
  output [4:0]  io_rd_bits_addr,
  output [31:0] io_rd_bits_data
);

  reg               valid;
  reg  [4:0]        addr;
  reg  [4:0]        op;
  wire              r2IsGreater = $signed(io_rs1_data) < $signed(io_rs2_data);
  wire              r2IsGreaterU = io_rs1_data < io_rs2_data;
  wire [31:0]       _io_rd_bits_data_T_19 = io_rs1_data ^ io_rs2_data;
  wire [62:0]       _io_rd_bits_data_T_7 = {31'h0, io_rs1_data} << io_rs2_data[4:0];
  wire [31:0]       _GEN = {27'h0, io_rs2_data[4:0]};
  wire [31:0]       _io_rd_bits_data_T_29 =
    {16'h0, io_rs1_data[31:16]} | {io_rs1_data[15:0], 16'h0};
  wire [31:0]       _io_rd_bits_data_T_39 =
    {8'h0, _io_rd_bits_data_T_29[31:8] & 24'hFF00FF}
    | {_io_rd_bits_data_T_29[23:0] & 24'hFF00FF, 8'h0};
  wire [31:0]       _io_rd_bits_data_T_49 =
    {4'h0, _io_rd_bits_data_T_39[31:4] & 28'hF0F0F0F}
    | {_io_rd_bits_data_T_39[27:0] & 28'hF0F0F0F, 4'h0};
  wire [31:0]       _io_rd_bits_data_T_59 =
    {2'h0, _io_rd_bits_data_T_49[31:2] & 30'h33333333}
    | {_io_rd_bits_data_T_49[29:0] & 30'h33333333, 2'h0};
  wire [31:0]       _io_rd_bits_data_T_69 =
    {1'h0, _io_rd_bits_data_T_59[31:1] & 31'h55555555}
    | {_io_rd_bits_data_T_59[30:0] & 31'h55555555, 1'h0};
  wire [31:0]       _io_rd_bits_data_T_312 =
    io_rs2_data[0] ? {io_rs1_data[30:0], io_rs1_data[31]} : io_rs1_data;
  wire [31:0]       _io_rd_bits_data_T_316 =
    io_rs2_data[1]
      ? {_io_rd_bits_data_T_312[29:0], _io_rd_bits_data_T_312[31:30]}
      : _io_rd_bits_data_T_312;
  wire [31:0]       _io_rd_bits_data_T_320 =
    io_rs2_data[2]
      ? {_io_rd_bits_data_T_316[27:0], _io_rd_bits_data_T_316[31:28]}
      : _io_rd_bits_data_T_316;
  wire [31:0]       _io_rd_bits_data_T_324 =
    io_rs2_data[3]
      ? {_io_rd_bits_data_T_320[23:0], _io_rd_bits_data_T_320[31:24]}
      : _io_rd_bits_data_T_320;
  wire [31:0]       _io_rd_bits_data_T_337 =
    io_rs2_data[0] ? {io_rs1_data[0], io_rs1_data[31:1]} : io_rs1_data;
  wire [31:0]       _io_rd_bits_data_T_341 =
    io_rs2_data[1]
      ? {_io_rd_bits_data_T_337[1:0], _io_rd_bits_data_T_337[31:2]}
      : _io_rd_bits_data_T_337;
  wire [31:0]       _io_rd_bits_data_T_345 =
    io_rs2_data[2]
      ? {_io_rd_bits_data_T_341[3:0], _io_rd_bits_data_T_341[31:4]}
      : _io_rd_bits_data_T_341;
  wire [31:0]       _io_rd_bits_data_T_349 =
    io_rs2_data[3]
      ? {_io_rd_bits_data_T_345[7:0], _io_rd_bits_data_T_345[31:8]}
      : _io_rd_bits_data_T_345;
  wire [31:0][31:0] _GEN_0 =
    {{32'h0},
     {32'h0},
     {32'h0},
     {32'h0},
     {{16'h0, io_rs1_data[15:0]}},
     {{io_rs1_data[7:0], io_rs1_data[15:8], io_rs1_data[23:16], io_rs1_data[31:24]}},
     {{io_rs1_data[31:24] == 8'h0 ? 8'h0 : 8'hFF,
       io_rs1_data[23:16] == 8'h0 ? 8'h0 : 8'hFF,
       io_rs1_data[15:8] == 8'h0 ? 8'h0 : 8'hFF,
       io_rs1_data[7:0] == 8'h0 ? 8'h0 : 8'hFF}},
     {io_rs2_data[4]
        ? {_io_rd_bits_data_T_349[15:0], _io_rd_bits_data_T_349[31:16]}
        : _io_rd_bits_data_T_349},
     {io_rs2_data[4]
        ? {_io_rd_bits_data_T_324[15:0], _io_rd_bits_data_T_324[31:16]}
        : _io_rd_bits_data_T_324},
     {{{16{io_rs1_data[15]}}, io_rs1_data[15:0]}},
     {{{24{io_rs1_data[7]}}, io_rs1_data[7:0]}},
     {r2IsGreaterU ? io_rs1_data : io_rs2_data},
     {r2IsGreater ? io_rs1_data : io_rs2_data},
     {r2IsGreaterU ? io_rs2_data : io_rs1_data},
     {r2IsGreater ? io_rs2_data : io_rs1_data},
     {{26'h0,
       {1'h0,
        {1'h0,
         {1'h0,
          {1'h0, {1'h0, io_rs1_data[0]} + {1'h0, io_rs1_data[1]}}
            + {1'h0, {1'h0, io_rs1_data[2]} + {1'h0, io_rs1_data[3]}}}
           + {1'h0,
              {1'h0, {1'h0, io_rs1_data[4]} + {1'h0, io_rs1_data[5]}}
                + {1'h0, {1'h0, io_rs1_data[6]} + {1'h0, io_rs1_data[7]}}}}
          + {1'h0,
             {1'h0,
              {1'h0, {1'h0, io_rs1_data[8]} + {1'h0, io_rs1_data[9]}}
                + {1'h0, {1'h0, io_rs1_data[10]} + {1'h0, io_rs1_data[11]}}}
               + {1'h0,
                  {1'h0, {1'h0, io_rs1_data[12]} + {1'h0, io_rs1_data[13]}}
                    + {1'h0, {1'h0, io_rs1_data[14]} + {1'h0, io_rs1_data[15]}}}}}
         + {1'h0,
            {1'h0,
             {1'h0,
              {1'h0, {1'h0, io_rs1_data[16]} + {1'h0, io_rs1_data[17]}}
                + {1'h0, {1'h0, io_rs1_data[18]} + {1'h0, io_rs1_data[19]}}}
               + {1'h0,
                  {1'h0, {1'h0, io_rs1_data[20]} + {1'h0, io_rs1_data[21]}}
                    + {1'h0, {1'h0, io_rs1_data[22]} + {1'h0, io_rs1_data[23]}}}}
              + {1'h0,
                 {1'h0,
                  {1'h0, {1'h0, io_rs1_data[24]} + {1'h0, io_rs1_data[25]}}
                    + {1'h0, {1'h0, io_rs1_data[26]} + {1'h0, io_rs1_data[27]}}}
                   + {1'h0,
                      {1'h0, {1'h0, io_rs1_data[28]} + {1'h0, io_rs1_data[29]}}
                        + {1'h0, {1'h0, io_rs1_data[30]} + {1'h0, io_rs1_data[31]}}}}}}},
     {{26'h0,
       io_rs1_data[0]
         ? 6'h0
         : io_rs1_data[1]
             ? 6'h1
             : io_rs1_data[2]
                 ? 6'h2
                 : io_rs1_data[3]
                     ? 6'h3
                     : io_rs1_data[4]
                         ? 6'h4
                         : io_rs1_data[5]
                             ? 6'h5
                             : io_rs1_data[6]
                                 ? 6'h6
                                 : io_rs1_data[7]
                                     ? 6'h7
                                     : io_rs1_data[8]
                                         ? 6'h8
                                         : io_rs1_data[9]
                                             ? 6'h9
                                             : io_rs1_data[10]
                                                 ? 6'hA
                                                 : io_rs1_data[11]
                                                     ? 6'hB
                                                     : io_rs1_data[12]
                                                         ? 6'hC
                                                         : io_rs1_data[13]
                                                             ? 6'hD
                                                             : io_rs1_data[14]
                                                                 ? 6'hE
                                                                 : io_rs1_data[15]
                                                                     ? 6'hF
                                                                     : io_rs1_data[16]
                                                                         ? 6'h10
                                                                         : io_rs1_data[17]
                                                                             ? 6'h11
                                                                             : io_rs1_data[18]
                                                                                 ? 6'h12
                                                                                 : io_rs1_data[19]
                                                                                     ? 6'h13
                                                                                     : io_rs1_data[20]
                                                                                         ? 6'h14
                                                                                         : io_rs1_data[21]
                                                                                             ? 6'h15
                                                                                             : io_rs1_data[22]
                                                                                                 ? 6'h16
                                                                                                 : io_rs1_data[23]
                                                                                                     ? 6'h17
                                                                                                     : io_rs1_data[24]
                                                                                                         ? 6'h18
                                                                                                         : io_rs1_data[25]
                                                                                                             ? 6'h19
                                                                                                             : io_rs1_data[26]
                                                                                                                 ? 6'h1A
                                                                                                                 : io_rs1_data[27]
                                                                                                                     ? 6'h1B
                                                                                                                     : io_rs1_data[28]
                                                                                                                         ? 6'h1C
                                                                                                                         : io_rs1_data[29]
                                                                                                                             ? 6'h1D
                                                                                                                             : io_rs1_data[30]
                                                                                                                                 ? 6'h1E
                                                                                                                                 : io_rs1_data[31]
                                                                                                                                     ? 6'h1F
                                                                                                                                     : 6'h20}},
     {{26'h0,
       _io_rd_bits_data_T_69[0]
         ? 6'h0
         : _io_rd_bits_data_T_69[1]
             ? 6'h1
             : _io_rd_bits_data_T_69[2]
                 ? 6'h2
                 : _io_rd_bits_data_T_69[3]
                     ? 6'h3
                     : _io_rd_bits_data_T_69[4]
                         ? 6'h4
                         : _io_rd_bits_data_T_69[5]
                             ? 6'h5
                             : _io_rd_bits_data_T_69[6]
                                 ? 6'h6
                                 : _io_rd_bits_data_T_69[7]
                                     ? 6'h7
                                     : _io_rd_bits_data_T_69[8]
                                         ? 6'h8
                                         : _io_rd_bits_data_T_69[9]
                                             ? 6'h9
                                             : _io_rd_bits_data_T_69[10]
                                                 ? 6'hA
                                                 : _io_rd_bits_data_T_69[11]
                                                     ? 6'hB
                                                     : _io_rd_bits_data_T_69[12]
                                                         ? 6'hC
                                                         : _io_rd_bits_data_T_69[13]
                                                             ? 6'hD
                                                             : _io_rd_bits_data_T_69[14]
                                                                 ? 6'hE
                                                                 : _io_rd_bits_data_T_69[15]
                                                                     ? 6'hF
                                                                     : _io_rd_bits_data_T_69[16]
                                                                         ? 6'h10
                                                                         : _io_rd_bits_data_T_69[17]
                                                                             ? 6'h11
                                                                             : _io_rd_bits_data_T_69[18]
                                                                                 ? 6'h12
                                                                                 : _io_rd_bits_data_T_69[19]
                                                                                     ? 6'h13
                                                                                     : _io_rd_bits_data_T_69[20]
                                                                                         ? 6'h14
                                                                                         : _io_rd_bits_data_T_69[21]
                                                                                             ? 6'h15
                                                                                             : _io_rd_bits_data_T_69[22]
                                                                                                 ? 6'h16
                                                                                                 : _io_rd_bits_data_T_69[23]
                                                                                                     ? 6'h17
                                                                                                     : _io_rd_bits_data_T_69[24]
                                                                                                         ? 6'h18
                                                                                                         : _io_rd_bits_data_T_69[25]
                                                                                                             ? 6'h19
                                                                                                             : _io_rd_bits_data_T_69[26]
                                                                                                                 ? 6'h1A
                                                                                                                 : _io_rd_bits_data_T_69[27]
                                                                                                                     ? 6'h1B
                                                                                                                     : _io_rd_bits_data_T_69[28]
                                                                                                                         ? 6'h1C
                                                                                                                         : _io_rd_bits_data_T_69[29]
                                                                                                                             ? 6'h1D
                                                                                                                             : _io_rd_bits_data_T_69[30]
                                                                                                                                 ? 6'h1E
                                                                                                                                 : _io_rd_bits_data_T_69[31]
                                                                                                                                     ? 6'h1F
                                                                                                                                     : 6'h20}},
     {~_io_rd_bits_data_T_19},
     {io_rs1_data | ~io_rs2_data},
     {io_rs1_data & ~io_rs2_data},
     {io_rs2_data},
     {$signed($signed(io_rs1_data) >>> _GEN)},
     {io_rs1_data >> _GEN},
     {_io_rd_bits_data_T_7[31:0]},
     {io_rs1_data & io_rs2_data},
     {io_rs1_data | io_rs2_data},
     {_io_rd_bits_data_T_19},
     {{31'h0, r2IsGreaterU}},
     {{31'h0, r2IsGreater}},
     {io_rs1_data - io_rs2_data},
     {io_rs1_data + io_rs2_data}};
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      valid <= 1'h0;
      addr <= 5'h0;
      op <= 5'h0;
    end
    else begin
      valid <= io_req_valid;
      if (io_req_valid) begin
        addr <= io_req_bits_addr;
        op <= io_req_bits_op;
      end
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;
        valid = _RANDOM[/*Zero width*/ 1'b0][0];
        addr = _RANDOM[/*Zero width*/ 1'b0][5:1];
        op = _RANDOM[/*Zero width*/ 1'b0][10:6];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        valid = 1'h0;
        addr = 5'h0;
        op = 5'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_rd_valid = valid;
  assign io_rd_bits_addr = addr;
  assign io_rd_bits_data = _GEN_0[op];
endmodule

