// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1
module FabricArbiter(
  input          clock,
                 reset,
                 io_source_0_readDataAddr_valid,
  input  [31:0]  io_source_0_readDataAddr_bits,
  output [127:0] io_source_0_readData_bits,
  input          io_source_0_writeDataAddr_valid,
  input  [31:0]  io_source_0_writeDataAddr_bits,
  input  [127:0] io_source_0_writeDataBits,
  input  [15:0]  io_source_0_writeDataStrb,
  input          io_source_1_readDataAddr_valid,
  input  [31:0]  io_source_1_readDataAddr_bits,
  output         io_source_1_readData_valid,
  output [127:0] io_source_1_readData_bits,
  input          io_source_1_writeDataAddr_valid,
  input  [31:0]  io_source_1_writeDataAddr_bits,
  input  [127:0] io_source_1_writeDataBits,
  input  [15:0]  io_source_1_writeDataStrb,
  input          io_source_2_readDataAddr_valid,
  input  [31:0]  io_source_2_readDataAddr_bits,
  output         io_source_2_readData_valid,
  output [127:0] io_source_2_readData_bits,
  input          io_source_2_writeDataAddr_valid,
  input  [31:0]  io_source_2_writeDataAddr_bits,
  input  [127:0] io_source_2_writeDataBits,
  input  [15:0]  io_source_2_writeDataStrb,
  output         io_fabricBusy_1,
                 io_port_readDataAddr_valid,
  output [31:0]  io_port_readDataAddr_bits,
  input          io_port_readData_valid,
  input  [127:0] io_port_readData_bits,
  output         io_port_writeDataAddr_valid,
  output [31:0]  io_port_writeDataAddr_bits,
  output [127:0] io_port_writeDataBits,
  output [15:0]  io_port_writeDataStrb
);

  wire sourceValid_0 = io_source_0_readDataAddr_valid | io_source_0_writeDataAddr_valid;
  wire sourceValid_1 = io_source_1_readDataAddr_valid | io_source_1_writeDataAddr_valid;
  wire sourceValid_2 = io_source_2_readDataAddr_valid | io_source_2_writeDataAddr_valid;
  assign io_source_0_readData_bits = io_port_readData_bits;
  assign io_source_1_readData_valid = io_port_readData_valid;
  assign io_source_1_readData_bits = io_port_readData_bits;
  assign io_source_2_readData_valid = io_port_readData_valid;
  assign io_source_2_readData_bits = io_port_readData_bits;
  assign io_fabricBusy_1 = sourceValid_0;
  assign io_port_readDataAddr_valid =
    sourceValid_0
      ? io_source_0_readDataAddr_valid
      : sourceValid_1
          ? io_source_1_readDataAddr_valid
          : sourceValid_2 & io_source_2_readDataAddr_valid;
  assign io_port_readDataAddr_bits =
    sourceValid_0
      ? io_source_0_readDataAddr_bits
      : sourceValid_1
          ? io_source_1_readDataAddr_bits
          : sourceValid_2 ? io_source_2_readDataAddr_bits : 32'h0;
  assign io_port_writeDataAddr_valid =
    sourceValid_0
      ? io_source_0_writeDataAddr_valid
      : sourceValid_1
          ? io_source_1_writeDataAddr_valid
          : sourceValid_2 & io_source_2_writeDataAddr_valid;
  assign io_port_writeDataAddr_bits =
    sourceValid_0
      ? io_source_0_writeDataAddr_bits
      : sourceValid_1
          ? io_source_1_writeDataAddr_bits
          : sourceValid_2 ? io_source_2_writeDataAddr_bits : 32'h0;
  assign io_port_writeDataBits =
    sourceValid_0
      ? io_source_0_writeDataBits
      : sourceValid_1
          ? io_source_1_writeDataBits
          : sourceValid_2 ? io_source_2_writeDataBits : 128'h0;
  assign io_port_writeDataStrb =
    sourceValid_0
      ? io_source_0_writeDataStrb
      : sourceValid_1
          ? io_source_1_writeDataStrb
          : sourceValid_2 ? io_source_2_writeDataStrb : 16'h0;
endmodule

