// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module LsuSuperSlot(
  input          clock,
                 reset,
  output         io_uop_ready,
  input          io_uop_valid,
                 io_uop_bits_store,
  input  [4:0]   io_uop_bits_rd,
                 io_uop_bits_op,
  input  [31:0]  io_uop_bits_pc,
                 io_uop_bits_addr,
                 io_uop_bits_data,
  input          io_busReq_ready,
  output         io_busReq_valid,
  output [27:0]  io_busReq_bits_rowAddr,
  output         io_busReq_bits_write,
  output [127:0] io_busReq_bits_wdata,
  output [15:0]  io_busReq_bits_wmask,
  input          io_busResp_valid,
  input  [127:0] io_busResp_bits_rdata,
  input          io_busResp_bits_fault,
  output         io_intWriteback_valid,
  output [4:0]   io_intWriteback_bits_addr,
  output [31:0]  io_intWriteback_bits_data,
  output         io_floatWriteback_valid,
  output [4:0]   io_floatWriteback_bits_addr,
  output [31:0]  io_floatWriteback_bits_data,
                 io_pc,
  output         io_active,
                 io_storeComplete
);

  reg  [31:0]      state_pc;
  reg              state_write;
  reg              state_faulted;
  reg              state_strictMode;
  reg  [4:0]       state_rd;
  reg              state_skipWriteback;
  reg  [2:0]       state_scalarWritebackMode;
  reg              state_float_writeback;
  reg  [2:0]       state_cells_0_state;
  reg  [7:0]       state_cells_0_data;
  reg  [27:0]      state_cells_0_rowAddr;
  reg  [15:0]      state_cells_0_mask;
  reg  [2:0]       state_cells_1_state;
  reg  [7:0]       state_cells_1_data;
  reg  [27:0]      state_cells_1_rowAddr;
  reg  [15:0]      state_cells_1_mask;
  reg  [2:0]       state_cells_2_state;
  reg  [7:0]       state_cells_2_data;
  reg  [27:0]      state_cells_2_rowAddr;
  reg  [15:0]      state_cells_2_mask;
  reg  [2:0]       state_cells_3_state;
  reg  [7:0]       state_cells_3_data;
  reg  [27:0]      state_cells_3_rowAddr;
  reg  [15:0]      state_cells_3_mask;
  reg  [1:0]       index;
  reg  [27:0]      state_rowAddr;
  wire             newFault = io_busResp_valid & io_busResp_bits_fault;
  wire [3:0][2:0]  _GEN =
    {{state_cells_3_state},
     {state_cells_2_state},
     {state_cells_1_state},
     {state_cells_0_state}};
  wire [2:0]       _GEN_0 = _GEN[index];
  wire [3:0][7:0]  _GEN_1 =
    {{state_cells_3_data},
     {state_cells_2_data},
     {state_cells_1_data},
     {state_cells_0_data}};
  wire [7:0]       _GEN_2 = _GEN_1[index];
  wire [3:0][15:0] _GEN_3 =
    {{state_cells_3_mask},
     {state_cells_2_mask},
     {state_cells_1_mask},
     {state_cells_0_mask}};
  wire [15:0]      bundle_1_0 = _GEN_3[index];
  wire [1:0]       _cellCanStartWindow_index_T_5 = index + 2'h1;
  wire [1:0]       _cellCanStartWindow_index_T_6 = index - 2'h2;
  wire [1:0]       _cellCanStartWindow_index_T_7 = index - 2'h1;
  wire             reqValidNormal = _GEN_0 == 3'h2;
  wire             _stateFromAction_cellsNext_noBadWb_T_6 = state_cells_0_state == 3'h2;
  wire             _cellCanStartWindow_T_121 = state_cells_0_rowAddr == state_rowAddr;
  wire             _stateFromAction_cellsNext_noBadWb_T_17 = state_cells_1_state == 3'h2;
  wire             _cellCanStartWindow_T_124 = state_cells_1_rowAddr == state_rowAddr;
  wire             _stateFromAction_cellsNext_noBadWb_T_28 = state_cells_2_state == 3'h2;
  wire             _cellCanStartWindow_T_127 = state_cells_2_rowAddr == state_rowAddr;
  wire             _stateFromAction_cellsNext_noBadWb_T_39 = state_cells_3_state == 3'h2;
  wire             _cellCanStartWindow_T_130 = state_cells_3_rowAddr == state_rowAddr;
  wire [3:0]       _cellCanStartWindow_T_14 =
    {_stateFromAction_cellsNext_noBadWb_T_39 & _cellCanStartWindow_T_130,
     _stateFromAction_cellsNext_noBadWb_T_28 & _cellCanStartWindow_T_127,
     _stateFromAction_cellsNext_noBadWb_T_17 & _cellCanStartWindow_T_124,
     _stateFromAction_cellsNext_noBadWb_T_6 & _cellCanStartWindow_T_121} >> index;
  wire [3:0]       _GEN_4 = {2'h0, _cellCanStartWindow_index_T_5};
  wire [3:0]       _cellCanStartWindow_T_31 =
    {_stateFromAction_cellsNext_noBadWb_T_39 & _cellCanStartWindow_T_130,
     _stateFromAction_cellsNext_noBadWb_T_28 & _cellCanStartWindow_T_127,
     _stateFromAction_cellsNext_noBadWb_T_17 & _cellCanStartWindow_T_124,
     _stateFromAction_cellsNext_noBadWb_T_6 & _cellCanStartWindow_T_121} >> _GEN_4;
  wire [3:0]       _GEN_5 = {2'h0, _cellCanStartWindow_index_T_6};
  wire [3:0]       _cellCanStartWindow_T_48 =
    {_stateFromAction_cellsNext_noBadWb_T_39 & _cellCanStartWindow_T_130,
     _stateFromAction_cellsNext_noBadWb_T_28 & _cellCanStartWindow_T_127,
     _stateFromAction_cellsNext_noBadWb_T_17 & _cellCanStartWindow_T_124,
     _stateFromAction_cellsNext_noBadWb_T_6 & _cellCanStartWindow_T_121} >> _GEN_5;
  wire [3:0]       _GEN_6 = {2'h0, _cellCanStartWindow_index_T_7};
  wire [3:0]       _cellCanStartWindow_T_65 =
    {_stateFromAction_cellsNext_noBadWb_T_39 & _cellCanStartWindow_T_130,
     _stateFromAction_cellsNext_noBadWb_T_28 & _cellCanStartWindow_T_127,
     _stateFromAction_cellsNext_noBadWb_T_17 & _cellCanStartWindow_T_124,
     _stateFromAction_cellsNext_noBadWb_T_6 & _cellCanStartWindow_T_121} >> _GEN_6;
  wire [15:0]      bundle_0 = _cellCanStartWindow_T_14[0] ? bundle_1_0 : 16'h0;
  wire [15:0]      bundle_1 =
    _cellCanStartWindow_T_31[0] ? _GEN_3[_cellCanStartWindow_index_T_5] : 16'h0;
  wire [15:0]      bundle_2 =
    _cellCanStartWindow_T_48[0] ? _GEN_3[_cellCanStartWindow_index_T_6] : 16'h0;
  wire [15:0]      bundle_3 =
    _cellCanStartWindow_T_65[0] ? _GEN_3[_cellCanStartWindow_index_T_7] : 16'h0;
  wire [15:0]      wMaskNormal = bundle_0 | bundle_1 | bundle_2 | bundle_3;
  wire [3:0]       _cellCanStartWindow_T_99 =
    {_stateFromAction_cellsNext_noBadWb_T_39 & _cellCanStartWindow_T_130,
     _stateFromAction_cellsNext_noBadWb_T_28 & _cellCanStartWindow_T_127,
     _stateFromAction_cellsNext_noBadWb_T_17 & _cellCanStartWindow_T_124,
     _stateFromAction_cellsNext_noBadWb_T_6 & _cellCanStartWindow_T_121} >> _GEN_4;
  wire [3:0]       _cellCanStartWindow_T_116 =
    {_stateFromAction_cellsNext_noBadWb_T_39 & _cellCanStartWindow_T_130,
     _stateFromAction_cellsNext_noBadWb_T_28 & _cellCanStartWindow_T_127,
     _stateFromAction_cellsNext_noBadWb_T_17 & _cellCanStartWindow_T_124,
     _stateFromAction_cellsNext_noBadWb_T_6 & _cellCanStartWindow_T_121} >> _GEN_5;
  wire [3:0]       _cellCanStartWindow_T_133 =
    {_stateFromAction_cellsNext_noBadWb_T_39 & _cellCanStartWindow_T_130,
     _stateFromAction_cellsNext_noBadWb_T_28 & _cellCanStartWindow_T_127,
     _stateFromAction_cellsNext_noBadWb_T_17 & _cellCanStartWindow_T_124,
     _stateFromAction_cellsNext_noBadWb_T_6 & _cellCanStartWindow_T_121} >> _GEN_6;
  wire             cellActive_1 =
    _cellCanStartWindow_T_99[0]
    & (bundle_1_0 & _GEN_3[_cellCanStartWindow_index_T_5]) == 16'h0;
  wire [15:0]      prevMask = bundle_1_0 | _GEN_3[_cellCanStartWindow_index_T_5];
  wire             cellActive_2 =
    cellActive_1 & _cellCanStartWindow_T_116[0]
    & (prevMask & _GEN_3[_cellCanStartWindow_index_T_6]) == 16'h0;
  wire             cellActive_3 =
    cellActive_2 & _cellCanStartWindow_T_133[0]
    & ((prevMask | _GEN_3[_cellCanStartWindow_index_T_6])
       & _GEN_3[_cellCanStartWindow_index_T_7]) == 16'h0;
  wire [15:0]      bundle_1_1 =
    cellActive_1 ? _GEN_3[_cellCanStartWindow_index_T_5] : 16'h0;
  wire [15:0]      bundle_1_2 =
    cellActive_2 ? _GEN_3[_cellCanStartWindow_index_T_6] : 16'h0;
  wire [15:0]      bundle_1_3 =
    cellActive_3 ? _GEN_3[_cellCanStartWindow_index_T_7] : 16'h0;
  wire [3:0]       _GEN_7 = {{cellActive_3}, {cellActive_2}, {cellActive_1}, {1'h1}};
  wire             tx_y = state_strictMode ? _GEN_0 == 3'h2 : reqValidNormal;
  wire [127:0]     tx_y_1 =
    state_strictMode
      ? {(bundle_1_0[15] ? _GEN_2 : 8'h0)
           | (bundle_1_1[15] ? _GEN_1[_cellCanStartWindow_index_T_5] : 8'h0)
           | (bundle_1_2[15] ? _GEN_1[_cellCanStartWindow_index_T_6] : 8'h0)
           | (bundle_1_3[15] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0),
         (bundle_1_0[14] ? _GEN_2 : 8'h0)
           | (bundle_1_1[14] ? _GEN_1[_cellCanStartWindow_index_T_5] : 8'h0)
           | (bundle_1_2[14] ? _GEN_1[_cellCanStartWindow_index_T_6] : 8'h0)
           | (bundle_1_3[14] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0),
         (bundle_1_0[13] ? _GEN_2 : 8'h0)
           | (bundle_1_1[13] ? _GEN_1[_cellCanStartWindow_index_T_5] : 8'h0)
           | (bundle_1_2[13] ? _GEN_1[_cellCanStartWindow_index_T_6] : 8'h0)
           | (bundle_1_3[13] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0),
         (bundle_1_0[12] ? _GEN_2 : 8'h0)
           | (bundle_1_1[12] ? _GEN_1[_cellCanStartWindow_index_T_5] : 8'h0)
           | (bundle_1_2[12] ? _GEN_1[_cellCanStartWindow_index_T_6] : 8'h0)
           | (bundle_1_3[12] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0),
         (bundle_1_0[11] ? _GEN_2 : 8'h0)
           | (bundle_1_1[11] ? _GEN_1[_cellCanStartWindow_index_T_5] : 8'h0)
           | (bundle_1_2[11] ? _GEN_1[_cellCanStartWindow_index_T_6] : 8'h0)
           | (bundle_1_3[11] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0),
         (bundle_1_0[10] ? _GEN_2 : 8'h0)
           | (bundle_1_1[10] ? _GEN_1[_cellCanStartWindow_index_T_5] : 8'h0)
           | (bundle_1_2[10] ? _GEN_1[_cellCanStartWindow_index_T_6] : 8'h0)
           | (bundle_1_3[10] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0),
         (bundle_1_0[9] ? _GEN_2 : 8'h0)
           | (bundle_1_1[9] ? _GEN_1[_cellCanStartWindow_index_T_5] : 8'h0)
           | (bundle_1_2[9] ? _GEN_1[_cellCanStartWindow_index_T_6] : 8'h0)
           | (bundle_1_3[9] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0),
         (bundle_1_0[8] ? _GEN_2 : 8'h0)
           | (bundle_1_1[8] ? _GEN_1[_cellCanStartWindow_index_T_5] : 8'h0)
           | (bundle_1_2[8] ? _GEN_1[_cellCanStartWindow_index_T_6] : 8'h0)
           | (bundle_1_3[8] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0),
         (bundle_1_0[7] ? _GEN_2 : 8'h0)
           | (bundle_1_1[7] ? _GEN_1[_cellCanStartWindow_index_T_5] : 8'h0)
           | (bundle_1_2[7] ? _GEN_1[_cellCanStartWindow_index_T_6] : 8'h0)
           | (bundle_1_3[7] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0),
         (bundle_1_0[6] ? _GEN_2 : 8'h0)
           | (bundle_1_1[6] ? _GEN_1[_cellCanStartWindow_index_T_5] : 8'h0)
           | (bundle_1_2[6] ? _GEN_1[_cellCanStartWindow_index_T_6] : 8'h0)
           | (bundle_1_3[6] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0),
         (bundle_1_0[5] ? _GEN_2 : 8'h0)
           | (bundle_1_1[5] ? _GEN_1[_cellCanStartWindow_index_T_5] : 8'h0)
           | (bundle_1_2[5] ? _GEN_1[_cellCanStartWindow_index_T_6] : 8'h0)
           | (bundle_1_3[5] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0),
         (bundle_1_0[4] ? _GEN_2 : 8'h0)
           | (bundle_1_1[4] ? _GEN_1[_cellCanStartWindow_index_T_5] : 8'h0)
           | (bundle_1_2[4] ? _GEN_1[_cellCanStartWindow_index_T_6] : 8'h0)
           | (bundle_1_3[4] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0),
         (bundle_1_0[3] ? _GEN_2 : 8'h0)
           | (bundle_1_1[3] ? _GEN_1[_cellCanStartWindow_index_T_5] : 8'h0)
           | (bundle_1_2[3] ? _GEN_1[_cellCanStartWindow_index_T_6] : 8'h0)
           | (bundle_1_3[3] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0),
         (bundle_1_0[2] ? _GEN_2 : 8'h0)
           | (bundle_1_1[2] ? _GEN_1[_cellCanStartWindow_index_T_5] : 8'h0)
           | (bundle_1_2[2] ? _GEN_1[_cellCanStartWindow_index_T_6] : 8'h0)
           | (bundle_1_3[2] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0),
         (bundle_1_0[1] ? _GEN_2 : 8'h0)
           | (bundle_1_1[1] ? _GEN_1[_cellCanStartWindow_index_T_5] : 8'h0)
           | (bundle_1_2[1] ? _GEN_1[_cellCanStartWindow_index_T_6] : 8'h0)
           | (bundle_1_3[1] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0),
         (bundle_1_0[0] ? _GEN_2 : 8'h0)
           | (bundle_1_1[0] ? _GEN_1[_cellCanStartWindow_index_T_5] : 8'h0)
           | (bundle_1_2[0] ? _GEN_1[_cellCanStartWindow_index_T_6] : 8'h0)
           | (bundle_1_3[0] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0)}
      : {bundle_0[15]
           ? _GEN_2
           : bundle_1[15]
               ? _GEN_1[_cellCanStartWindow_index_T_5]
               : bundle_2[15]
                   ? _GEN_1[_cellCanStartWindow_index_T_6]
                   : bundle_3[15] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0,
         bundle_0[14]
           ? _GEN_2
           : bundle_1[14]
               ? _GEN_1[_cellCanStartWindow_index_T_5]
               : bundle_2[14]
                   ? _GEN_1[_cellCanStartWindow_index_T_6]
                   : bundle_3[14] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0,
         bundle_0[13]
           ? _GEN_2
           : bundle_1[13]
               ? _GEN_1[_cellCanStartWindow_index_T_5]
               : bundle_2[13]
                   ? _GEN_1[_cellCanStartWindow_index_T_6]
                   : bundle_3[13] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0,
         bundle_0[12]
           ? _GEN_2
           : bundle_1[12]
               ? _GEN_1[_cellCanStartWindow_index_T_5]
               : bundle_2[12]
                   ? _GEN_1[_cellCanStartWindow_index_T_6]
                   : bundle_3[12] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0,
         bundle_0[11]
           ? _GEN_2
           : bundle_1[11]
               ? _GEN_1[_cellCanStartWindow_index_T_5]
               : bundle_2[11]
                   ? _GEN_1[_cellCanStartWindow_index_T_6]
                   : bundle_3[11] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0,
         bundle_0[10]
           ? _GEN_2
           : bundle_1[10]
               ? _GEN_1[_cellCanStartWindow_index_T_5]
               : bundle_2[10]
                   ? _GEN_1[_cellCanStartWindow_index_T_6]
                   : bundle_3[10] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0,
         bundle_0[9]
           ? _GEN_2
           : bundle_1[9]
               ? _GEN_1[_cellCanStartWindow_index_T_5]
               : bundle_2[9]
                   ? _GEN_1[_cellCanStartWindow_index_T_6]
                   : bundle_3[9] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0,
         bundle_0[8]
           ? _GEN_2
           : bundle_1[8]
               ? _GEN_1[_cellCanStartWindow_index_T_5]
               : bundle_2[8]
                   ? _GEN_1[_cellCanStartWindow_index_T_6]
                   : bundle_3[8] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0,
         bundle_0[7]
           ? _GEN_2
           : bundle_1[7]
               ? _GEN_1[_cellCanStartWindow_index_T_5]
               : bundle_2[7]
                   ? _GEN_1[_cellCanStartWindow_index_T_6]
                   : bundle_3[7] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0,
         bundle_0[6]
           ? _GEN_2
           : bundle_1[6]
               ? _GEN_1[_cellCanStartWindow_index_T_5]
               : bundle_2[6]
                   ? _GEN_1[_cellCanStartWindow_index_T_6]
                   : bundle_3[6] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0,
         bundle_0[5]
           ? _GEN_2
           : bundle_1[5]
               ? _GEN_1[_cellCanStartWindow_index_T_5]
               : bundle_2[5]
                   ? _GEN_1[_cellCanStartWindow_index_T_6]
                   : bundle_3[5] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0,
         bundle_0[4]
           ? _GEN_2
           : bundle_1[4]
               ? _GEN_1[_cellCanStartWindow_index_T_5]
               : bundle_2[4]
                   ? _GEN_1[_cellCanStartWindow_index_T_6]
                   : bundle_3[4] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0,
         bundle_0[3]
           ? _GEN_2
           : bundle_1[3]
               ? _GEN_1[_cellCanStartWindow_index_T_5]
               : bundle_2[3]
                   ? _GEN_1[_cellCanStartWindow_index_T_6]
                   : bundle_3[3] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0,
         bundle_0[2]
           ? _GEN_2
           : bundle_1[2]
               ? _GEN_1[_cellCanStartWindow_index_T_5]
               : bundle_2[2]
                   ? _GEN_1[_cellCanStartWindow_index_T_6]
                   : bundle_3[2] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0,
         bundle_0[1]
           ? _GEN_2
           : bundle_1[1]
               ? _GEN_1[_cellCanStartWindow_index_T_5]
               : bundle_2[1]
                   ? _GEN_1[_cellCanStartWindow_index_T_6]
                   : bundle_3[1] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0,
         bundle_0[0]
           ? _GEN_2
           : bundle_1[0]
               ? _GEN_1[_cellCanStartWindow_index_T_5]
               : bundle_2[0]
                   ? _GEN_1[_cellCanStartWindow_index_T_6]
                   : bundle_3[0] ? _GEN_1[_cellCanStartWindow_index_T_7] : 8'h0};
  wire [15:0]      tx_y_2 =
    state_strictMode ? bundle_1_0 | bundle_1_1 | bundle_1_2 | bundle_1_3 : wMaskNormal;
  wire [3:0]       started =
    state_strictMode
      ? {_GEN_7[2'h3 - index],
         index != 2'h3 & _GEN_7[2'h2 - index],
         ~(index[1]) & _GEN_7[2'h1 - index],
         index == 2'h0 & _GEN_7[2'h0 - index]}
      : {_stateFromAction_cellsNext_noBadWb_T_39 & _cellCanStartWindow_T_130
           & (|{~state_write, state_cells_3_mask & wMaskNormal}),
         _stateFromAction_cellsNext_noBadWb_T_28 & _cellCanStartWindow_T_127
           & (|{~state_write, state_cells_2_mask & wMaskNormal}),
         _stateFromAction_cellsNext_noBadWb_T_17 & _cellCanStartWindow_T_124
           & (|{~state_write, state_cells_1_mask & wMaskNormal}),
         _stateFromAction_cellsNext_noBadWb_T_6 & _cellCanStartWindow_T_121
           & (|{~state_write, state_cells_0_mask & wMaskNormal})};
  reg              txPending_valid;
  reg  [27:0]      txPending_bits_rowAddr;
  reg              txPending_bits_write;
  reg  [127:0]     txPending_bits_wdata;
  reg  [15:0]      txPending_bits_wmask;
  wire             txOutgoing_valid = txPending_valid ? txPending_valid : tx_y;
  wire [27:0]      txOutgoing_bits_rowAddr =
    txPending_valid ? txPending_bits_rowAddr : state_rowAddr;
  wire             txOutgoing_bits_write =
    txPending_valid ? txPending_bits_write : state_write;
  wire             _stateFromAction_T = io_busReq_ready | state_faulted;
  wire             stateFromAction_faulted = state_faulted | newFault;
  wire             io_busReq_out_valid = ~stateFromAction_faulted & txOutgoing_valid;
  wire [27:0]      io_busReq_out_bits_rowAddr =
    stateFromAction_faulted ? 28'h0 : txOutgoing_bits_rowAddr;
  wire             io_busReq_out_bits_write =
    ~stateFromAction_faulted & txOutgoing_bits_write;
  wire [127:0]     io_busReq_out_bits_wdata =
    stateFromAction_faulted ? 128'h0 : txPending_valid ? txPending_bits_wdata : tx_y_1;
  wire [15:0]      io_busReq_out_bits_wmask =
    stateFromAction_faulted ? 16'h0 : txPending_valid ? txPending_bits_wmask : tx_y_2;
  reg              io_busReq_prevPending;
  reg  [27:0]      io_busReq_prevBits_rowAddr;
  reg              io_busReq_prevBits_write;
  reg  [127:0]     io_busReq_prevBits_wdata;
  reg  [15:0]      io_busReq_prevBits_wmask;
  reg              io_busReq_prevPending_1;
  reg  [27:0]      io_busReq_prevBits_1_rowAddr;
  reg              io_busReq_prevBits_1_write;
  reg  [127:0]     io_busReq_prevBits_1_wdata;
  reg  [15:0]      io_busReq_prevBits_1_wmask;
  reg  [27:0]      busRespRowAddr;
  reg  [3:0]       busRespMask;
  reg              faultRespValid;
  wire             scalar8Valid = state_cells_0_state == 3'h4;
  wire             scalarReq_valid =
    state_scalarWritebackMode == 3'h5
      ? state_cells_0_state == 3'h4 & state_cells_1_state == 3'h4
        & state_cells_2_state == 3'h4 & state_cells_3_state == 3'h4
      : state_scalarWritebackMode == 3'h4 | state_scalarWritebackMode == 3'h3
          ? state_cells_0_state == 3'h4 & state_cells_1_state == 3'h4
          : (state_scalarWritebackMode == 3'h2 | state_scalarWritebackMode == 3'h1)
            & scalar8Valid;
  wire [7:0][31:0] _GEN_8 =
    {{32'h0},
     {32'h0},
     {{state_cells_3_data, state_cells_2_data, state_cells_1_data, state_cells_0_data}},
     {{{16{state_cells_1_data[7]}}, state_cells_1_data, state_cells_0_data}},
     {{16'h0, state_cells_1_data, state_cells_0_data}},
     {{{24{state_cells_0_data[7]}}, state_cells_0_data}},
     {{24'h0, state_cells_0_data}},
     {32'h0}};
  wire [31:0]      scalarReq_bits = _GEN_8[state_scalarWritebackMode];
  wire             _io_storeComplete_T_3 = state_cells_1_state == 3'h4;
  wire             _io_storeComplete_T_6 = state_cells_2_state == 3'h4;
  wire             _io_storeComplete_T_9 = state_cells_3_state == 3'h4;
  wire             req_y_valid = ~state_float_writeback & scalarReq_valid;
  wire             writebackReq_float_valid = state_float_writeback & scalarReq_valid;
  wire             _io_storeComplete_T_1 = state_cells_0_state == 3'h0;
  wire             _io_storeComplete_T_4 = state_cells_1_state == 3'h0;
  wire             _io_storeComplete_T_7 = state_cells_2_state == 3'h0;
  wire             _io_storeComplete_T_10 = state_cells_3_state == 3'h0;
  wire [3:0]       _stateFromAction_T_2 =
    (_stateFromAction_T | newFault) & tx_y ? started : 4'h0;
  wire             _stateFromAction_T_4 = io_busResp_valid | faultRespValid;
  wire [3:0]       _stateFromAction_T_7 =
    (req_y_valid | writebackReq_float_valid) & (|state_scalarWritebackMode)
      ? {(|state_scalarWritebackMode) & _io_storeComplete_T_9,
         (|state_scalarWritebackMode) & _io_storeComplete_T_6,
         (|state_scalarWritebackMode) & _io_storeComplete_T_3,
         (|state_scalarWritebackMode) & scalar8Valid}
      : 4'h0;
  wire             _stateFromAction_cellsNext_cellAcceptResp_T_24 =
    state_strictMode | state_write;
  wire             _stateFromAction_cellsNext_noBadWb_T_7 = state_cells_0_state == 3'h3;
  wire             stateFromAction_cellsNext_cellAcceptResp =
    _stateFromAction_T_4
    & (_stateFromAction_cellsNext_cellAcceptResp_T_24
         ? busRespMask[0]
         : state_cells_0_rowAddr == busRespRowAddr
           & (_stateFromAction_cellsNext_noBadWb_T_6
              | _stateFromAction_cellsNext_noBadWb_T_7));
  wire             stateFromAction_cellsNext_cellWriteback =
    state_skipWriteback
      ? stateFromAction_cellsNext_cellAcceptResp
      : _stateFromAction_T_7[0];
  wire             stateFromAction_cellsNext_doStart =
    _stateFromAction_T_2[0] & ~stateFromAction_cellsNext_cellAcceptResp;
  wire             stateFromAction_cellsNext_doResp =
    stateFromAction_cellsNext_cellAcceptResp & ~stateFromAction_cellsNext_cellWriteback;
  wire             stateFromAction_cellsNext_precondition =
    {1'h0,
     {1'h0, stateFromAction_cellsNext_doStart} + {1'h0, stateFromAction_cellsNext_doResp}
       + {1'h0, stateFromAction_cellsNext_cellWriteback}} < 3'h2
    & (~stateFromAction_cellsNext_doStart | _stateFromAction_cellsNext_noBadWb_T_6)
    & (|{~stateFromAction_cellsNext_doResp,
         _stateFromAction_cellsNext_noBadWb_T_7,
         _stateFromAction_cellsNext_noBadWb_T_6})
    & ((|{~stateFromAction_cellsNext_cellWriteback, _io_storeComplete_T_1, scalar8Valid})
       | state_write
       & (|{_stateFromAction_cellsNext_noBadWb_T_7,
            _stateFromAction_cellsNext_noBadWb_T_6}))
    & (state_write | ~stateFromAction_cellsNext_cellAcceptResp
       | ~stateFromAction_cellsNext_cellWriteback);
  wire             _stateFromAction_cellsNext_retBase_defaultSel_T_4 =
    ~state_write & stateFromAction_cellsNext_doResp;
  wire [2:0]       stateFromAction_cells_0_state =
    stateFromAction_cellsNext_precondition
      ? (stateFromAction_cellsNext_doStart ? 3'h3 : 3'h0)
        | {stateFromAction_cellsNext_doResp, 2'h0}
        | (stateFromAction_cellsNext_doStart | stateFromAction_cellsNext_doResp
           | stateFromAction_cellsNext_cellWriteback
             ? 3'h0
             : state_cells_0_state)
      : 3'h0;
  wire             _stateFromAction_cellsNext_noBadWb_T_18 = state_cells_1_state == 3'h3;
  wire             stateFromAction_cellsNext_cellAcceptResp_1 =
    _stateFromAction_T_4
    & (_stateFromAction_cellsNext_cellAcceptResp_T_24
         ? busRespMask[1]
         : state_cells_1_rowAddr == busRespRowAddr
           & (_stateFromAction_cellsNext_noBadWb_T_17
              | _stateFromAction_cellsNext_noBadWb_T_18));
  wire             stateFromAction_cellsNext_cellWriteback_1 =
    state_skipWriteback
      ? stateFromAction_cellsNext_cellAcceptResp_1
      : _stateFromAction_T_7[1];
  wire             stateFromAction_cellsNext_doStart_1 =
    _stateFromAction_T_2[1] & ~stateFromAction_cellsNext_cellAcceptResp_1;
  wire             stateFromAction_cellsNext_doResp_1 =
    stateFromAction_cellsNext_cellAcceptResp_1
    & ~stateFromAction_cellsNext_cellWriteback_1;
  wire             stateFromAction_cellsNext_precondition_1 =
    {1'h0,
     {1'h0, stateFromAction_cellsNext_doStart_1}
       + {1'h0, stateFromAction_cellsNext_doResp_1}
       + {1'h0, stateFromAction_cellsNext_cellWriteback_1}} < 3'h2
    & (~stateFromAction_cellsNext_doStart_1 | _stateFromAction_cellsNext_noBadWb_T_17)
    & (|{~stateFromAction_cellsNext_doResp_1,
         _stateFromAction_cellsNext_noBadWb_T_18,
         _stateFromAction_cellsNext_noBadWb_T_17})
    & ((|{~stateFromAction_cellsNext_cellWriteback_1,
          _io_storeComplete_T_4,
          _io_storeComplete_T_3}) | state_write
       & (|{_stateFromAction_cellsNext_noBadWb_T_18,
            _stateFromAction_cellsNext_noBadWb_T_17}))
    & (state_write | ~stateFromAction_cellsNext_cellAcceptResp_1
       | ~stateFromAction_cellsNext_cellWriteback_1);
  wire             _stateFromAction_cellsNext_retBase_defaultSel_T_9 =
    ~state_write & stateFromAction_cellsNext_doResp_1;
  wire [2:0]       stateFromAction_cells_1_state =
    stateFromAction_cellsNext_precondition_1
      ? (stateFromAction_cellsNext_doStart_1 ? 3'h3 : 3'h0)
        | {stateFromAction_cellsNext_doResp_1, 2'h0}
        | (stateFromAction_cellsNext_doStart_1 | stateFromAction_cellsNext_doResp_1
           | stateFromAction_cellsNext_cellWriteback_1
             ? 3'h0
             : state_cells_1_state)
      : 3'h0;
  wire             _stateFromAction_cellsNext_noBadWb_T_29 = state_cells_2_state == 3'h3;
  wire             stateFromAction_cellsNext_cellAcceptResp_2 =
    _stateFromAction_T_4
    & (_stateFromAction_cellsNext_cellAcceptResp_T_24
         ? busRespMask[2]
         : state_cells_2_rowAddr == busRespRowAddr
           & (_stateFromAction_cellsNext_noBadWb_T_28
              | _stateFromAction_cellsNext_noBadWb_T_29));
  wire             stateFromAction_cellsNext_cellWriteback_2 =
    state_skipWriteback
      ? stateFromAction_cellsNext_cellAcceptResp_2
      : _stateFromAction_T_7[2];
  wire             stateFromAction_cellsNext_doStart_2 =
    _stateFromAction_T_2[2] & ~stateFromAction_cellsNext_cellAcceptResp_2;
  wire             stateFromAction_cellsNext_doResp_2 =
    stateFromAction_cellsNext_cellAcceptResp_2
    & ~stateFromAction_cellsNext_cellWriteback_2;
  wire             stateFromAction_cellsNext_precondition_2 =
    {1'h0,
     {1'h0, stateFromAction_cellsNext_doStart_2}
       + {1'h0, stateFromAction_cellsNext_doResp_2}
       + {1'h0, stateFromAction_cellsNext_cellWriteback_2}} < 3'h2
    & (~stateFromAction_cellsNext_doStart_2 | _stateFromAction_cellsNext_noBadWb_T_28)
    & (|{~stateFromAction_cellsNext_doResp_2,
         _stateFromAction_cellsNext_noBadWb_T_29,
         _stateFromAction_cellsNext_noBadWb_T_28})
    & ((|{~stateFromAction_cellsNext_cellWriteback_2,
          _io_storeComplete_T_7,
          _io_storeComplete_T_6}) | state_write
       & (|{_stateFromAction_cellsNext_noBadWb_T_29,
            _stateFromAction_cellsNext_noBadWb_T_28}))
    & (state_write | ~stateFromAction_cellsNext_cellAcceptResp_2
       | ~stateFromAction_cellsNext_cellWriteback_2);
  wire             _stateFromAction_cellsNext_retBase_defaultSel_T_14 =
    ~state_write & stateFromAction_cellsNext_doResp_2;
  wire [2:0]       stateFromAction_cells_2_state =
    stateFromAction_cellsNext_precondition_2
      ? (stateFromAction_cellsNext_doStart_2 ? 3'h3 : 3'h0)
        | {stateFromAction_cellsNext_doResp_2, 2'h0}
        | (stateFromAction_cellsNext_doStart_2 | stateFromAction_cellsNext_doResp_2
           | stateFromAction_cellsNext_cellWriteback_2
             ? 3'h0
             : state_cells_2_state)
      : 3'h0;
  wire             _stateFromAction_cellsNext_noBadWb_T_40 = state_cells_3_state == 3'h3;
  wire             stateFromAction_cellsNext_cellAcceptResp_3 =
    _stateFromAction_T_4
    & (_stateFromAction_cellsNext_cellAcceptResp_T_24
         ? busRespMask[3]
         : state_cells_3_rowAddr == busRespRowAddr
           & (_stateFromAction_cellsNext_noBadWb_T_39
              | _stateFromAction_cellsNext_noBadWb_T_40));
  wire             stateFromAction_cellsNext_cellWriteback_3 =
    state_skipWriteback
      ? stateFromAction_cellsNext_cellAcceptResp_3
      : _stateFromAction_T_7[3];
  wire             stateFromAction_cellsNext_doStart_3 =
    _stateFromAction_T_2[3] & ~stateFromAction_cellsNext_cellAcceptResp_3;
  wire             stateFromAction_cellsNext_doResp_3 =
    stateFromAction_cellsNext_cellAcceptResp_3
    & ~stateFromAction_cellsNext_cellWriteback_3;
  wire             stateFromAction_cellsNext_precondition_3 =
    {1'h0,
     {1'h0, stateFromAction_cellsNext_doStart_3}
       + {1'h0, stateFromAction_cellsNext_doResp_3}
       + {1'h0, stateFromAction_cellsNext_cellWriteback_3}} < 3'h2
    & (~stateFromAction_cellsNext_doStart_3 | _stateFromAction_cellsNext_noBadWb_T_39)
    & (|{~stateFromAction_cellsNext_doResp_3,
         _stateFromAction_cellsNext_noBadWb_T_40,
         _stateFromAction_cellsNext_noBadWb_T_39})
    & ((|{~stateFromAction_cellsNext_cellWriteback_3,
          _io_storeComplete_T_10,
          _io_storeComplete_T_9}) | state_write
       & (|{_stateFromAction_cellsNext_noBadWb_T_40,
            _stateFromAction_cellsNext_noBadWb_T_39}))
    & (state_write | ~stateFromAction_cellsNext_cellAcceptResp_3
       | ~stateFromAction_cellsNext_cellWriteback_3);
  wire             _stateFromAction_cellsNext_retBase_defaultSel_T_19 =
    ~state_write & stateFromAction_cellsNext_doResp_3;
  wire [2:0]       stateFromAction_cells_3_state =
    stateFromAction_cellsNext_precondition_3
      ? (stateFromAction_cellsNext_doStart_3 ? 3'h3 : 3'h0)
        | {stateFromAction_cellsNext_doResp_3, 2'h0}
        | (stateFromAction_cellsNext_doStart_3 | stateFromAction_cellsNext_doResp_3
           | stateFromAction_cellsNext_cellWriteback_3
             ? 3'h0
             : state_cells_3_state)
      : 3'h0;
  wire             _io_storeComplete_T_19 = stateFromAction_cells_0_state == 3'h0;
  wire             _io_storeComplete_T_22 = stateFromAction_cells_1_state == 3'h0;
  wire             _io_storeComplete_T_25 = stateFromAction_cells_2_state == 3'h0;
  wire             _io_storeComplete_T_28 = stateFromAction_cells_3_state == 3'h0;
  wire             io_uop_ready_0 =
    _io_storeComplete_T_19 & _io_storeComplete_T_22 & _io_storeComplete_T_25
    & _io_storeComplete_T_28;
  wire [31:0]      _stateFromUop_lookupSeqFloat_ret_T_24 = io_uop_bits_addr + 32'h1;
  wire [31:0]      _stateFromUop_lookupSeqFloat_ret_T_28 = io_uop_bits_addr + 32'h2;
  wire [31:0]      _stateFromUop_lookupSeqFloat_ret_T_32 = io_uop_bits_addr + 32'h3;
  wire [3:0][27:0] _GEN_9 =
    {{state_cells_3_rowAddr},
     {state_cells_2_rowAddr},
     {state_cells_1_rowAddr},
     {state_cells_0_rowAddr}};
  wire             _moveLead_T_24 = _GEN_0 != 3'h2;
  wire             _moveLead_T_55 = _GEN_0 != 3'h2;
  wire [1:0]       _stateFromAction_ret_T_1 =
    index
    + (~(_io_storeComplete_T_1 & _io_storeComplete_T_4 & _io_storeComplete_T_7
         & _io_storeComplete_T_10) & (~io_busReq_out_valid | io_busReq_ready)
         ? (state_strictMode
              ? (_GEN_0 == 3'h1
                   ? 2'h0
                   : _GEN[_cellCanStartWindow_index_T_5] == 3'h1
                     | _GEN[_cellCanStartWindow_index_T_5] == 3'h2
                     & (~cellActive_1 | _moveLead_T_55)
                       ? 2'h1
                       : _GEN[_cellCanStartWindow_index_T_6] == 3'h1
                         | _GEN[_cellCanStartWindow_index_T_6] == 3'h2
                         & (~cellActive_2 | _moveLead_T_55)
                           ? 2'h2
                           : {2{_GEN[_cellCanStartWindow_index_T_7] == 3'h1
                                  | _GEN[_cellCanStartWindow_index_T_7] == 3'h2
                                  & (~cellActive_3 | _moveLead_T_55)}})
              : _GEN_0 == 3'h1 | reqValidNormal
                & (_GEN_9[index] != state_rowAddr | _moveLead_T_24)
                  ? 2'h0
                  : _GEN[_cellCanStartWindow_index_T_5] == 3'h1
                    | _GEN[_cellCanStartWindow_index_T_5] == 3'h2
                    & (_GEN_9[_cellCanStartWindow_index_T_5] != state_rowAddr
                       | _moveLead_T_24)
                      ? 2'h1
                      : _GEN[_cellCanStartWindow_index_T_6] == 3'h1
                        | _GEN[_cellCanStartWindow_index_T_6] == 3'h2
                        & (_GEN_9[_cellCanStartWindow_index_T_6] != state_rowAddr
                           | _moveLead_T_24)
                          ? 2'h2
                          : {2{_GEN[_cellCanStartWindow_index_T_7] == 3'h1
                                 | _GEN[_cellCanStartWindow_index_T_7] == 3'h2
                                 & (_GEN_9[_cellCanStartWindow_index_T_7] != state_rowAddr
                                    | _moveLead_T_24)}})
         : 2'h0);
  wire [3:0][27:0] _GEN_10 =
    {{stateFromAction_cellsNext_precondition_3 ? state_cells_3_rowAddr : 28'h0},
     {stateFromAction_cellsNext_precondition_2 ? state_cells_2_rowAddr : 28'h0},
     {stateFromAction_cellsNext_precondition_1 ? state_cells_1_rowAddr : 28'h0},
     {stateFromAction_cellsNext_precondition ? state_cells_0_rowAddr : 28'h0}};
  wire             _txPending_T_1 = _stateFromAction_T | newFault;
  wire             _stateFromUop_T_1 = io_uop_bits_op == 5'h0;
  wire             _stateFromUop_T_3 = io_uop_bits_op == 5'h1;
  wire             _GEN_11 = _stateFromUop_T_3 | _stateFromUop_T_1;
  wire             _stateFromUop_T_5 = io_uop_bits_op == 5'h2;
  wire             _stateFromUop_T_7 = io_uop_bits_op == 5'h3;
  wire             _stateFromUop_T_9 = io_uop_bits_op == 5'h4;
  wire             _GEN_12 =
    _stateFromUop_T_9 | _stateFromUop_T_7 | _stateFromUop_T_5 | _GEN_11;
  wire             _stateFromUop_T_11 = io_uop_bits_op == 5'h5;
  wire             _stateFromUop_T_13 = io_uop_bits_op == 5'h6;
  wire             _stateFromUop_T_15 = io_uop_bits_op == 5'h7;
  wire             _GEN_13 =
    _stateFromUop_T_15 | _stateFromUop_T_13 | _stateFromUop_T_11 | _GEN_12;
  wire             _stateFromUop_T_17 = io_uop_bits_op == 5'hC;
  wire             _GEN_14 = _stateFromUop_T_17 | _GEN_13;
  wire             _state_T = io_uop_ready_0 & io_uop_valid;
  wire             _GEN_15 = _stateFromUop_T_9 | _stateFromUop_T_7;
  wire             _GEN_16 = _stateFromUop_T_15 | _stateFromUop_T_13 | _stateFromUop_T_11;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      state_pc <= 32'h0;
      state_write <= 1'h0;
      state_faulted <= 1'h0;
      state_strictMode <= 1'h0;
      state_rd <= 5'h0;
      state_skipWriteback <= 1'h0;
      state_scalarWritebackMode <= 3'h0;
      state_float_writeback <= 1'h0;
      state_cells_0_state <= 3'h0;
      state_cells_0_data <= 8'h0;
      state_cells_0_rowAddr <= 28'h0;
      state_cells_0_mask <= 16'h0;
      state_cells_1_state <= 3'h0;
      state_cells_1_data <= 8'h0;
      state_cells_1_rowAddr <= 28'h0;
      state_cells_1_mask <= 16'h0;
      state_cells_2_state <= 3'h0;
      state_cells_2_data <= 8'h0;
      state_cells_2_rowAddr <= 28'h0;
      state_cells_2_mask <= 16'h0;
      state_cells_3_state <= 3'h0;
      state_cells_3_data <= 8'h0;
      state_cells_3_rowAddr <= 28'h0;
      state_cells_3_mask <= 16'h0;
      index <= 2'h0;
      state_rowAddr <= 28'h0;
      txPending_valid <= 1'h0;
      txPending_bits_rowAddr <= 28'h0;
      txPending_bits_write <= 1'h0;
      txPending_bits_wdata <= 128'h0;
      txPending_bits_wmask <= 16'h0;
      io_busReq_prevPending <= 1'h0;
      io_busReq_prevPending_1 <= 1'h0;
      busRespRowAddr <= 28'h0;
      busRespMask <= 4'h0;
      faultRespValid <= 1'h0;
    end
    else begin
      if (_state_T & _GEN_14)
        state_pc <= io_uop_bits_pc;
      if (_state_T) begin
        state_write <=
          _stateFromUop_T_17 ? io_uop_bits_store : _GEN_16 | ~_GEN_12 & state_write;
        state_skipWriteback <=
          _stateFromUop_T_17
            ? io_uop_bits_store
            : _GEN_16 | ~_GEN_12 & state_skipWriteback;
        if (_stateFromUop_T_17) begin
          state_scalarWritebackMode <= io_uop_bits_store ? 3'h0 : 3'h5;
          state_cells_0_rowAddr <=
            io_uop_bits_store ? io_uop_bits_addr[31:4] : io_uop_bits_addr[31:4];
          state_cells_0_mask <=
            io_uop_bits_store
              ? 16'h1 << io_uop_bits_addr[3:0]
              : 16'h1 << io_uop_bits_addr[3:0];
          state_cells_1_rowAddr <=
            io_uop_bits_store
              ? _stateFromUop_lookupSeqFloat_ret_T_24[31:4]
              : _stateFromUop_lookupSeqFloat_ret_T_24[31:4];
          state_cells_1_mask <=
            io_uop_bits_store
              ? 16'h1 << _stateFromUop_lookupSeqFloat_ret_T_24[3:0]
              : 16'h1 << _stateFromUop_lookupSeqFloat_ret_T_24[3:0];
          state_cells_2_rowAddr <=
            io_uop_bits_store
              ? _stateFromUop_lookupSeqFloat_ret_T_28[31:4]
              : _stateFromUop_lookupSeqFloat_ret_T_28[31:4];
          state_cells_2_mask <=
            io_uop_bits_store
              ? 16'h1 << _stateFromUop_lookupSeqFloat_ret_T_28[3:0]
              : 16'h1 << _stateFromUop_lookupSeqFloat_ret_T_28[3:0];
          state_cells_3_rowAddr <=
            io_uop_bits_store
              ? _stateFromUop_lookupSeqFloat_ret_T_32[31:4]
              : _stateFromUop_lookupSeqFloat_ret_T_32[31:4];
          state_cells_3_mask <=
            io_uop_bits_store
              ? 16'h1 << _stateFromUop_lookupSeqFloat_ret_T_32[3:0]
              : 16'h1 << _stateFromUop_lookupSeqFloat_ret_T_32[3:0];
        end
        else begin
          if (_GEN_16)
            state_scalarWritebackMode <= 3'h0;
          else if (_stateFromUop_T_9)
            state_scalarWritebackMode <= 3'h3;
          else if (_stateFromUop_T_7)
            state_scalarWritebackMode <= 3'h1;
          else if (_stateFromUop_T_5)
            state_scalarWritebackMode <= 3'h5;
          else if (_stateFromUop_T_3)
            state_scalarWritebackMode <= 3'h4;
          else if (_stateFromUop_T_1)
            state_scalarWritebackMode <= 3'h2;
          if (_stateFromUop_T_15) begin
            state_cells_0_rowAddr <= io_uop_bits_addr[31:4];
            state_cells_0_mask <= 16'h1 << io_uop_bits_addr[3:0];
            state_cells_1_rowAddr <= _stateFromUop_lookupSeqFloat_ret_T_24[31:4];
            state_cells_1_mask <= 16'h1 << _stateFromUop_lookupSeqFloat_ret_T_24[3:0];
            state_cells_2_rowAddr <= _stateFromUop_lookupSeqFloat_ret_T_28[31:4];
            state_cells_2_mask <= 16'h1 << _stateFromUop_lookupSeqFloat_ret_T_28[3:0];
            state_cells_3_rowAddr <= _stateFromUop_lookupSeqFloat_ret_T_32[31:4];
            state_cells_3_mask <= 16'h1 << _stateFromUop_lookupSeqFloat_ret_T_32[3:0];
          end
          else begin
            if (_stateFromUop_T_13) begin
              state_cells_0_rowAddr <= io_uop_bits_addr[31:4];
              state_cells_0_mask <= 16'h1 << io_uop_bits_addr[3:0];
              state_cells_1_rowAddr <= _stateFromUop_lookupSeqFloat_ret_T_24[31:4];
              state_cells_1_mask <= 16'h1 << _stateFromUop_lookupSeqFloat_ret_T_24[3:0];
            end
            else if (_stateFromUop_T_11) begin
              state_cells_0_rowAddr <= io_uop_bits_addr[31:4];
              state_cells_0_mask <= 16'h1 << io_uop_bits_addr[3:0];
            end
            else if (_stateFromUop_T_9) begin
              state_cells_0_rowAddr <= io_uop_bits_addr[31:4];
              state_cells_0_mask <= 16'h1 << io_uop_bits_addr[3:0];
              state_cells_1_rowAddr <= _stateFromUop_lookupSeqFloat_ret_T_24[31:4];
              state_cells_1_mask <= 16'h1 << _stateFromUop_lookupSeqFloat_ret_T_24[3:0];
            end
            else if (_stateFromUop_T_7) begin
              state_cells_0_rowAddr <= io_uop_bits_addr[31:4];
              state_cells_0_mask <= 16'h1 << io_uop_bits_addr[3:0];
            end
            else if (_stateFromUop_T_5) begin
              state_cells_0_rowAddr <= io_uop_bits_addr[31:4];
              state_cells_0_mask <= 16'h1 << io_uop_bits_addr[3:0];
              state_cells_1_rowAddr <= _stateFromUop_lookupSeqFloat_ret_T_24[31:4];
              state_cells_1_mask <= 16'h1 << _stateFromUop_lookupSeqFloat_ret_T_24[3:0];
            end
            else if (_stateFromUop_T_3) begin
              state_cells_0_rowAddr <= io_uop_bits_addr[31:4];
              state_cells_0_mask <= 16'h1 << io_uop_bits_addr[3:0];
              state_cells_1_rowAddr <= _stateFromUop_lookupSeqFloat_ret_T_24[31:4];
              state_cells_1_mask <= 16'h1 << _stateFromUop_lookupSeqFloat_ret_T_24[3:0];
            end
            else if (_stateFromUop_T_1) begin
              state_cells_0_rowAddr <= io_uop_bits_addr[31:4];
              state_cells_0_mask <= 16'h1 << io_uop_bits_addr[3:0];
            end
            if (_stateFromUop_T_13 | _stateFromUop_T_11 | _stateFromUop_T_9
                | _stateFromUop_T_7 | ~_stateFromUop_T_5) begin
            end
            else begin
              state_cells_2_rowAddr <= _stateFromUop_lookupSeqFloat_ret_T_28[31:4];
              state_cells_2_mask <= 16'h1 << _stateFromUop_lookupSeqFloat_ret_T_28[3:0];
              state_cells_3_rowAddr <= _stateFromUop_lookupSeqFloat_ret_T_32[31:4];
              state_cells_3_mask <= 16'h1 << _stateFromUop_lookupSeqFloat_ret_T_32[3:0];
            end
          end
        end
        state_float_writeback <=
          _stateFromUop_T_17 ? ~io_uop_bits_store : ~_GEN_13 & state_float_writeback;
        if (_stateFromUop_T_17 | _GEN_16 | _GEN_15 | _stateFromUop_T_5 | _stateFromUop_T_3
            | _stateFromUop_T_1)
          state_cells_0_state <= 3'h2;
        if (_stateFromUop_T_17
              ? io_uop_bits_store
              : _stateFromUop_T_15 | _stateFromUop_T_13 | _stateFromUop_T_11)
          state_cells_0_data <= io_uop_bits_data[7:0];
        if (_stateFromUop_T_17 | _stateFromUop_T_15 | _stateFromUop_T_13)
          state_cells_1_state <= 3'h2;
        else if (_stateFromUop_T_11)
          state_cells_1_state <= 3'h0;
        else if (_stateFromUop_T_9)
          state_cells_1_state <= 3'h2;
        else if (_stateFromUop_T_7)
          state_cells_1_state <= 3'h0;
        else if (_stateFromUop_T_5 | _stateFromUop_T_3)
          state_cells_1_state <= 3'h2;
        else if (_stateFromUop_T_1)
          state_cells_1_state <= 3'h0;
        if (_stateFromUop_T_17
              ? io_uop_bits_store
              : _stateFromUop_T_15 | _stateFromUop_T_13)
          state_cells_1_data <= io_uop_bits_data[15:8];
        if (_stateFromUop_T_17 | _stateFromUop_T_15) begin
          state_cells_2_state <= 3'h2;
          state_cells_3_state <= 3'h2;
        end
        else if (_stateFromUop_T_13 | _stateFromUop_T_11 | _GEN_15) begin
          state_cells_2_state <= 3'h0;
          state_cells_3_state <= 3'h0;
        end
        else if (_stateFromUop_T_5) begin
          state_cells_2_state <= 3'h2;
          state_cells_3_state <= 3'h2;
        end
        else if (_GEN_11) begin
          state_cells_2_state <= 3'h0;
          state_cells_3_state <= 3'h0;
        end
        if (_stateFromUop_T_17 ? io_uop_bits_store : _stateFromUop_T_15) begin
          state_cells_2_data <= io_uop_bits_data[23:16];
          state_cells_3_data <= io_uop_bits_data[31:24];
        end
        if (_GEN_14)
          index <= 2'h0;
        if (_stateFromUop_T_17 | _stateFromUop_T_15 | _stateFromUop_T_13
            | _stateFromUop_T_11 | _stateFromUop_T_9 | _stateFromUop_T_7
            | _stateFromUop_T_5 | _stateFromUop_T_3 | _stateFromUop_T_1)
          state_rowAddr <= io_uop_bits_addr[31:4];
      end
      else begin
        state_cells_0_state <= stateFromAction_cells_0_state;
        state_cells_0_data <=
          stateFromAction_cellsNext_precondition
            ? (_stateFromAction_cellsNext_retBase_defaultSel_T_4
                 ? (state_cells_0_mask[0] ? io_busResp_bits_rdata[7:0] : 8'h0)
                   | (state_cells_0_mask[1] ? io_busResp_bits_rdata[15:8] : 8'h0)
                   | (state_cells_0_mask[2] ? io_busResp_bits_rdata[23:16] : 8'h0)
                   | (state_cells_0_mask[3] ? io_busResp_bits_rdata[31:24] : 8'h0)
                   | (state_cells_0_mask[4] ? io_busResp_bits_rdata[39:32] : 8'h0)
                   | (state_cells_0_mask[5] ? io_busResp_bits_rdata[47:40] : 8'h0)
                   | (state_cells_0_mask[6] ? io_busResp_bits_rdata[55:48] : 8'h0)
                   | (state_cells_0_mask[7] ? io_busResp_bits_rdata[63:56] : 8'h0)
                   | (state_cells_0_mask[8] ? io_busResp_bits_rdata[71:64] : 8'h0)
                   | (state_cells_0_mask[9] ? io_busResp_bits_rdata[79:72] : 8'h0)
                   | (state_cells_0_mask[10] ? io_busResp_bits_rdata[87:80] : 8'h0)
                   | (state_cells_0_mask[11] ? io_busResp_bits_rdata[95:88] : 8'h0)
                   | (state_cells_0_mask[12] ? io_busResp_bits_rdata[103:96] : 8'h0)
                   | (state_cells_0_mask[13] ? io_busResp_bits_rdata[111:104] : 8'h0)
                   | (state_cells_0_mask[14] ? io_busResp_bits_rdata[119:112] : 8'h0)
                   | (state_cells_0_mask[15] ? io_busResp_bits_rdata[127:120] : 8'h0)
                 : 8'h0)
              | (_stateFromAction_cellsNext_retBase_defaultSel_T_4
                   ? 8'h0
                   : state_cells_0_data)
            : 8'h0;
        if (~stateFromAction_cellsNext_precondition) begin
          state_cells_0_rowAddr <= 28'h0;
          state_cells_0_mask <= 16'h0;
        end
        state_cells_1_state <= stateFromAction_cells_1_state;
        state_cells_1_data <=
          stateFromAction_cellsNext_precondition_1
            ? (_stateFromAction_cellsNext_retBase_defaultSel_T_9
                 ? (state_cells_1_mask[0] ? io_busResp_bits_rdata[7:0] : 8'h0)
                   | (state_cells_1_mask[1] ? io_busResp_bits_rdata[15:8] : 8'h0)
                   | (state_cells_1_mask[2] ? io_busResp_bits_rdata[23:16] : 8'h0)
                   | (state_cells_1_mask[3] ? io_busResp_bits_rdata[31:24] : 8'h0)
                   | (state_cells_1_mask[4] ? io_busResp_bits_rdata[39:32] : 8'h0)
                   | (state_cells_1_mask[5] ? io_busResp_bits_rdata[47:40] : 8'h0)
                   | (state_cells_1_mask[6] ? io_busResp_bits_rdata[55:48] : 8'h0)
                   | (state_cells_1_mask[7] ? io_busResp_bits_rdata[63:56] : 8'h0)
                   | (state_cells_1_mask[8] ? io_busResp_bits_rdata[71:64] : 8'h0)
                   | (state_cells_1_mask[9] ? io_busResp_bits_rdata[79:72] : 8'h0)
                   | (state_cells_1_mask[10] ? io_busResp_bits_rdata[87:80] : 8'h0)
                   | (state_cells_1_mask[11] ? io_busResp_bits_rdata[95:88] : 8'h0)
                   | (state_cells_1_mask[12] ? io_busResp_bits_rdata[103:96] : 8'h0)
                   | (state_cells_1_mask[13] ? io_busResp_bits_rdata[111:104] : 8'h0)
                   | (state_cells_1_mask[14] ? io_busResp_bits_rdata[119:112] : 8'h0)
                   | (state_cells_1_mask[15] ? io_busResp_bits_rdata[127:120] : 8'h0)
                 : 8'h0)
              | (_stateFromAction_cellsNext_retBase_defaultSel_T_9
                   ? 8'h0
                   : state_cells_1_data)
            : 8'h0;
        if (~stateFromAction_cellsNext_precondition_1) begin
          state_cells_1_rowAddr <= 28'h0;
          state_cells_1_mask <= 16'h0;
        end
        state_cells_2_state <= stateFromAction_cells_2_state;
        state_cells_2_data <=
          stateFromAction_cellsNext_precondition_2
            ? (_stateFromAction_cellsNext_retBase_defaultSel_T_14
                 ? (state_cells_2_mask[0] ? io_busResp_bits_rdata[7:0] : 8'h0)
                   | (state_cells_2_mask[1] ? io_busResp_bits_rdata[15:8] : 8'h0)
                   | (state_cells_2_mask[2] ? io_busResp_bits_rdata[23:16] : 8'h0)
                   | (state_cells_2_mask[3] ? io_busResp_bits_rdata[31:24] : 8'h0)
                   | (state_cells_2_mask[4] ? io_busResp_bits_rdata[39:32] : 8'h0)
                   | (state_cells_2_mask[5] ? io_busResp_bits_rdata[47:40] : 8'h0)
                   | (state_cells_2_mask[6] ? io_busResp_bits_rdata[55:48] : 8'h0)
                   | (state_cells_2_mask[7] ? io_busResp_bits_rdata[63:56] : 8'h0)
                   | (state_cells_2_mask[8] ? io_busResp_bits_rdata[71:64] : 8'h0)
                   | (state_cells_2_mask[9] ? io_busResp_bits_rdata[79:72] : 8'h0)
                   | (state_cells_2_mask[10] ? io_busResp_bits_rdata[87:80] : 8'h0)
                   | (state_cells_2_mask[11] ? io_busResp_bits_rdata[95:88] : 8'h0)
                   | (state_cells_2_mask[12] ? io_busResp_bits_rdata[103:96] : 8'h0)
                   | (state_cells_2_mask[13] ? io_busResp_bits_rdata[111:104] : 8'h0)
                   | (state_cells_2_mask[14] ? io_busResp_bits_rdata[119:112] : 8'h0)
                   | (state_cells_2_mask[15] ? io_busResp_bits_rdata[127:120] : 8'h0)
                 : 8'h0)
              | (_stateFromAction_cellsNext_retBase_defaultSel_T_14
                   ? 8'h0
                   : state_cells_2_data)
            : 8'h0;
        if (~stateFromAction_cellsNext_precondition_2) begin
          state_cells_2_rowAddr <= 28'h0;
          state_cells_2_mask <= 16'h0;
        end
        state_cells_3_state <= stateFromAction_cells_3_state;
        state_cells_3_data <=
          stateFromAction_cellsNext_precondition_3
            ? (_stateFromAction_cellsNext_retBase_defaultSel_T_19
                 ? (state_cells_3_mask[0] ? io_busResp_bits_rdata[7:0] : 8'h0)
                   | (state_cells_3_mask[1] ? io_busResp_bits_rdata[15:8] : 8'h0)
                   | (state_cells_3_mask[2] ? io_busResp_bits_rdata[23:16] : 8'h0)
                   | (state_cells_3_mask[3] ? io_busResp_bits_rdata[31:24] : 8'h0)
                   | (state_cells_3_mask[4] ? io_busResp_bits_rdata[39:32] : 8'h0)
                   | (state_cells_3_mask[5] ? io_busResp_bits_rdata[47:40] : 8'h0)
                   | (state_cells_3_mask[6] ? io_busResp_bits_rdata[55:48] : 8'h0)
                   | (state_cells_3_mask[7] ? io_busResp_bits_rdata[63:56] : 8'h0)
                   | (state_cells_3_mask[8] ? io_busResp_bits_rdata[71:64] : 8'h0)
                   | (state_cells_3_mask[9] ? io_busResp_bits_rdata[79:72] : 8'h0)
                   | (state_cells_3_mask[10] ? io_busResp_bits_rdata[87:80] : 8'h0)
                   | (state_cells_3_mask[11] ? io_busResp_bits_rdata[95:88] : 8'h0)
                   | (state_cells_3_mask[12] ? io_busResp_bits_rdata[103:96] : 8'h0)
                   | (state_cells_3_mask[13] ? io_busResp_bits_rdata[111:104] : 8'h0)
                   | (state_cells_3_mask[14] ? io_busResp_bits_rdata[119:112] : 8'h0)
                   | (state_cells_3_mask[15] ? io_busResp_bits_rdata[127:120] : 8'h0)
                 : 8'h0)
              | (_stateFromAction_cellsNext_retBase_defaultSel_T_19
                   ? 8'h0
                   : state_cells_3_data)
            : 8'h0;
        if (~stateFromAction_cellsNext_precondition_3) begin
          state_cells_3_rowAddr <= 28'h0;
          state_cells_3_mask <= 16'h0;
        end
        index <= _stateFromAction_ret_T_1;
        state_rowAddr <= _GEN_10[_stateFromAction_ret_T_1];
      end
      state_faulted <= _state_T ? ~_GEN_14 & state_faulted : stateFromAction_faulted;
      state_strictMode <= (~_state_T | ~_GEN_14) & state_strictMode;
      if (~_state_T
          | (_stateFromUop_T_17
               ? io_uop_bits_store
               : _stateFromUop_T_15 | _stateFromUop_T_13 | _stateFromUop_T_11
                 | ~_GEN_12)) begin
      end
      else
        state_rd <= io_uop_bits_rd;
      txPending_valid <= ~_txPending_T_1 & txOutgoing_valid;
      if (_txPending_T_1) begin
        txPending_bits_rowAddr <= 28'h0;
        txPending_bits_wdata <= 128'h0;
        txPending_bits_wmask <= 16'h0;
      end
      else if (txPending_valid) begin
      end
      else begin
        txPending_bits_rowAddr <= state_rowAddr;
        txPending_bits_wdata <= tx_y_1;
        txPending_bits_wmask <= tx_y_2;
      end
      txPending_bits_write <= ~_txPending_T_1 & txOutgoing_bits_write;
      io_busReq_prevPending <= io_busReq_out_valid & ~io_busReq_ready;
      io_busReq_prevPending_1 <= io_busReq_out_valid & ~io_busReq_ready;
      busRespRowAddr <= txOutgoing_bits_rowAddr;
      busRespMask <= tx_y ? started : 4'h0;
      faultRespValid <= txOutgoing_valid & stateFromAction_faulted;
    end
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    io_busReq_prevBits_rowAddr <= io_busReq_out_bits_rowAddr;
    io_busReq_prevBits_write <= io_busReq_out_bits_write;
    io_busReq_prevBits_wdata <= io_busReq_out_bits_wdata;
    io_busReq_prevBits_wmask <= io_busReq_out_bits_wmask;
    io_busReq_prevBits_1_rowAddr <= io_busReq_out_bits_rowAddr;
    io_busReq_prevBits_1_write <= io_busReq_out_bits_write;
    io_busReq_prevBits_1_wdata <= io_busReq_out_bits_wdata;
    io_busReq_prevBits_1_wmask <= io_busReq_out_bits_wmask;
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:26];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [4:0] i = 5'h0; i < 5'h1B; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        state_pc = _RANDOM[5'h0];
        state_write = _RANDOM[5'h1][0];
        state_faulted = _RANDOM[5'h1][1];
        state_strictMode = _RANDOM[5'h1][2];
        state_rd = _RANDOM[5'h1][7:3];
        state_skipWriteback = _RANDOM[5'h1][8];
        state_scalarWritebackMode = _RANDOM[5'h1][11:9];
        state_float_writeback = _RANDOM[5'h1][12];
        state_cells_0_state = _RANDOM[5'h1][15:13];
        state_cells_0_data = _RANDOM[5'h1][23:16];
        state_cells_0_rowAddr = {_RANDOM[5'h1][31:24], _RANDOM[5'h2][19:0]};
        state_cells_0_mask = {_RANDOM[5'h2][31:20], _RANDOM[5'h3][3:0]};
        state_cells_1_state = _RANDOM[5'h3][6:4];
        state_cells_1_data = _RANDOM[5'h3][14:7];
        state_cells_1_rowAddr = {_RANDOM[5'h3][31:15], _RANDOM[5'h4][10:0]};
        state_cells_1_mask = _RANDOM[5'h4][26:11];
        state_cells_2_state = _RANDOM[5'h4][29:27];
        state_cells_2_data = {_RANDOM[5'h4][31:30], _RANDOM[5'h5][5:0]};
        state_cells_2_rowAddr = {_RANDOM[5'h5][31:6], _RANDOM[5'h6][1:0]};
        state_cells_2_mask = _RANDOM[5'h6][17:2];
        state_cells_3_state = _RANDOM[5'h6][20:18];
        state_cells_3_data = _RANDOM[5'h6][28:21];
        state_cells_3_rowAddr = {_RANDOM[5'h6][31:29], _RANDOM[5'h7][24:0]};
        state_cells_3_mask = {_RANDOM[5'h7][31:25], _RANDOM[5'h8][8:0]};
        index = _RANDOM[5'h8][10:9];
        state_rowAddr = {_RANDOM[5'h8][31:11], _RANDOM[5'h9][6:0]};
        txPending_valid = _RANDOM[5'h9][8];
        txPending_bits_rowAddr = {_RANDOM[5'h9][31:9], _RANDOM[5'hA][4:0]};
        txPending_bits_write = _RANDOM[5'hA][5];
        txPending_bits_wdata =
          {_RANDOM[5'hA][31:6],
           _RANDOM[5'hB],
           _RANDOM[5'hC],
           _RANDOM[5'hD],
           _RANDOM[5'hE][5:0]};
        txPending_bits_wmask = _RANDOM[5'hE][21:6];
        io_busReq_prevPending = _RANDOM[5'hE][22];
        io_busReq_prevBits_rowAddr = {_RANDOM[5'hE][31:23], _RANDOM[5'hF][18:0]};
        io_busReq_prevBits_write = _RANDOM[5'hF][19];
        io_busReq_prevBits_wdata =
          {_RANDOM[5'hF][31:20],
           _RANDOM[5'h10],
           _RANDOM[5'h11],
           _RANDOM[5'h12],
           _RANDOM[5'h13][19:0]};
        io_busReq_prevBits_wmask = {_RANDOM[5'h13][31:20], _RANDOM[5'h14][3:0]};
        io_busReq_prevPending_1 = _RANDOM[5'h14][4];
        io_busReq_prevBits_1_rowAddr = {_RANDOM[5'h14][31:5], _RANDOM[5'h15][0]};
        io_busReq_prevBits_1_write = _RANDOM[5'h15][1];
        io_busReq_prevBits_1_wdata =
          {_RANDOM[5'h15][31:2],
           _RANDOM[5'h16],
           _RANDOM[5'h17],
           _RANDOM[5'h18],
           _RANDOM[5'h19][1:0]};
        io_busReq_prevBits_1_wmask = _RANDOM[5'h19][17:2];
        busRespRowAddr = {_RANDOM[5'h19][31:18], _RANDOM[5'h1A][13:0]};
        busRespMask = _RANDOM[5'h1A][17:14];
        faultRespValid = _RANDOM[5'h1A][18];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        state_pc = 32'h0;
        state_write = 1'h0;
        state_faulted = 1'h0;
        state_strictMode = 1'h0;
        state_rd = 5'h0;
        state_skipWriteback = 1'h0;
        state_scalarWritebackMode = 3'h0;
        state_float_writeback = 1'h0;
        state_cells_0_state = 3'h0;
        state_cells_0_data = 8'h0;
        state_cells_0_rowAddr = 28'h0;
        state_cells_0_mask = 16'h0;
        state_cells_1_state = 3'h0;
        state_cells_1_data = 8'h0;
        state_cells_1_rowAddr = 28'h0;
        state_cells_1_mask = 16'h0;
        state_cells_2_state = 3'h0;
        state_cells_2_data = 8'h0;
        state_cells_2_rowAddr = 28'h0;
        state_cells_2_mask = 16'h0;
        state_cells_3_state = 3'h0;
        state_cells_3_data = 8'h0;
        state_cells_3_rowAddr = 28'h0;
        state_cells_3_mask = 16'h0;
        index = 2'h0;
        state_rowAddr = 28'h0;
        txPending_valid = 1'h0;
        txPending_bits_rowAddr = 28'h0;
        txPending_bits_write = 1'h0;
        txPending_bits_wdata = 128'h0;
        txPending_bits_wmask = 16'h0;
        io_busReq_prevPending = 1'h0;
        io_busReq_prevPending_1 = 1'h0;
        busRespRowAddr = 28'h0;
        busRespMask = 4'h0;
        faultRespValid = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_uop_ready = io_uop_ready_0;
  assign io_busReq_valid = io_busReq_out_valid;
  assign io_busReq_bits_rowAddr = io_busReq_out_bits_rowAddr;
  assign io_busReq_bits_write = io_busReq_out_bits_write;
  assign io_busReq_bits_wdata = io_busReq_out_bits_wdata;
  assign io_busReq_bits_wmask = io_busReq_out_bits_wmask;
  assign io_intWriteback_valid = req_y_valid;
  assign io_intWriteback_bits_addr = state_rd;
  assign io_intWriteback_bits_data = state_float_writeback ? 32'h0 : scalarReq_bits;
  assign io_floatWriteback_valid = writebackReq_float_valid;
  assign io_floatWriteback_bits_addr = state_rd;
  assign io_floatWriteback_bits_data = state_float_writeback ? scalarReq_bits : 32'h0;
  assign io_pc = state_pc;
  assign io_active =
    _io_storeComplete_T_1 & _io_storeComplete_T_4 & _io_storeComplete_T_7
    & _io_storeComplete_T_10;
  assign io_storeComplete =
    state_write
    & ~((scalar8Valid | _io_storeComplete_T_1)
        & (_io_storeComplete_T_3 | _io_storeComplete_T_4)
        & (_io_storeComplete_T_6 | _io_storeComplete_T_7)
        & (_io_storeComplete_T_9 | _io_storeComplete_T_10))
    & (stateFromAction_cells_0_state == 3'h4 | _io_storeComplete_T_19)
    & (stateFromAction_cells_1_state == 3'h4 | _io_storeComplete_T_22)
    & (stateFromAction_cells_2_state == 3'h4 | _io_storeComplete_T_25)
    & (stateFromAction_cells_3_state == 3'h4 | _io_storeComplete_T_28);
endmodule

