// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module LsuV3(
  input          clock,
                 reset,
  output         io_req_0_ready,
  input          io_req_0_valid,
                 io_req_0_bits_store,
  input  [4:0]   io_req_0_bits_addr,
                 io_req_0_bits_op,
  input  [31:0]  io_req_0_bits_pc,
  output         io_req_1_ready,
  input          io_req_1_valid,
                 io_req_1_bits_store,
  input  [4:0]   io_req_1_bits_addr,
                 io_req_1_bits_op,
  input  [31:0]  io_req_1_bits_pc,
  output         io_req_2_ready,
  input          io_req_2_valid,
                 io_req_2_bits_store,
  input  [4:0]   io_req_2_bits_addr,
                 io_req_2_bits_op,
  input  [31:0]  io_req_2_bits_pc,
  output         io_req_3_ready,
  input          io_req_3_valid,
                 io_req_3_bits_store,
  input  [4:0]   io_req_3_bits_addr,
                 io_req_3_bits_op,
  input  [31:0]  io_req_3_bits_pc,
                 io_busPort_addr_0,
                 io_busPort_addr_1,
                 io_busPort_addr_2,
                 io_busPort_addr_3,
                 io_busPort_data_0,
                 io_busPort_data_1,
                 io_busPort_data_2,
                 io_busPort_data_3,
                 io_busPort_flt_data_0,
  output         io_rd_valid,
  output [4:0]   io_rd_bits_addr,
  output [31:0]  io_rd_bits_data,
  output         io_rd_flt_valid,
  output [4:0]   io_rd_flt_bits_addr,
  output [31:0]  io_rd_flt_bits_data,
  output         io_ibus_valid,
  input          io_ibus_ready,
  output [31:0]  io_ibus_addr,
  input  [127:0] io_ibus_rdata,
  output         io_dbus_valid,
                 io_dbus_write,
  output [31:0]  io_dbus_addr,
  output [127:0] io_dbus_wdata,
  output [15:0]  io_dbus_wmask,
  input  [127:0] io_dbus_rdata,
  output         io_fault_valid,
                 io_fault_bits_write,
  output [31:0]  io_fault_bits_addr,
                 io_fault_bits_epc,
  output         io_ebus_dbus_valid,
  input          io_ebus_dbus_ready,
  output         io_ebus_dbus_write,
  output [31:0]  io_ebus_dbus_pc,
                 io_ebus_dbus_addr,
  output [4:0]   io_ebus_dbus_size,
  output [127:0] io_ebus_dbus_wdata,
  output [15:0]  io_ebus_dbus_wmask,
  input  [127:0] io_ebus_dbus_rdata,
  input          io_ebus_fault_valid,
                 io_ebus_fault_bits_write,
  input  [31:0]  io_ebus_fault_bits_addr,
                 io_ebus_fault_bits_epc,
  output [2:0]   io_queueCapacity,
  output         io_active,
                 io_storeComplete_valid,
  output [31:0]  io_storeComplete_bits
);

  wire         _slot_io_uop_ready;
  wire         _slot_io_busReq_valid;
  wire [27:0]  _slot_io_busReq_bits_rowAddr;
  wire         _slot_io_busReq_bits_write;
  wire [127:0] _slot_io_busReq_bits_wdata;
  wire [15:0]  _slot_io_busReq_bits_wmask;
  wire [31:0]  _slot_io_pc;
  wire         _slot_io_active;
  wire         _alignedOps_aligner_out_0_valid;
  wire [106:0] _alignedOps_aligner_out_0_bits;
  wire         _alignedOps_aligner_out_1_valid;
  wire [106:0] _alignedOps_aligner_out_1_bits;
  wire         _alignedOps_aligner_out_2_valid;
  wire [106:0] _alignedOps_aligner_out_2_bits;
  wire         _alignedOps_aligner_out_3_valid;
  wire [106:0] _alignedOps_aligner_out_3_bits;
  wire [2:0]   _rs_io_nEnqueued;
  wire [2:0]   _rs_io_nSpace;
  wire         _rs_io_dataOut_0_store;
  wire [4:0]   _rs_io_dataOut_0_rd;
  wire [4:0]   _rs_io_dataOut_0_op;
  wire [31:0]  _rs_io_dataOut_0_pc;
  wire [31:0]  _rs_io_dataOut_0_addr;
  wire [31:0]  _rs_io_dataOut_0_data;
  wire [2:0]   _validSums_T_1 = {2'h0, io_req_0_valid} + {2'h0, io_req_1_valid};
  wire         io_req_1_ready_0 = {2'h0, io_req_0_valid} < _rs_io_nSpace;
  wire         io_req_2_ready_0 = _validSums_T_1 < _rs_io_nSpace;
  wire         io_req_3_ready_0 = _validSums_T_1 + {2'h0, io_req_2_valid} < _rs_io_nSpace;
  wire [31:0]  addr = {_slot_io_busReq_bits_rowAddr, 4'h0};
  wire         itcm = addr < 32'h2000;
  wire         dtcm = (|(_slot_io_busReq_bits_rowAddr[27:12])) & addr < 32'h18000;
  wire         ibusFault_y = _slot_io_busReq_valid & _slot_io_busReq_bits_write & itcm;
  reg          faultReg_valid;
  reg          faultReg_bits_write;
  reg  [31:0]  faultReg_bits_addr;
  reg  [31:0]  faultReg_bits_epc;
  wire         io_ibus_valid_0 =
    itcm & _slot_io_busReq_valid & ~_slot_io_busReq_bits_write;
  reg          ibusResp;
  wire         io_dbus_valid_0 = dtcm & _slot_io_busReq_valid;
  reg          dbusResp;
  wire         _slot_io_busReq_ready_defaultSel_T = itcm | dtcm;
  wire [3:0]   _ebus_offset_T_29 =
    _slot_io_busReq_bits_wmask[1]
      ? 4'h1
      : _slot_io_busReq_bits_wmask[2]
          ? 4'h2
          : _slot_io_busReq_bits_wmask[3]
              ? 4'h3
              : _slot_io_busReq_bits_wmask[4]
                  ? 4'h4
                  : _slot_io_busReq_bits_wmask[5]
                      ? 4'h5
                      : _slot_io_busReq_bits_wmask[6]
                          ? 4'h6
                          : _slot_io_busReq_bits_wmask[7]
                              ? 4'h7
                              : _slot_io_busReq_bits_wmask[8]
                                  ? 4'h8
                                  : _slot_io_busReq_bits_wmask[9]
                                      ? 4'h9
                                      : _slot_io_busReq_bits_wmask[10]
                                          ? 4'hA
                                          : _slot_io_busReq_bits_wmask[11]
                                              ? 4'hB
                                              : _slot_io_busReq_bits_wmask[12]
                                                  ? 4'hC
                                                  : _slot_io_busReq_bits_wmask[13]
                                                      ? 4'hD
                                                      : {3'h7,
                                                         ~(_slot_io_busReq_bits_wmask[14])};
  wire [3:0]   ebus_offset = _slot_io_busReq_bits_wmask[0] ? 4'h0 : _ebus_offset_T_29;
  wire [15:0]  _ebus_last_T_8 =
    {8'h0, _slot_io_busReq_bits_wmask[15:8]} | {_slot_io_busReq_bits_wmask[7:0], 8'h0};
  wire [15:0]  _ebus_last_T_18 =
    {4'h0, _ebus_last_T_8[15:4] & 12'hF0F} | {_ebus_last_T_8[11:0] & 12'hF0F, 4'h0};
  wire [15:0]  _ebus_last_T_28 =
    {2'h0, _ebus_last_T_18[15:2] & 14'h3333} | {_ebus_last_T_18[13:0] & 14'h3333, 2'h0};
  wire [14:0]  _ebus_last_T_38 =
    _ebus_last_T_28[15:1] & 15'h5555 | {1'h0, _ebus_last_T_28[12:0] & 13'h1555, 1'h0};
  wire [4:0]   _ebus_span_T_2 =
    5'h10
    - {1'h0,
       _ebus_last_T_38[0]
         ? 4'h0
         : _ebus_last_T_38[1]
             ? 4'h1
             : _ebus_last_T_38[2]
                 ? 4'h2
                 : _ebus_last_T_38[3]
                     ? 4'h3
                     : _ebus_last_T_38[4]
                         ? 4'h4
                         : _ebus_last_T_38[5]
                             ? 4'h5
                             : _ebus_last_T_38[6]
                                 ? 4'h6
                                 : _ebus_last_T_38[7]
                                     ? 4'h7
                                     : _ebus_last_T_38[8]
                                         ? 4'h8
                                         : _ebus_last_T_38[9]
                                             ? 4'h9
                                             : _ebus_last_T_38[10]
                                                 ? 4'hA
                                                 : _ebus_last_T_38[11]
                                                     ? 4'hB
                                                     : _ebus_last_T_38[12]
                                                         ? 4'hC
                                                         : _ebus_last_T_38[13]
                                                             ? 4'hD
                                                             : {3'h7,
                                                                ~(_ebus_last_T_38[14])}}
    - {1'h0, ebus_offset};
  wire         _ebus_size_T_2 =
    _slot_io_busReq_bits_wmask == 16'h0 | _ebus_span_T_2 > 5'h4;
  wire         _ebus_size_T_6 = _ebus_span_T_2 == 5'h4 & (|(ebus_offset[1:0]));
  wire         _ebus_size_T_10 = _ebus_span_T_2 == 5'h3;
  wire         _ebus_size_T_9 = _ebus_size_T_10 & ebus_offset[1];
  wire         _ebus_size_T_13 = _ebus_size_T_10 & ~(ebus_offset[1]);
  wire         _ebus_size_T_16 = _ebus_span_T_2 == 5'h2 & ebus_offset[0];
  wire [4:0]   _ebus_size_T_35 =
    {_ebus_size_T_2, 4'h0} | {_ebus_size_T_6, 4'h0} | {_ebus_size_T_9, 4'h0};
  wire [4:0]   ebus_size =
    {_ebus_size_T_35[4:3],
     _ebus_size_T_35[2:0] | {_ebus_size_T_13, 2'h0} | {_ebus_size_T_16, 2'h0}}
    | (_ebus_size_T_2 | _ebus_size_T_6 | _ebus_size_T_9 | _ebus_size_T_13
       | _ebus_size_T_16
         ? 5'h0
         : _ebus_span_T_2);
  wire         io_ebus_dbus_valid_0 =
    ~_slot_io_busReq_ready_defaultSel_T & _slot_io_busReq_valid;
  reg          ebusResp;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      faultReg_valid <= 1'h0;
      faultReg_bits_write <= 1'h0;
      faultReg_bits_addr <= 32'h0;
      faultReg_bits_epc <= 32'h0;
      ibusResp <= 1'h0;
      dbusResp <= 1'h0;
      ebusResp <= 1'h0;
    end
    else begin
      faultReg_valid <= io_ebus_fault_valid ? io_ebus_fault_valid : ibusFault_y;
      faultReg_bits_write <= io_ebus_fault_valid ? io_ebus_fault_bits_write : ibusFault_y;
      faultReg_bits_addr <=
        io_ebus_fault_valid
          ? io_ebus_fault_bits_addr
          : ibusFault_y ? {4'h0, _slot_io_busReq_bits_rowAddr} : 32'h0;
      faultReg_bits_epc <=
        io_ebus_fault_valid ? io_ebus_fault_bits_epc : ibusFault_y ? _slot_io_pc : 32'h0;
      ibusResp <= io_ibus_valid_0 & io_ibus_ready | ibusFault_y;
      dbusResp <= io_dbus_valid_0;
      ebusResp <= io_ebus_dbus_valid_0 & io_ebus_dbus_ready;
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:2];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        faultReg_valid = _RANDOM[2'h0][0];
        faultReg_bits_write = _RANDOM[2'h0][1];
        faultReg_bits_addr = {_RANDOM[2'h0][31:2], _RANDOM[2'h1][1:0]};
        faultReg_bits_epc = {_RANDOM[2'h1][31:2], _RANDOM[2'h2][1:0]};
        ibusResp = _RANDOM[2'h2][2];
        dbusResp = _RANDOM[2'h2][3];
        ebusResp = _RANDOM[2'h2][4];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        faultReg_valid = 1'h0;
        faultReg_bits_write = 1'h0;
        faultReg_bits_addr = 32'h0;
        faultReg_bits_epc = 32'h0;
        ibusResp = 1'h0;
        dbusResp = 1'h0;
        ebusResp = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  CircularBufferMulti_1 rs (
    .clock              (clock),
    .reset              (reset),
    .io_enqValid
      ({1'h0,
        {1'h0, _alignedOps_aligner_out_0_valid} + {1'h0, _alignedOps_aligner_out_1_valid}}
       + {1'h0,
          {1'h0, _alignedOps_aligner_out_2_valid}
            + {1'h0, _alignedOps_aligner_out_3_valid}}),
    .io_enqData_0_store (_alignedOps_aligner_out_0_bits[106]),
    .io_enqData_0_rd    (_alignedOps_aligner_out_0_bits[105:101]),
    .io_enqData_0_op    (_alignedOps_aligner_out_0_bits[100:96]),
    .io_enqData_0_pc    (_alignedOps_aligner_out_0_bits[95:64]),
    .io_enqData_0_addr  (_alignedOps_aligner_out_0_bits[63:32]),
    .io_enqData_0_data  (_alignedOps_aligner_out_0_bits[31:0]),
    .io_enqData_1_store (_alignedOps_aligner_out_1_bits[106]),
    .io_enqData_1_rd    (_alignedOps_aligner_out_1_bits[105:101]),
    .io_enqData_1_op    (_alignedOps_aligner_out_1_bits[100:96]),
    .io_enqData_1_pc    (_alignedOps_aligner_out_1_bits[95:64]),
    .io_enqData_1_addr  (_alignedOps_aligner_out_1_bits[63:32]),
    .io_enqData_1_data  (_alignedOps_aligner_out_1_bits[31:0]),
    .io_enqData_2_store (_alignedOps_aligner_out_2_bits[106]),
    .io_enqData_2_rd    (_alignedOps_aligner_out_2_bits[105:101]),
    .io_enqData_2_op    (_alignedOps_aligner_out_2_bits[100:96]),
    .io_enqData_2_pc    (_alignedOps_aligner_out_2_bits[95:64]),
    .io_enqData_2_addr  (_alignedOps_aligner_out_2_bits[63:32]),
    .io_enqData_2_data  (_alignedOps_aligner_out_2_bits[31:0]),
    .io_enqData_3_store (_alignedOps_aligner_out_3_bits[106]),
    .io_enqData_3_rd    (_alignedOps_aligner_out_3_bits[105:101]),
    .io_enqData_3_op    (_alignedOps_aligner_out_3_bits[100:96]),
    .io_enqData_3_pc    (_alignedOps_aligner_out_3_bits[95:64]),
    .io_enqData_3_addr  (_alignedOps_aligner_out_3_bits[63:32]),
    .io_enqData_3_data  (_alignedOps_aligner_out_3_bits[31:0]),
    .io_nEnqueued       (_rs_io_nEnqueued),
    .io_nSpace          (_rs_io_nSpace),
    .io_dataOut_0_store (_rs_io_dataOut_0_store),
    .io_dataOut_0_rd    (_rs_io_dataOut_0_rd),
    .io_dataOut_0_op    (_rs_io_dataOut_0_op),
    .io_dataOut_0_pc    (_rs_io_dataOut_0_pc),
    .io_dataOut_0_addr  (_rs_io_dataOut_0_addr),
    .io_dataOut_0_data  (_rs_io_dataOut_0_data),
    .io_dataOut_1_store (/* unused */),
    .io_dataOut_1_rd    (/* unused */),
    .io_dataOut_1_op    (/* unused */),
    .io_dataOut_1_pc    (/* unused */),
    .io_dataOut_1_addr  (/* unused */),
    .io_dataOut_1_data  (/* unused */),
    .io_dataOut_2_store (/* unused */),
    .io_dataOut_2_rd    (/* unused */),
    .io_dataOut_2_op    (/* unused */),
    .io_dataOut_2_pc    (/* unused */),
    .io_dataOut_2_addr  (/* unused */),
    .io_dataOut_2_data  (/* unused */),
    .io_dataOut_3_store (/* unused */),
    .io_dataOut_3_rd    (/* unused */),
    .io_dataOut_3_op    (/* unused */),
    .io_dataOut_3_pc    (/* unused */),
    .io_dataOut_3_addr  (/* unused */),
    .io_dataOut_3_data  (/* unused */),
    .io_deqReady        ({2'h0, _slot_io_uop_ready & (|_rs_io_nEnqueued)}),
    .io_flush           (1'h0)
  );
  Aligner_107_4 alignedOps_aligner (
    .in_0_valid  ((|_rs_io_nSpace) & io_req_0_valid),
    .in_0_bits
      ({io_req_0_bits_store,
        io_req_0_bits_addr,
        io_req_0_bits_op,
        io_req_0_bits_pc,
        io_busPort_addr_0,
        io_req_0_bits_op == 5'hC ? io_busPort_flt_data_0 : io_busPort_data_0}),
    .in_1_valid  (io_req_1_ready_0 & io_req_1_valid),
    .in_1_bits
      ({io_req_1_bits_store,
        io_req_1_bits_addr,
        io_req_1_bits_op,
        io_req_1_bits_pc,
        io_busPort_addr_1,
        io_req_1_bits_op == 5'hC ? 32'h0 : io_busPort_data_1}),
    .in_2_valid  (io_req_2_ready_0 & io_req_2_valid),
    .in_2_bits
      ({io_req_2_bits_store,
        io_req_2_bits_addr,
        io_req_2_bits_op,
        io_req_2_bits_pc,
        io_busPort_addr_2,
        io_req_2_bits_op == 5'hC ? 32'h0 : io_busPort_data_2}),
    .in_3_valid  (io_req_3_ready_0 & io_req_3_valid),
    .in_3_bits
      ({io_req_3_bits_store,
        io_req_3_bits_addr,
        io_req_3_bits_op,
        io_req_3_bits_pc,
        io_busPort_addr_3,
        io_req_3_bits_op == 5'hC ? 32'h0 : io_busPort_data_3}),
    .out_0_valid (_alignedOps_aligner_out_0_valid),
    .out_0_bits  (_alignedOps_aligner_out_0_bits),
    .out_1_valid (_alignedOps_aligner_out_1_valid),
    .out_1_bits  (_alignedOps_aligner_out_1_bits),
    .out_2_valid (_alignedOps_aligner_out_2_valid),
    .out_2_bits  (_alignedOps_aligner_out_2_bits),
    .out_3_valid (_alignedOps_aligner_out_3_valid),
    .out_3_bits  (_alignedOps_aligner_out_3_bits)
  );
  LsuSuperSlot slot (
    .clock                       (clock),
    .reset                       (reset),
    .io_uop_ready                (_slot_io_uop_ready),
    .io_uop_valid                (|_rs_io_nEnqueued),
    .io_uop_bits_store           (_rs_io_dataOut_0_store),
    .io_uop_bits_rd              (_rs_io_dataOut_0_rd),
    .io_uop_bits_op              (_rs_io_dataOut_0_op),
    .io_uop_bits_pc              (_rs_io_dataOut_0_pc),
    .io_uop_bits_addr            (_rs_io_dataOut_0_addr),
    .io_uop_bits_data            (_rs_io_dataOut_0_data),
    .io_busReq_ready
      (itcm & (io_ibus_ready | ibusFault_y) | dtcm | ~_slot_io_busReq_ready_defaultSel_T
       & io_ebus_dbus_ready),
    .io_busReq_valid             (_slot_io_busReq_valid),
    .io_busReq_bits_rowAddr      (_slot_io_busReq_bits_rowAddr),
    .io_busReq_bits_write        (_slot_io_busReq_bits_write),
    .io_busReq_bits_wdata        (_slot_io_busReq_bits_wdata),
    .io_busReq_bits_wmask        (_slot_io_busReq_bits_wmask),
    .io_busResp_valid            (ibusResp | dbusResp | ebusResp),
    .io_busResp_bits_rdata
      ((ibusResp ? io_ibus_rdata : 128'h0) | (dbusResp ? io_dbus_rdata : 128'h0)
       | (ebusResp ? io_ebus_dbus_rdata : 128'h0)),
    .io_busResp_bits_fault       (faultReg_valid),
    .io_intWriteback_valid       (io_rd_valid),
    .io_intWriteback_bits_addr   (io_rd_bits_addr),
    .io_intWriteback_bits_data   (io_rd_bits_data),
    .io_floatWriteback_valid     (io_rd_flt_valid),
    .io_floatWriteback_bits_addr (io_rd_flt_bits_addr),
    .io_floatWriteback_bits_data (io_rd_flt_bits_data),
    .io_pc                       (_slot_io_pc),
    .io_active                   (_slot_io_active),
    .io_storeComplete            (io_storeComplete_valid)
  );
  assign io_req_0_ready = |_rs_io_nSpace;
  assign io_req_1_ready = io_req_1_ready_0;
  assign io_req_2_ready = io_req_2_ready_0;
  assign io_req_3_ready = io_req_3_ready_0;
  assign io_ibus_valid = io_ibus_valid_0;
  assign io_ibus_addr = addr;
  assign io_dbus_valid = io_dbus_valid_0;
  assign io_dbus_write = _slot_io_busReq_bits_write;
  assign io_dbus_addr = addr;
  assign io_dbus_wdata = _slot_io_busReq_bits_wdata;
  assign io_dbus_wmask = _slot_io_busReq_bits_wmask;
  assign io_fault_valid = faultReg_valid;
  assign io_fault_bits_write = faultReg_bits_write;
  assign io_fault_bits_addr = faultReg_bits_addr;
  assign io_fault_bits_epc = faultReg_bits_epc;
  assign io_ebus_dbus_valid = io_ebus_dbus_valid_0;
  assign io_ebus_dbus_write = _slot_io_busReq_bits_write;
  assign io_ebus_dbus_pc = _slot_io_pc;
  assign io_ebus_dbus_addr =
    {_slot_io_busReq_bits_rowAddr, 4'h0}
    + {28'h0,
       ebus_size == 5'h4
         ? ebus_offset & 4'hC
         : ebus_size == 5'h2
             ? ebus_offset & 4'hE
             : ebus_size != 5'h1 | _slot_io_busReq_bits_wmask[0]
                 ? 4'h0
                 : _ebus_offset_T_29};
  assign io_ebus_dbus_size = ebus_size;
  assign io_ebus_dbus_wdata = _slot_io_busReq_bits_wdata;
  assign io_ebus_dbus_wmask = _slot_io_busReq_bits_wmask;
  assign io_queueCapacity = _rs_io_nSpace;
  assign io_active = (|_rs_io_nEnqueued) | ~_slot_io_active;
  assign io_storeComplete_bits = _slot_io_pc;
endmodule

