// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Queue1_FloatInstruction(
  input         clock,
                reset,
                io_enq_valid,
  input  [2:0]  io_enq_bits_opcode,
  input  [4:0]  io_enq_bits_funct5,
  input  [2:0]  io_enq_bits_src_fmt,
                io_enq_bits_dst_fmt,
  input  [4:0]  io_enq_bits_rs3,
                io_enq_bits_rs2,
                io_enq_bits_rs1,
  input  [2:0]  io_enq_bits_rm,
  input  [31:0] io_enq_bits_inst,
                io_enq_bits_pc,
  input         io_enq_bits_scalar_rd,
                io_enq_bits_scalar_rs1,
                io_enq_bits_float_rs1,
  input  [4:0]  io_enq_bits_rd,
  input         io_enq_bits_uses_rs3,
                io_enq_bits_uses_rs2,
                io_deq_ready,
  output        io_deq_valid,
  output [2:0]  io_deq_bits_opcode,
  output [4:0]  io_deq_bits_funct5,
  output [2:0]  io_deq_bits_src_fmt,
                io_deq_bits_dst_fmt,
  output [4:0]  io_deq_bits_rs3,
                io_deq_bits_rs2,
                io_deq_bits_rs1,
  output [2:0]  io_deq_bits_rm,
  output        io_deq_bits_scalar_rd,
  output [4:0]  io_deq_bits_rd,
  output        io_count
);

  reg  [105:0] ram;
  wire         io_enq_ready;
  reg          full;
  wire         do_enq = io_enq_ready & io_enq_valid;
  assign io_enq_ready = ~full;
  always @(posedge clock or posedge reset) begin
    if (reset)
      full <= 1'h0;
    else if (~(do_enq == (io_deq_ready & full)))
      full <= do_enq;
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (do_enq)
      ram <=
        {io_enq_bits_opcode,
         io_enq_bits_funct5,
         io_enq_bits_src_fmt,
         io_enq_bits_dst_fmt,
         io_enq_bits_rs3,
         io_enq_bits_rs2,
         io_enq_bits_rs1,
         io_enq_bits_rm,
         io_enq_bits_inst,
         io_enq_bits_pc,
         io_enq_bits_scalar_rd,
         io_enq_bits_scalar_rs1,
         io_enq_bits_float_rs1,
         io_enq_bits_rd,
         io_enq_bits_uses_rs3,
         io_enq_bits_uses_rs2};
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:3];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [2:0] i = 3'h0; i < 3'h4; i += 3'h1) begin
          _RANDOM[i[1:0]] = `RANDOM;
        end
        full = _RANDOM[2'h0][0];
        ram = {_RANDOM[2'h0][31:1], _RANDOM[2'h1], _RANDOM[2'h2], _RANDOM[2'h3][10:0]};
      `endif // RANDOMIZE_REG_INIT
      if (reset)
        full = 1'h0;
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_deq_valid = full;
  assign io_deq_bits_opcode = ram[105:103];
  assign io_deq_bits_funct5 = ram[102:98];
  assign io_deq_bits_src_fmt = ram[97:95];
  assign io_deq_bits_dst_fmt = ram[94:92];
  assign io_deq_bits_rs3 = ram[91:87];
  assign io_deq_bits_rs2 = ram[86:82];
  assign io_deq_bits_rs1 = ram[81:77];
  assign io_deq_bits_rm = ram[76:74];
  assign io_deq_bits_scalar_rd = ram[9];
  assign io_deq_bits_rd = ram[6:2];
  assign io_count = full;
endmodule

