// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module RetirementBuffer(
  input         clock,
                reset,
                io_inst_0_ready,
                io_inst_0_valid,
  input  [31:0] io_inst_0_bits_addr,
                io_inst_0_bits_inst,
  input         io_inst_1_ready,
                io_inst_1_valid,
  input  [31:0] io_inst_1_bits_addr,
                io_inst_1_bits_inst,
  input         io_inst_2_ready,
                io_inst_2_valid,
  input  [31:0] io_inst_2_bits_addr,
                io_inst_2_bits_inst,
  input         io_inst_3_ready,
                io_inst_3_valid,
  input  [31:0] io_inst_3_bits_addr,
                io_inst_3_bits_inst,
                io_targets_0,
                io_targets_1,
                io_targets_2,
                io_targets_3,
                io_jalrTargets_0,
                io_jalrTargets_1,
                io_jalrTargets_2,
                io_jalrTargets_3,
  input         io_jump_0,
                io_jump_1,
                io_jump_2,
                io_jump_3,
                io_branch_0,
                io_branch_1,
                io_branch_2,
                io_branch_3,
                io_storeComplete_valid,
  input  [31:0] io_storeComplete_bits,
  input         io_writeAddrScalar_0_valid,
  input  [4:0]  io_writeAddrScalar_0_addr,
  input         io_writeAddrScalar_1_valid,
  input  [4:0]  io_writeAddrScalar_1_addr,
  input         io_writeAddrScalar_2_valid,
  input  [4:0]  io_writeAddrScalar_2_addr,
  input         io_writeAddrScalar_3_valid,
  input  [4:0]  io_writeAddrScalar_3_addr,
  input         io_writeDataScalar_0_valid,
  input  [4:0]  io_writeDataScalar_0_bits_addr,
  input         io_writeDataScalar_1_valid,
  input  [4:0]  io_writeDataScalar_1_bits_addr,
  input         io_writeDataScalar_2_valid,
  input  [4:0]  io_writeDataScalar_2_bits_addr,
  input         io_writeDataScalar_3_valid,
  input  [4:0]  io_writeDataScalar_3_bits_addr,
  input         io_writeDataScalar_4_valid,
  input  [4:0]  io_writeDataScalar_4_bits_addr,
  input         io_writeDataScalar_5_valid,
  input  [4:0]  io_writeDataScalar_5_bits_addr,
  input         io_writeAddrFloat_valid,
  input  [4:0]  io_writeAddrFloat_addr,
  input         io_writeDataFloat_0_valid,
  input  [4:0]  io_writeDataFloat_0_bits_addr,
  input         io_writeDataFloat_1_valid,
  input  [4:0]  io_writeDataFloat_1_bits_addr,
  input         io_fault_valid,
  input  [31:0] io_fault_bits_mepc,
                io_fault_bits_mcause,
  input         io_fault_bits_decode,
  output [4:0]  io_nSpace,
  output [3:0]  io_nRetired,
  output        io_empty,
                io_trapPending
);

  wire [4:0]  _instBuffer_io_nEnqueued;
  wire [31:0] _instBuffer_io_dataOut_0_addr;
  wire [6:0]  _instBuffer_io_dataOut_0_idx;
  wire        _instBuffer_io_dataOut_0_trap;
  wire        _instBuffer_io_dataOut_0_isControlFlow;
  wire        _instBuffer_io_dataOut_0_isBranch;
  wire        _instBuffer_io_dataOut_0_isEcall;
  wire        _instBuffer_io_dataOut_0_isMpause;
  wire [31:0] _instBuffer_io_dataOut_1_addr;
  wire [6:0]  _instBuffer_io_dataOut_1_idx;
  wire        _instBuffer_io_dataOut_1_trap;
  wire        _instBuffer_io_dataOut_1_isControlFlow;
  wire        _instBuffer_io_dataOut_1_isBranch;
  wire        _instBuffer_io_dataOut_1_linkOk;
  wire        _instBuffer_io_dataOut_1_isEcall;
  wire        _instBuffer_io_dataOut_1_isMpause;
  wire [31:0] _instBuffer_io_dataOut_2_addr;
  wire [6:0]  _instBuffer_io_dataOut_2_idx;
  wire        _instBuffer_io_dataOut_2_trap;
  wire        _instBuffer_io_dataOut_2_isControlFlow;
  wire        _instBuffer_io_dataOut_2_isBranch;
  wire        _instBuffer_io_dataOut_2_linkOk;
  wire        _instBuffer_io_dataOut_2_isEcall;
  wire        _instBuffer_io_dataOut_2_isMpause;
  wire [31:0] _instBuffer_io_dataOut_3_addr;
  wire [6:0]  _instBuffer_io_dataOut_3_idx;
  wire        _instBuffer_io_dataOut_3_trap;
  wire        _instBuffer_io_dataOut_3_isControlFlow;
  wire        _instBuffer_io_dataOut_3_isBranch;
  wire        _instBuffer_io_dataOut_3_linkOk;
  wire        _instBuffer_io_dataOut_3_isEcall;
  wire        _instBuffer_io_dataOut_3_isMpause;
  wire [31:0] _instBuffer_io_dataOut_4_addr;
  wire [6:0]  _instBuffer_io_dataOut_4_idx;
  wire        _instBuffer_io_dataOut_4_trap;
  wire        _instBuffer_io_dataOut_4_isControlFlow;
  wire        _instBuffer_io_dataOut_4_isBranch;
  wire        _instBuffer_io_dataOut_4_linkOk;
  wire        _instBuffer_io_dataOut_4_isEcall;
  wire        _instBuffer_io_dataOut_4_isMpause;
  wire [31:0] _instBuffer_io_dataOut_5_addr;
  wire [6:0]  _instBuffer_io_dataOut_5_idx;
  wire        _instBuffer_io_dataOut_5_trap;
  wire        _instBuffer_io_dataOut_5_isControlFlow;
  wire        _instBuffer_io_dataOut_5_isBranch;
  wire        _instBuffer_io_dataOut_5_linkOk;
  wire        _instBuffer_io_dataOut_5_isEcall;
  wire        _instBuffer_io_dataOut_5_isMpause;
  wire [31:0] _instBuffer_io_dataOut_6_addr;
  wire [6:0]  _instBuffer_io_dataOut_6_idx;
  wire        _instBuffer_io_dataOut_6_trap;
  wire        _instBuffer_io_dataOut_6_isControlFlow;
  wire        _instBuffer_io_dataOut_6_isBranch;
  wire        _instBuffer_io_dataOut_6_linkOk;
  wire        _instBuffer_io_dataOut_6_isEcall;
  wire        _instBuffer_io_dataOut_6_isMpause;
  wire [31:0] _instBuffer_io_dataOut_7_addr;
  wire [6:0]  _instBuffer_io_dataOut_7_idx;
  wire        _instBuffer_io_dataOut_7_trap;
  wire        _instBuffer_io_dataOut_7_isControlFlow;
  wire        _instBuffer_io_dataOut_7_isBranch;
  wire        _instBuffer_io_dataOut_7_linkOk;
  wire        _instBuffer_io_dataOut_7_isEcall;
  wire        _instBuffer_io_dataOut_7_isMpause;
  wire [31:0] _instBuffer_io_dataOut_8_addr;
  wire [6:0]  _instBuffer_io_dataOut_8_idx;
  wire        _instBuffer_io_dataOut_8_trap;
  wire        _instBuffer_io_dataOut_8_isControlFlow;
  wire        _instBuffer_io_dataOut_8_isBranch;
  wire        _instBuffer_io_dataOut_8_linkOk;
  wire        _instBuffer_io_dataOut_8_isMpause;
  wire [31:0] _instBuffer_io_dataOut_9_addr;
  wire [6:0]  _instBuffer_io_dataOut_9_idx;
  wire        _instBuffer_io_dataOut_9_trap;
  wire        _instBuffer_io_dataOut_9_isControlFlow;
  wire        _instBuffer_io_dataOut_9_isBranch;
  wire        _instBuffer_io_dataOut_9_linkOk;
  wire        _instBuffer_io_dataOut_9_isMpause;
  wire [31:0] _instBuffer_io_dataOut_10_addr;
  wire [6:0]  _instBuffer_io_dataOut_10_idx;
  wire        _instBuffer_io_dataOut_10_trap;
  wire        _instBuffer_io_dataOut_10_isControlFlow;
  wire        _instBuffer_io_dataOut_10_isBranch;
  wire        _instBuffer_io_dataOut_10_linkOk;
  wire        _instBuffer_io_dataOut_10_isMpause;
  wire [31:0] _instBuffer_io_dataOut_11_addr;
  wire [6:0]  _instBuffer_io_dataOut_11_idx;
  wire        _instBuffer_io_dataOut_11_trap;
  wire        _instBuffer_io_dataOut_11_isControlFlow;
  wire        _instBuffer_io_dataOut_11_isBranch;
  wire        _instBuffer_io_dataOut_11_linkOk;
  wire        _instBuffer_io_dataOut_11_isMpause;
  wire [31:0] _instBuffer_io_dataOut_12_addr;
  wire [6:0]  _instBuffer_io_dataOut_12_idx;
  wire        _instBuffer_io_dataOut_12_trap;
  wire        _instBuffer_io_dataOut_12_isControlFlow;
  wire        _instBuffer_io_dataOut_12_isBranch;
  wire        _instBuffer_io_dataOut_12_linkOk;
  wire        _instBuffer_io_dataOut_12_isMpause;
  wire [31:0] _instBuffer_io_dataOut_13_addr;
  wire [6:0]  _instBuffer_io_dataOut_13_idx;
  wire        _instBuffer_io_dataOut_13_trap;
  wire        _instBuffer_io_dataOut_13_isControlFlow;
  wire        _instBuffer_io_dataOut_13_isBranch;
  wire        _instBuffer_io_dataOut_13_linkOk;
  wire        _instBuffer_io_dataOut_13_isMpause;
  wire [31:0] _instBuffer_io_dataOut_14_addr;
  wire [6:0]  _instBuffer_io_dataOut_14_idx;
  wire        _instBuffer_io_dataOut_14_trap;
  wire        _instBuffer_io_dataOut_14_isControlFlow;
  wire        _instBuffer_io_dataOut_14_isBranch;
  wire        _instBuffer_io_dataOut_14_linkOk;
  wire        _instBuffer_io_dataOut_14_isMpause;
  wire [31:0] _instBuffer_io_dataOut_15_addr;
  wire [6:0]  _instBuffer_io_dataOut_15_idx;
  wire        _instBuffer_io_dataOut_15_trap;
  wire        _instBuffer_io_dataOut_15_isControlFlow;
  wire        _instBuffer_io_dataOut_15_isBranch;
  wire        _instBuffer_io_dataOut_15_linkOk;
  wire        _instBuffer_io_dataOut_15_isMpause;
  reg         storeComplete_pipe_v;
  reg  [31:0] storeComplete_pipe_b;
  wire        instFires_0 = io_inst_0_ready & io_inst_0_valid;
  wire        instFires_1 = io_inst_1_ready & io_inst_1_valid;
  wire        instFires_2 = io_inst_2_ready & io_inst_2_valid;
  wire        instFires_3 = io_inst_3_ready & io_inst_3_valid;
  wire        decodeFaultValid = io_fault_valid & io_fault_bits_decode;
  wire        noFire0Fault =
    io_fault_valid & ~instFires_0 & io_fault_bits_mcause != 32'h7
    & io_fault_bits_mcause != 32'h5;
  reg  [31:0] regLastTarget;
  reg  [31:0] regLastAddr;
  reg         regLastIsBranch;
  wire        _lane0LinkOk_T_75 = io_inst_0_bits_addr == regLastTarget;
  wire [31:0] _faultLinkOk_T_76 = regLastAddr + 32'h4;
  wire [6:0]  _GEN = {2'h0, io_writeAddrScalar_0_addr};
  reg         resultBuffer_0_valid;
  reg         resultBuffer_0_bits_trap;
  reg         resultBuffer_0_bits_cfDone;
  reg         resultBuffer_1_valid;
  reg         resultBuffer_1_bits_trap;
  reg         resultBuffer_1_bits_cfDone;
  reg         resultBuffer_2_valid;
  reg         resultBuffer_2_bits_trap;
  reg         resultBuffer_2_bits_cfDone;
  reg         resultBuffer_3_valid;
  reg         resultBuffer_3_bits_trap;
  reg         resultBuffer_3_bits_cfDone;
  reg         resultBuffer_4_valid;
  reg         resultBuffer_4_bits_trap;
  reg         resultBuffer_4_bits_cfDone;
  reg         resultBuffer_5_valid;
  reg         resultBuffer_5_bits_trap;
  reg         resultBuffer_5_bits_cfDone;
  reg         resultBuffer_6_valid;
  reg         resultBuffer_6_bits_trap;
  reg         resultBuffer_6_bits_cfDone;
  reg         resultBuffer_7_valid;
  reg         resultBuffer_7_bits_trap;
  reg         resultBuffer_7_bits_cfDone;
  reg         resultBuffer_8_valid;
  reg         resultBuffer_8_bits_trap;
  reg         resultBuffer_8_bits_cfDone;
  reg         resultBuffer_9_valid;
  reg         resultBuffer_9_bits_trap;
  reg         resultBuffer_9_bits_cfDone;
  reg         resultBuffer_10_valid;
  reg         resultBuffer_10_bits_trap;
  reg         resultBuffer_10_bits_cfDone;
  reg         resultBuffer_11_valid;
  reg         resultBuffer_11_bits_trap;
  reg         resultBuffer_11_bits_cfDone;
  reg         resultBuffer_12_valid;
  reg         resultBuffer_12_bits_trap;
  reg         resultBuffer_12_bits_cfDone;
  reg         resultBuffer_13_valid;
  reg         resultBuffer_13_bits_trap;
  reg         resultBuffer_13_bits_cfDone;
  reg         resultBuffer_14_valid;
  reg         resultBuffer_14_bits_trap;
  reg         resultBuffer_14_bits_cfDone;
  reg         resultBuffer_15_valid;
  reg         resultBuffer_15_bits_trap;
  reg         resultBuffer_15_bits_cfDone;
  wire [6:0]  _GEN_0 = {2'h0, io_writeDataScalar_0_bits_addr};
  wire [6:0]  _GEN_1 = {2'h0, io_writeDataScalar_1_bits_addr};
  wire [6:0]  _GEN_2 = {2'h0, io_writeDataScalar_2_bits_addr};
  wire [6:0]  _GEN_3 = {2'h0, io_writeDataScalar_3_bits_addr};
  wire [6:0]  _GEN_4 = {2'h0, io_writeDataScalar_4_bits_addr};
  wire [6:0]  _GEN_5 = {2'h0, io_writeDataScalar_5_bits_addr};
  wire [6:0]  _floatWriteIdxMap_T_60 = {2'h0, io_writeDataFloat_0_bits_addr} + 7'h20;
  wire [6:0]  _floatWriteIdxMap_T_62 = {2'h0, io_writeDataFloat_1_bits_addr} + 7'h20;
  wire        nextAddrValid =
    (|(_instBuffer_io_nEnqueued[4:1])) | noFire0Fault | io_inst_0_valid;
  wire        _faultLinkOk_T_75 = io_fault_bits_mepc == regLastTarget;
  wire        newCfDone =
    (|_instBuffer_io_nEnqueued)
    & (~_instBuffer_io_dataOut_0_isControlFlow | nextAddrValid);
  wire        hi =
    resultBuffer_0_bits_trap | io_fault_valid
    & _instBuffer_io_dataOut_0_addr == io_fault_bits_mepc | (|_instBuffer_io_nEnqueued)
    & _instBuffer_io_dataOut_0_trap | _instBuffer_io_dataOut_0_isControlFlow & newCfDone
    & (~(nextAddrValid
         & (((|(_instBuffer_io_nEnqueued[4:1]))
               ? _instBuffer_io_dataOut_1_linkOk
               : noFire0Fault
                   ? _faultLinkOk_T_75 | regLastIsBranch
                     & io_fault_bits_mepc == _faultLinkOk_T_76
                   : ~io_inst_0_valid | _lane0LinkOk_T_75 | regLastIsBranch
                     & io_inst_0_bits_addr == _faultLinkOk_T_76)
            | _instBuffer_io_dataOut_0_isBranch
            & ((|(_instBuffer_io_nEnqueued[4:1]))
                 ? _instBuffer_io_dataOut_1_addr
                 : noFire0Fault
                     ? io_fault_bits_mepc
                     : io_inst_0_valid
                         ? io_inst_0_bits_addr
                         : _instBuffer_io_dataOut_1_addr) == _instBuffer_io_dataOut_0_addr
            + 32'h4)) | noFire0Fault) & ~_instBuffer_io_dataOut_0_isMpause;
  wire        currentDataDone =
    resultBuffer_0_valid | (|_instBuffer_io_nEnqueued) & ~resultBuffer_0_valid
    & (io_writeDataScalar_0_valid & _GEN_0 == _instBuffer_io_dataOut_0_idx
       | io_writeDataScalar_1_valid & _GEN_1 == _instBuffer_io_dataOut_0_idx
       | io_writeDataScalar_2_valid & _GEN_2 == _instBuffer_io_dataOut_0_idx
       | io_writeDataScalar_3_valid & _GEN_3 == _instBuffer_io_dataOut_0_idx
       | io_writeDataScalar_4_valid & _GEN_4 == _instBuffer_io_dataOut_0_idx
       | io_writeDataScalar_5_valid & _GEN_5 == _instBuffer_io_dataOut_0_idx
       | io_writeDataFloat_0_valid
       & _floatWriteIdxMap_T_60 == _instBuffer_io_dataOut_0_idx
       | io_writeDataFloat_1_valid
       & _floatWriteIdxMap_T_62 == _instBuffer_io_dataOut_0_idx
       | (&_instBuffer_io_dataOut_0_idx) | _instBuffer_io_dataOut_0_idx == 7'h7E
       & storeComplete_pipe_v & storeComplete_pipe_b == _instBuffer_io_dataOut_0_addr
       | hi);
  wire        currentCfDone =
    resultBuffer_0_valid & resultBuffer_0_bits_cfDone | newCfDone;
  wire        nextValid_1 = _instBuffer_io_nEnqueued > 5'h2;
  wire        nextAddrValid_1 = nextValid_1 | noFire0Fault | io_inst_0_valid;
  wire        newCfDone_1 =
    (|(_instBuffer_io_nEnqueued[4:1]))
    & (~_instBuffer_io_dataOut_1_isControlFlow | nextAddrValid_1);
  wire        currentTrap_1 =
    resultBuffer_1_bits_trap | io_fault_valid
    & _instBuffer_io_dataOut_1_addr == io_fault_bits_mepc
    | (|(_instBuffer_io_nEnqueued[4:1])) & _instBuffer_io_dataOut_1_trap
    | _instBuffer_io_dataOut_1_isControlFlow & newCfDone_1
    & (~(nextAddrValid_1
         & ((nextValid_1
               ? _instBuffer_io_dataOut_2_linkOk
               : noFire0Fault
                   ? _faultLinkOk_T_75 | regLastIsBranch
                     & io_fault_bits_mepc == _faultLinkOk_T_76
                   : ~io_inst_0_valid | _lane0LinkOk_T_75 | regLastIsBranch
                     & io_inst_0_bits_addr == _faultLinkOk_T_76)
            | _instBuffer_io_dataOut_1_isBranch
            & (nextValid_1
                 ? _instBuffer_io_dataOut_2_addr
                 : noFire0Fault
                     ? io_fault_bits_mepc
                     : io_inst_0_valid
                         ? io_inst_0_bits_addr
                         : _instBuffer_io_dataOut_2_addr) == _instBuffer_io_dataOut_1_addr
            + 32'h4)) | noFire0Fault) & ~_instBuffer_io_dataOut_1_isMpause;
  wire        currentDataDone_1 =
    resultBuffer_1_valid | (|(_instBuffer_io_nEnqueued[4:1])) & ~resultBuffer_1_valid
    & (io_writeDataScalar_0_valid & _GEN_0 == _instBuffer_io_dataOut_1_idx
       | io_writeDataScalar_1_valid & _GEN_1 == _instBuffer_io_dataOut_1_idx
       | io_writeDataScalar_2_valid & _GEN_2 == _instBuffer_io_dataOut_1_idx
       | io_writeDataScalar_3_valid & _GEN_3 == _instBuffer_io_dataOut_1_idx
       | io_writeDataScalar_4_valid & _GEN_4 == _instBuffer_io_dataOut_1_idx
       | io_writeDataScalar_5_valid & _GEN_5 == _instBuffer_io_dataOut_1_idx
       | io_writeDataFloat_0_valid
       & _floatWriteIdxMap_T_60 == _instBuffer_io_dataOut_1_idx
       | io_writeDataFloat_1_valid
       & _floatWriteIdxMap_T_62 == _instBuffer_io_dataOut_1_idx
       | (&_instBuffer_io_dataOut_1_idx) | _instBuffer_io_dataOut_1_idx == 7'h7E
       & storeComplete_pipe_v & storeComplete_pipe_b == _instBuffer_io_dataOut_1_addr
       | currentTrap_1);
  wire        currentCfDone_1 =
    resultBuffer_1_valid & resultBuffer_1_bits_cfDone | newCfDone_1;
  wire        validBufferEntry_2 = _instBuffer_io_nEnqueued > 5'h2;
  wire        nextAddrValid_2 =
    (|(_instBuffer_io_nEnqueued[4:2])) | noFire0Fault | io_inst_0_valid;
  wire        newCfDone_2 =
    validBufferEntry_2 & (~_instBuffer_io_dataOut_2_isControlFlow | nextAddrValid_2);
  wire        currentTrap_2 =
    resultBuffer_2_bits_trap | io_fault_valid
    & _instBuffer_io_dataOut_2_addr == io_fault_bits_mepc | validBufferEntry_2
    & _instBuffer_io_dataOut_2_trap | _instBuffer_io_dataOut_2_isControlFlow & newCfDone_2
    & (~(nextAddrValid_2
         & (((|(_instBuffer_io_nEnqueued[4:2]))
               ? _instBuffer_io_dataOut_3_linkOk
               : noFire0Fault
                   ? _faultLinkOk_T_75 | regLastIsBranch
                     & io_fault_bits_mepc == _faultLinkOk_T_76
                   : ~io_inst_0_valid | _lane0LinkOk_T_75 | regLastIsBranch
                     & io_inst_0_bits_addr == _faultLinkOk_T_76)
            | _instBuffer_io_dataOut_2_isBranch
            & ((|(_instBuffer_io_nEnqueued[4:2]))
                 ? _instBuffer_io_dataOut_3_addr
                 : noFire0Fault
                     ? io_fault_bits_mepc
                     : io_inst_0_valid
                         ? io_inst_0_bits_addr
                         : _instBuffer_io_dataOut_3_addr) == _instBuffer_io_dataOut_2_addr
            + 32'h4)) | noFire0Fault) & ~_instBuffer_io_dataOut_2_isMpause;
  wire        currentDataDone_2 =
    resultBuffer_2_valid | validBufferEntry_2 & ~resultBuffer_2_valid
    & (io_writeDataScalar_0_valid & _GEN_0 == _instBuffer_io_dataOut_2_idx
       | io_writeDataScalar_1_valid & _GEN_1 == _instBuffer_io_dataOut_2_idx
       | io_writeDataScalar_2_valid & _GEN_2 == _instBuffer_io_dataOut_2_idx
       | io_writeDataScalar_3_valid & _GEN_3 == _instBuffer_io_dataOut_2_idx
       | io_writeDataScalar_4_valid & _GEN_4 == _instBuffer_io_dataOut_2_idx
       | io_writeDataScalar_5_valid & _GEN_5 == _instBuffer_io_dataOut_2_idx
       | io_writeDataFloat_0_valid
       & _floatWriteIdxMap_T_60 == _instBuffer_io_dataOut_2_idx
       | io_writeDataFloat_1_valid
       & _floatWriteIdxMap_T_62 == _instBuffer_io_dataOut_2_idx
       | (&_instBuffer_io_dataOut_2_idx) | _instBuffer_io_dataOut_2_idx == 7'h7E
       & storeComplete_pipe_v & storeComplete_pipe_b == _instBuffer_io_dataOut_2_addr
       | currentTrap_2);
  wire        currentCfDone_2 =
    resultBuffer_2_valid & resultBuffer_2_bits_cfDone | newCfDone_2;
  wire        nextValid_3 = _instBuffer_io_nEnqueued > 5'h4;
  wire        nextAddrValid_3 = nextValid_3 | noFire0Fault | io_inst_0_valid;
  wire        newCfDone_3 =
    (|(_instBuffer_io_nEnqueued[4:2]))
    & (~_instBuffer_io_dataOut_3_isControlFlow | nextAddrValid_3);
  wire        currentTrap_3 =
    resultBuffer_3_bits_trap | io_fault_valid
    & _instBuffer_io_dataOut_3_addr == io_fault_bits_mepc
    | (|(_instBuffer_io_nEnqueued[4:2])) & _instBuffer_io_dataOut_3_trap
    | _instBuffer_io_dataOut_3_isControlFlow & newCfDone_3
    & (~(nextAddrValid_3
         & ((nextValid_3
               ? _instBuffer_io_dataOut_4_linkOk
               : noFire0Fault
                   ? _faultLinkOk_T_75 | regLastIsBranch
                     & io_fault_bits_mepc == _faultLinkOk_T_76
                   : ~io_inst_0_valid | _lane0LinkOk_T_75 | regLastIsBranch
                     & io_inst_0_bits_addr == _faultLinkOk_T_76)
            | _instBuffer_io_dataOut_3_isBranch
            & (nextValid_3
                 ? _instBuffer_io_dataOut_4_addr
                 : noFire0Fault
                     ? io_fault_bits_mepc
                     : io_inst_0_valid
                         ? io_inst_0_bits_addr
                         : _instBuffer_io_dataOut_4_addr) == _instBuffer_io_dataOut_3_addr
            + 32'h4)) | noFire0Fault) & ~_instBuffer_io_dataOut_3_isMpause;
  wire        currentDataDone_3 =
    resultBuffer_3_valid | (|(_instBuffer_io_nEnqueued[4:2])) & ~resultBuffer_3_valid
    & (io_writeDataScalar_0_valid & _GEN_0 == _instBuffer_io_dataOut_3_idx
       | io_writeDataScalar_1_valid & _GEN_1 == _instBuffer_io_dataOut_3_idx
       | io_writeDataScalar_2_valid & _GEN_2 == _instBuffer_io_dataOut_3_idx
       | io_writeDataScalar_3_valid & _GEN_3 == _instBuffer_io_dataOut_3_idx
       | io_writeDataScalar_4_valid & _GEN_4 == _instBuffer_io_dataOut_3_idx
       | io_writeDataScalar_5_valid & _GEN_5 == _instBuffer_io_dataOut_3_idx
       | io_writeDataFloat_0_valid
       & _floatWriteIdxMap_T_60 == _instBuffer_io_dataOut_3_idx
       | io_writeDataFloat_1_valid
       & _floatWriteIdxMap_T_62 == _instBuffer_io_dataOut_3_idx
       | (&_instBuffer_io_dataOut_3_idx) | _instBuffer_io_dataOut_3_idx == 7'h7E
       & storeComplete_pipe_v & storeComplete_pipe_b == _instBuffer_io_dataOut_3_addr
       | currentTrap_3);
  wire        currentCfDone_3 =
    resultBuffer_3_valid & resultBuffer_3_bits_cfDone | newCfDone_3;
  wire        validBufferEntry_4 = _instBuffer_io_nEnqueued > 5'h4;
  wire        nextValid_4 = _instBuffer_io_nEnqueued > 5'h5;
  wire        nextAddrValid_4 = nextValid_4 | noFire0Fault | io_inst_0_valid;
  wire        newCfDone_4 =
    validBufferEntry_4 & (~_instBuffer_io_dataOut_4_isControlFlow | nextAddrValid_4);
  wire        currentTrap_4 =
    resultBuffer_4_bits_trap | io_fault_valid
    & _instBuffer_io_dataOut_4_addr == io_fault_bits_mepc | validBufferEntry_4
    & _instBuffer_io_dataOut_4_trap | _instBuffer_io_dataOut_4_isControlFlow & newCfDone_4
    & (~(nextAddrValid_4
         & ((nextValid_4
               ? _instBuffer_io_dataOut_5_linkOk
               : noFire0Fault
                   ? _faultLinkOk_T_75 | regLastIsBranch
                     & io_fault_bits_mepc == _faultLinkOk_T_76
                   : ~io_inst_0_valid | _lane0LinkOk_T_75 | regLastIsBranch
                     & io_inst_0_bits_addr == _faultLinkOk_T_76)
            | _instBuffer_io_dataOut_4_isBranch
            & (nextValid_4
                 ? _instBuffer_io_dataOut_5_addr
                 : noFire0Fault
                     ? io_fault_bits_mepc
                     : io_inst_0_valid
                         ? io_inst_0_bits_addr
                         : _instBuffer_io_dataOut_5_addr) == _instBuffer_io_dataOut_4_addr
            + 32'h4)) | noFire0Fault) & ~_instBuffer_io_dataOut_4_isMpause;
  wire        currentDataDone_4 =
    resultBuffer_4_valid | validBufferEntry_4 & ~resultBuffer_4_valid
    & (io_writeDataScalar_0_valid & _GEN_0 == _instBuffer_io_dataOut_4_idx
       | io_writeDataScalar_1_valid & _GEN_1 == _instBuffer_io_dataOut_4_idx
       | io_writeDataScalar_2_valid & _GEN_2 == _instBuffer_io_dataOut_4_idx
       | io_writeDataScalar_3_valid & _GEN_3 == _instBuffer_io_dataOut_4_idx
       | io_writeDataScalar_4_valid & _GEN_4 == _instBuffer_io_dataOut_4_idx
       | io_writeDataScalar_5_valid & _GEN_5 == _instBuffer_io_dataOut_4_idx
       | io_writeDataFloat_0_valid
       & _floatWriteIdxMap_T_60 == _instBuffer_io_dataOut_4_idx
       | io_writeDataFloat_1_valid
       & _floatWriteIdxMap_T_62 == _instBuffer_io_dataOut_4_idx
       | (&_instBuffer_io_dataOut_4_idx) | _instBuffer_io_dataOut_4_idx == 7'h7E
       & storeComplete_pipe_v & storeComplete_pipe_b == _instBuffer_io_dataOut_4_addr
       | currentTrap_4);
  wire        currentCfDone_4 =
    resultBuffer_4_valid & resultBuffer_4_bits_cfDone | newCfDone_4;
  wire        validBufferEntry_5 = _instBuffer_io_nEnqueued > 5'h5;
  wire        nextValid_5 = _instBuffer_io_nEnqueued > 5'h6;
  wire        nextAddrValid_5 = nextValid_5 | noFire0Fault | io_inst_0_valid;
  wire        newCfDone_5 =
    validBufferEntry_5 & (~_instBuffer_io_dataOut_5_isControlFlow | nextAddrValid_5);
  wire        currentTrap_5 =
    resultBuffer_5_bits_trap | io_fault_valid
    & _instBuffer_io_dataOut_5_addr == io_fault_bits_mepc | validBufferEntry_5
    & _instBuffer_io_dataOut_5_trap | _instBuffer_io_dataOut_5_isControlFlow & newCfDone_5
    & (~(nextAddrValid_5
         & ((nextValid_5
               ? _instBuffer_io_dataOut_6_linkOk
               : noFire0Fault
                   ? _faultLinkOk_T_75 | regLastIsBranch
                     & io_fault_bits_mepc == _faultLinkOk_T_76
                   : ~io_inst_0_valid | _lane0LinkOk_T_75 | regLastIsBranch
                     & io_inst_0_bits_addr == _faultLinkOk_T_76)
            | _instBuffer_io_dataOut_5_isBranch
            & (nextValid_5
                 ? _instBuffer_io_dataOut_6_addr
                 : noFire0Fault
                     ? io_fault_bits_mepc
                     : io_inst_0_valid
                         ? io_inst_0_bits_addr
                         : _instBuffer_io_dataOut_6_addr) == _instBuffer_io_dataOut_5_addr
            + 32'h4)) | noFire0Fault) & ~_instBuffer_io_dataOut_5_isMpause;
  wire        currentDataDone_5 =
    resultBuffer_5_valid | validBufferEntry_5 & ~resultBuffer_5_valid
    & (io_writeDataScalar_0_valid & _GEN_0 == _instBuffer_io_dataOut_5_idx
       | io_writeDataScalar_1_valid & _GEN_1 == _instBuffer_io_dataOut_5_idx
       | io_writeDataScalar_2_valid & _GEN_2 == _instBuffer_io_dataOut_5_idx
       | io_writeDataScalar_3_valid & _GEN_3 == _instBuffer_io_dataOut_5_idx
       | io_writeDataScalar_4_valid & _GEN_4 == _instBuffer_io_dataOut_5_idx
       | io_writeDataScalar_5_valid & _GEN_5 == _instBuffer_io_dataOut_5_idx
       | io_writeDataFloat_0_valid
       & _floatWriteIdxMap_T_60 == _instBuffer_io_dataOut_5_idx
       | io_writeDataFloat_1_valid
       & _floatWriteIdxMap_T_62 == _instBuffer_io_dataOut_5_idx
       | (&_instBuffer_io_dataOut_5_idx) | _instBuffer_io_dataOut_5_idx == 7'h7E
       & storeComplete_pipe_v & storeComplete_pipe_b == _instBuffer_io_dataOut_5_addr
       | currentTrap_5);
  wire        currentCfDone_5 =
    resultBuffer_5_valid & resultBuffer_5_bits_cfDone | newCfDone_5;
  wire        validBufferEntry_6 = _instBuffer_io_nEnqueued > 5'h6;
  wire        nextAddrValid_6 =
    (|(_instBuffer_io_nEnqueued[4:3])) | noFire0Fault | io_inst_0_valid;
  wire        newCfDone_6 =
    validBufferEntry_6 & (~_instBuffer_io_dataOut_6_isControlFlow | nextAddrValid_6);
  wire        currentTrap_6 =
    resultBuffer_6_bits_trap | io_fault_valid
    & _instBuffer_io_dataOut_6_addr == io_fault_bits_mepc | validBufferEntry_6
    & _instBuffer_io_dataOut_6_trap | _instBuffer_io_dataOut_6_isControlFlow & newCfDone_6
    & (~(nextAddrValid_6
         & (((|(_instBuffer_io_nEnqueued[4:3]))
               ? _instBuffer_io_dataOut_7_linkOk
               : noFire0Fault
                   ? _faultLinkOk_T_75 | regLastIsBranch
                     & io_fault_bits_mepc == _faultLinkOk_T_76
                   : ~io_inst_0_valid | _lane0LinkOk_T_75 | regLastIsBranch
                     & io_inst_0_bits_addr == _faultLinkOk_T_76)
            | _instBuffer_io_dataOut_6_isBranch
            & ((|(_instBuffer_io_nEnqueued[4:3]))
                 ? _instBuffer_io_dataOut_7_addr
                 : noFire0Fault
                     ? io_fault_bits_mepc
                     : io_inst_0_valid
                         ? io_inst_0_bits_addr
                         : _instBuffer_io_dataOut_7_addr) == _instBuffer_io_dataOut_6_addr
            + 32'h4)) | noFire0Fault) & ~_instBuffer_io_dataOut_6_isMpause;
  wire        currentDataDone_6 =
    resultBuffer_6_valid | validBufferEntry_6 & ~resultBuffer_6_valid
    & (io_writeDataScalar_0_valid & _GEN_0 == _instBuffer_io_dataOut_6_idx
       | io_writeDataScalar_1_valid & _GEN_1 == _instBuffer_io_dataOut_6_idx
       | io_writeDataScalar_2_valid & _GEN_2 == _instBuffer_io_dataOut_6_idx
       | io_writeDataScalar_3_valid & _GEN_3 == _instBuffer_io_dataOut_6_idx
       | io_writeDataScalar_4_valid & _GEN_4 == _instBuffer_io_dataOut_6_idx
       | io_writeDataScalar_5_valid & _GEN_5 == _instBuffer_io_dataOut_6_idx
       | io_writeDataFloat_0_valid
       & _floatWriteIdxMap_T_60 == _instBuffer_io_dataOut_6_idx
       | io_writeDataFloat_1_valid
       & _floatWriteIdxMap_T_62 == _instBuffer_io_dataOut_6_idx
       | (&_instBuffer_io_dataOut_6_idx) | _instBuffer_io_dataOut_6_idx == 7'h7E
       & storeComplete_pipe_v & storeComplete_pipe_b == _instBuffer_io_dataOut_6_addr
       | currentTrap_6);
  wire        currentCfDone_6 =
    resultBuffer_6_valid & resultBuffer_6_bits_cfDone | newCfDone_6;
  wire        nextValid_7 = _instBuffer_io_nEnqueued > 5'h8;
  wire        nextAddrValid_7 = nextValid_7 | noFire0Fault | io_inst_0_valid;
  wire        newCfDone_7 =
    (|(_instBuffer_io_nEnqueued[4:3]))
    & (~_instBuffer_io_dataOut_7_isControlFlow | nextAddrValid_7);
  wire        currentTrap_7 =
    resultBuffer_7_bits_trap | io_fault_valid
    & _instBuffer_io_dataOut_7_addr == io_fault_bits_mepc
    | (|(_instBuffer_io_nEnqueued[4:3])) & _instBuffer_io_dataOut_7_trap
    | _instBuffer_io_dataOut_7_isControlFlow & newCfDone_7
    & (~(nextAddrValid_7
         & ((nextValid_7
               ? _instBuffer_io_dataOut_8_linkOk
               : noFire0Fault
                   ? _faultLinkOk_T_75 | regLastIsBranch
                     & io_fault_bits_mepc == _faultLinkOk_T_76
                   : ~io_inst_0_valid | _lane0LinkOk_T_75 | regLastIsBranch
                     & io_inst_0_bits_addr == _faultLinkOk_T_76)
            | _instBuffer_io_dataOut_7_isBranch
            & (nextValid_7
                 ? _instBuffer_io_dataOut_8_addr
                 : noFire0Fault
                     ? io_fault_bits_mepc
                     : io_inst_0_valid
                         ? io_inst_0_bits_addr
                         : _instBuffer_io_dataOut_8_addr) == _instBuffer_io_dataOut_7_addr
            + 32'h4)) | noFire0Fault) & ~_instBuffer_io_dataOut_7_isMpause;
  wire        currentDataDone_7 =
    resultBuffer_7_valid | (|(_instBuffer_io_nEnqueued[4:3])) & ~resultBuffer_7_valid
    & (io_writeDataScalar_0_valid & _GEN_0 == _instBuffer_io_dataOut_7_idx
       | io_writeDataScalar_1_valid & _GEN_1 == _instBuffer_io_dataOut_7_idx
       | io_writeDataScalar_2_valid & _GEN_2 == _instBuffer_io_dataOut_7_idx
       | io_writeDataScalar_3_valid & _GEN_3 == _instBuffer_io_dataOut_7_idx
       | io_writeDataScalar_4_valid & _GEN_4 == _instBuffer_io_dataOut_7_idx
       | io_writeDataScalar_5_valid & _GEN_5 == _instBuffer_io_dataOut_7_idx
       | io_writeDataFloat_0_valid
       & _floatWriteIdxMap_T_60 == _instBuffer_io_dataOut_7_idx
       | io_writeDataFloat_1_valid
       & _floatWriteIdxMap_T_62 == _instBuffer_io_dataOut_7_idx
       | (&_instBuffer_io_dataOut_7_idx) | _instBuffer_io_dataOut_7_idx == 7'h7E
       & storeComplete_pipe_v & storeComplete_pipe_b == _instBuffer_io_dataOut_7_addr
       | currentTrap_7);
  wire        currentCfDone_7 =
    resultBuffer_7_valid & resultBuffer_7_bits_cfDone | newCfDone_7;
  wire [3:0]  deqReady =
    currentDataDone & currentCfDone
      ? (~currentDataDone_1 | ~currentCfDone_1 | hi
           ? 4'h1
           : ~currentDataDone_2 | ~currentCfDone_2 | currentTrap_1
               ? 4'h2
               : ~currentDataDone_3 | ~currentCfDone_3 | currentTrap_2
                   ? 4'h3
                   : ~currentDataDone_4 | ~currentCfDone_4 | currentTrap_3
                       ? 4'h4
                       : ~currentDataDone_5 | ~currentCfDone_5 | currentTrap_4
                           ? 4'h5
                           : ~currentDataDone_6 | ~currentCfDone_6 | currentTrap_5
                               ? 4'h6
                               : ~currentDataDone_7 | ~currentCfDone_7 | currentTrap_6
                                   ? 4'h7
                                   : 4'h8)
      : 4'h0;
  wire        trapRetired_laneReady_0 = currentDataDone & currentCfDone;
  wire        trapRetired_laneCanTrap_1 =
    trapRetired_laneReady_0 & currentDataDone_1 & currentCfDone_1;
  wire        trapRetired_laneCanTrap_2 =
    trapRetired_laneCanTrap_1 & currentDataDone_2 & currentCfDone_2;
  wire        trapRetired_laneCanTrap_3 =
    trapRetired_laneCanTrap_2 & currentDataDone_3 & currentCfDone_3;
  wire        trapRetired_laneCanTrap_4 =
    trapRetired_laneCanTrap_3 & currentDataDone_4 & currentCfDone_4;
  wire        trapRetired_laneCanTrap_5 =
    trapRetired_laneCanTrap_4 & currentDataDone_5 & currentCfDone_5;
  wire        trapRetired_laneCanTrap_6 =
    trapRetired_laneCanTrap_5 & currentDataDone_6 & currentCfDone_6;
  wire        trapRetired =
    trapRetired_laneReady_0 & hi | trapRetired_laneCanTrap_1 & currentTrap_1
    | trapRetired_laneCanTrap_2 & currentTrap_2 | trapRetired_laneCanTrap_3
    & currentTrap_3 | trapRetired_laneCanTrap_4 & currentTrap_4
    | trapRetired_laneCanTrap_5 & currentTrap_5 | trapRetired_laneCanTrap_6
    & currentTrap_6 | trapRetired_laneCanTrap_6 & currentDataDone_7 & currentCfDone_7
    & currentTrap_7;
  reg  [3:0]  deqReady_reg;
  reg  [3:0]  retiredEcalls_reg;
  reg         io_trapPending_REG;
  wire        validBufferEntry_8 = _instBuffer_io_nEnqueued > 5'h8;
  wire        nextValid_8 = _instBuffer_io_nEnqueued > 5'h9;
  wire        nextAddrValid_8 = nextValid_8 | noFire0Fault | io_inst_0_valid;
  wire        newCfDone_8 =
    validBufferEntry_8 & (~_instBuffer_io_dataOut_8_isControlFlow | nextAddrValid_8);
  wire        currentTrap_8 =
    resultBuffer_8_bits_trap | io_fault_valid
    & _instBuffer_io_dataOut_8_addr == io_fault_bits_mepc | validBufferEntry_8
    & _instBuffer_io_dataOut_8_trap | _instBuffer_io_dataOut_8_isControlFlow & newCfDone_8
    & (~(nextAddrValid_8
         & ((nextValid_8
               ? _instBuffer_io_dataOut_9_linkOk
               : noFire0Fault
                   ? _faultLinkOk_T_75 | regLastIsBranch
                     & io_fault_bits_mepc == _faultLinkOk_T_76
                   : ~io_inst_0_valid | _lane0LinkOk_T_75 | regLastIsBranch
                     & io_inst_0_bits_addr == _faultLinkOk_T_76)
            | _instBuffer_io_dataOut_8_isBranch
            & (nextValid_8
                 ? _instBuffer_io_dataOut_9_addr
                 : noFire0Fault
                     ? io_fault_bits_mepc
                     : io_inst_0_valid
                         ? io_inst_0_bits_addr
                         : _instBuffer_io_dataOut_9_addr) == _instBuffer_io_dataOut_8_addr
            + 32'h4)) | noFire0Fault) & ~_instBuffer_io_dataOut_8_isMpause;
  wire        currentDataDone_8 =
    resultBuffer_8_valid | validBufferEntry_8 & ~resultBuffer_8_valid
    & (io_writeDataScalar_0_valid & _GEN_0 == _instBuffer_io_dataOut_8_idx
       | io_writeDataScalar_1_valid & _GEN_1 == _instBuffer_io_dataOut_8_idx
       | io_writeDataScalar_2_valid & _GEN_2 == _instBuffer_io_dataOut_8_idx
       | io_writeDataScalar_3_valid & _GEN_3 == _instBuffer_io_dataOut_8_idx
       | io_writeDataScalar_4_valid & _GEN_4 == _instBuffer_io_dataOut_8_idx
       | io_writeDataScalar_5_valid & _GEN_5 == _instBuffer_io_dataOut_8_idx
       | io_writeDataFloat_0_valid
       & _floatWriteIdxMap_T_60 == _instBuffer_io_dataOut_8_idx
       | io_writeDataFloat_1_valid
       & _floatWriteIdxMap_T_62 == _instBuffer_io_dataOut_8_idx
       | (&_instBuffer_io_dataOut_8_idx) | _instBuffer_io_dataOut_8_idx == 7'h7E
       & storeComplete_pipe_v & storeComplete_pipe_b == _instBuffer_io_dataOut_8_addr
       | currentTrap_8);
  wire        validBufferEntry_9 = _instBuffer_io_nEnqueued > 5'h9;
  wire        nextValid_9 = _instBuffer_io_nEnqueued > 5'hA;
  wire        nextAddrValid_9 = nextValid_9 | noFire0Fault | io_inst_0_valid;
  wire        newCfDone_9 =
    validBufferEntry_9 & (~_instBuffer_io_dataOut_9_isControlFlow | nextAddrValid_9);
  wire        currentTrap_9 =
    resultBuffer_9_bits_trap | io_fault_valid
    & _instBuffer_io_dataOut_9_addr == io_fault_bits_mepc | validBufferEntry_9
    & _instBuffer_io_dataOut_9_trap | _instBuffer_io_dataOut_9_isControlFlow & newCfDone_9
    & (~(nextAddrValid_9
         & ((nextValid_9
               ? _instBuffer_io_dataOut_10_linkOk
               : noFire0Fault
                   ? _faultLinkOk_T_75 | regLastIsBranch
                     & io_fault_bits_mepc == _faultLinkOk_T_76
                   : ~io_inst_0_valid | _lane0LinkOk_T_75 | regLastIsBranch
                     & io_inst_0_bits_addr == _faultLinkOk_T_76)
            | _instBuffer_io_dataOut_9_isBranch
            & (nextValid_9
                 ? _instBuffer_io_dataOut_10_addr
                 : noFire0Fault
                     ? io_fault_bits_mepc
                     : io_inst_0_valid
                         ? io_inst_0_bits_addr
                         : _instBuffer_io_dataOut_10_addr) == _instBuffer_io_dataOut_9_addr
            + 32'h4)) | noFire0Fault) & ~_instBuffer_io_dataOut_9_isMpause;
  wire        currentDataDone_9 =
    resultBuffer_9_valid | validBufferEntry_9 & ~resultBuffer_9_valid
    & (io_writeDataScalar_0_valid & _GEN_0 == _instBuffer_io_dataOut_9_idx
       | io_writeDataScalar_1_valid & _GEN_1 == _instBuffer_io_dataOut_9_idx
       | io_writeDataScalar_2_valid & _GEN_2 == _instBuffer_io_dataOut_9_idx
       | io_writeDataScalar_3_valid & _GEN_3 == _instBuffer_io_dataOut_9_idx
       | io_writeDataScalar_4_valid & _GEN_4 == _instBuffer_io_dataOut_9_idx
       | io_writeDataScalar_5_valid & _GEN_5 == _instBuffer_io_dataOut_9_idx
       | io_writeDataFloat_0_valid
       & _floatWriteIdxMap_T_60 == _instBuffer_io_dataOut_9_idx
       | io_writeDataFloat_1_valid
       & _floatWriteIdxMap_T_62 == _instBuffer_io_dataOut_9_idx
       | (&_instBuffer_io_dataOut_9_idx) | _instBuffer_io_dataOut_9_idx == 7'h7E
       & storeComplete_pipe_v & storeComplete_pipe_b == _instBuffer_io_dataOut_9_addr
       | currentTrap_9);
  wire        validBufferEntry_10 = _instBuffer_io_nEnqueued > 5'hA;
  wire        nextValid_10 = _instBuffer_io_nEnqueued > 5'hB;
  wire        nextAddrValid_10 = nextValid_10 | noFire0Fault | io_inst_0_valid;
  wire        newCfDone_10 =
    validBufferEntry_10 & (~_instBuffer_io_dataOut_10_isControlFlow | nextAddrValid_10);
  wire        currentTrap_10 =
    resultBuffer_10_bits_trap | io_fault_valid
    & _instBuffer_io_dataOut_10_addr == io_fault_bits_mepc | validBufferEntry_10
    & _instBuffer_io_dataOut_10_trap | _instBuffer_io_dataOut_10_isControlFlow
    & newCfDone_10
    & (~(nextAddrValid_10
         & ((nextValid_10
               ? _instBuffer_io_dataOut_11_linkOk
               : noFire0Fault
                   ? _faultLinkOk_T_75 | regLastIsBranch
                     & io_fault_bits_mepc == _faultLinkOk_T_76
                   : ~io_inst_0_valid | _lane0LinkOk_T_75 | regLastIsBranch
                     & io_inst_0_bits_addr == _faultLinkOk_T_76)
            | _instBuffer_io_dataOut_10_isBranch
            & (nextValid_10
                 ? _instBuffer_io_dataOut_11_addr
                 : noFire0Fault
                     ? io_fault_bits_mepc
                     : io_inst_0_valid
                         ? io_inst_0_bits_addr
                         : _instBuffer_io_dataOut_11_addr) == _instBuffer_io_dataOut_10_addr
            + 32'h4)) | noFire0Fault) & ~_instBuffer_io_dataOut_10_isMpause;
  wire        currentDataDone_10 =
    resultBuffer_10_valid | validBufferEntry_10 & ~resultBuffer_10_valid
    & (io_writeDataScalar_0_valid & _GEN_0 == _instBuffer_io_dataOut_10_idx
       | io_writeDataScalar_1_valid & _GEN_1 == _instBuffer_io_dataOut_10_idx
       | io_writeDataScalar_2_valid & _GEN_2 == _instBuffer_io_dataOut_10_idx
       | io_writeDataScalar_3_valid & _GEN_3 == _instBuffer_io_dataOut_10_idx
       | io_writeDataScalar_4_valid & _GEN_4 == _instBuffer_io_dataOut_10_idx
       | io_writeDataScalar_5_valid & _GEN_5 == _instBuffer_io_dataOut_10_idx
       | io_writeDataFloat_0_valid
       & _floatWriteIdxMap_T_60 == _instBuffer_io_dataOut_10_idx
       | io_writeDataFloat_1_valid
       & _floatWriteIdxMap_T_62 == _instBuffer_io_dataOut_10_idx
       | (&_instBuffer_io_dataOut_10_idx) | _instBuffer_io_dataOut_10_idx == 7'h7E
       & storeComplete_pipe_v & storeComplete_pipe_b == _instBuffer_io_dataOut_10_addr
       | currentTrap_10);
  wire        validBufferEntry_11 = _instBuffer_io_nEnqueued > 5'hB;
  wire        nextValid_11 = _instBuffer_io_nEnqueued > 5'hC;
  wire        nextAddrValid_11 = nextValid_11 | noFire0Fault | io_inst_0_valid;
  wire        newCfDone_11 =
    validBufferEntry_11 & (~_instBuffer_io_dataOut_11_isControlFlow | nextAddrValid_11);
  wire        currentTrap_11 =
    resultBuffer_11_bits_trap | io_fault_valid
    & _instBuffer_io_dataOut_11_addr == io_fault_bits_mepc | validBufferEntry_11
    & _instBuffer_io_dataOut_11_trap | _instBuffer_io_dataOut_11_isControlFlow
    & newCfDone_11
    & (~(nextAddrValid_11
         & ((nextValid_11
               ? _instBuffer_io_dataOut_12_linkOk
               : noFire0Fault
                   ? _faultLinkOk_T_75 | regLastIsBranch
                     & io_fault_bits_mepc == _faultLinkOk_T_76
                   : ~io_inst_0_valid | _lane0LinkOk_T_75 | regLastIsBranch
                     & io_inst_0_bits_addr == _faultLinkOk_T_76)
            | _instBuffer_io_dataOut_11_isBranch
            & (nextValid_11
                 ? _instBuffer_io_dataOut_12_addr
                 : noFire0Fault
                     ? io_fault_bits_mepc
                     : io_inst_0_valid
                         ? io_inst_0_bits_addr
                         : _instBuffer_io_dataOut_12_addr) == _instBuffer_io_dataOut_11_addr
            + 32'h4)) | noFire0Fault) & ~_instBuffer_io_dataOut_11_isMpause;
  wire        currentDataDone_11 =
    resultBuffer_11_valid | validBufferEntry_11 & ~resultBuffer_11_valid
    & (io_writeDataScalar_0_valid & _GEN_0 == _instBuffer_io_dataOut_11_idx
       | io_writeDataScalar_1_valid & _GEN_1 == _instBuffer_io_dataOut_11_idx
       | io_writeDataScalar_2_valid & _GEN_2 == _instBuffer_io_dataOut_11_idx
       | io_writeDataScalar_3_valid & _GEN_3 == _instBuffer_io_dataOut_11_idx
       | io_writeDataScalar_4_valid & _GEN_4 == _instBuffer_io_dataOut_11_idx
       | io_writeDataScalar_5_valid & _GEN_5 == _instBuffer_io_dataOut_11_idx
       | io_writeDataFloat_0_valid
       & _floatWriteIdxMap_T_60 == _instBuffer_io_dataOut_11_idx
       | io_writeDataFloat_1_valid
       & _floatWriteIdxMap_T_62 == _instBuffer_io_dataOut_11_idx
       | (&_instBuffer_io_dataOut_11_idx) | _instBuffer_io_dataOut_11_idx == 7'h7E
       & storeComplete_pipe_v & storeComplete_pipe_b == _instBuffer_io_dataOut_11_addr
       | currentTrap_11);
  wire        validBufferEntry_12 = _instBuffer_io_nEnqueued > 5'hC;
  wire        nextValid_12 = _instBuffer_io_nEnqueued > 5'hD;
  wire        nextAddrValid_12 = nextValid_12 | noFire0Fault | io_inst_0_valid;
  wire        newCfDone_12 =
    validBufferEntry_12 & (~_instBuffer_io_dataOut_12_isControlFlow | nextAddrValid_12);
  wire        currentTrap_12 =
    resultBuffer_12_bits_trap | io_fault_valid
    & _instBuffer_io_dataOut_12_addr == io_fault_bits_mepc | validBufferEntry_12
    & _instBuffer_io_dataOut_12_trap | _instBuffer_io_dataOut_12_isControlFlow
    & newCfDone_12
    & (~(nextAddrValid_12
         & ((nextValid_12
               ? _instBuffer_io_dataOut_13_linkOk
               : noFire0Fault
                   ? _faultLinkOk_T_75 | regLastIsBranch
                     & io_fault_bits_mepc == _faultLinkOk_T_76
                   : ~io_inst_0_valid | _lane0LinkOk_T_75 | regLastIsBranch
                     & io_inst_0_bits_addr == _faultLinkOk_T_76)
            | _instBuffer_io_dataOut_12_isBranch
            & (nextValid_12
                 ? _instBuffer_io_dataOut_13_addr
                 : noFire0Fault
                     ? io_fault_bits_mepc
                     : io_inst_0_valid
                         ? io_inst_0_bits_addr
                         : _instBuffer_io_dataOut_13_addr) == _instBuffer_io_dataOut_12_addr
            + 32'h4)) | noFire0Fault) & ~_instBuffer_io_dataOut_12_isMpause;
  wire        currentDataDone_12 =
    resultBuffer_12_valid | validBufferEntry_12 & ~resultBuffer_12_valid
    & (io_writeDataScalar_0_valid & _GEN_0 == _instBuffer_io_dataOut_12_idx
       | io_writeDataScalar_1_valid & _GEN_1 == _instBuffer_io_dataOut_12_idx
       | io_writeDataScalar_2_valid & _GEN_2 == _instBuffer_io_dataOut_12_idx
       | io_writeDataScalar_3_valid & _GEN_3 == _instBuffer_io_dataOut_12_idx
       | io_writeDataScalar_4_valid & _GEN_4 == _instBuffer_io_dataOut_12_idx
       | io_writeDataScalar_5_valid & _GEN_5 == _instBuffer_io_dataOut_12_idx
       | io_writeDataFloat_0_valid
       & _floatWriteIdxMap_T_60 == _instBuffer_io_dataOut_12_idx
       | io_writeDataFloat_1_valid
       & _floatWriteIdxMap_T_62 == _instBuffer_io_dataOut_12_idx
       | (&_instBuffer_io_dataOut_12_idx) | _instBuffer_io_dataOut_12_idx == 7'h7E
       & storeComplete_pipe_v & storeComplete_pipe_b == _instBuffer_io_dataOut_12_addr
       | currentTrap_12);
  wire        validBufferEntry_13 = _instBuffer_io_nEnqueued > 5'hD;
  wire        nextValid_13 = _instBuffer_io_nEnqueued > 5'hE;
  wire        nextAddrValid_13 = nextValid_13 | noFire0Fault | io_inst_0_valid;
  wire        newCfDone_13 =
    validBufferEntry_13 & (~_instBuffer_io_dataOut_13_isControlFlow | nextAddrValid_13);
  wire        currentTrap_13 =
    resultBuffer_13_bits_trap | io_fault_valid
    & _instBuffer_io_dataOut_13_addr == io_fault_bits_mepc | validBufferEntry_13
    & _instBuffer_io_dataOut_13_trap | _instBuffer_io_dataOut_13_isControlFlow
    & newCfDone_13
    & (~(nextAddrValid_13
         & ((nextValid_13
               ? _instBuffer_io_dataOut_14_linkOk
               : noFire0Fault
                   ? _faultLinkOk_T_75 | regLastIsBranch
                     & io_fault_bits_mepc == _faultLinkOk_T_76
                   : ~io_inst_0_valid | _lane0LinkOk_T_75 | regLastIsBranch
                     & io_inst_0_bits_addr == _faultLinkOk_T_76)
            | _instBuffer_io_dataOut_13_isBranch
            & (nextValid_13
                 ? _instBuffer_io_dataOut_14_addr
                 : noFire0Fault
                     ? io_fault_bits_mepc
                     : io_inst_0_valid
                         ? io_inst_0_bits_addr
                         : _instBuffer_io_dataOut_14_addr) == _instBuffer_io_dataOut_13_addr
            + 32'h4)) | noFire0Fault) & ~_instBuffer_io_dataOut_13_isMpause;
  wire        currentDataDone_13 =
    resultBuffer_13_valid | validBufferEntry_13 & ~resultBuffer_13_valid
    & (io_writeDataScalar_0_valid & _GEN_0 == _instBuffer_io_dataOut_13_idx
       | io_writeDataScalar_1_valid & _GEN_1 == _instBuffer_io_dataOut_13_idx
       | io_writeDataScalar_2_valid & _GEN_2 == _instBuffer_io_dataOut_13_idx
       | io_writeDataScalar_3_valid & _GEN_3 == _instBuffer_io_dataOut_13_idx
       | io_writeDataScalar_4_valid & _GEN_4 == _instBuffer_io_dataOut_13_idx
       | io_writeDataScalar_5_valid & _GEN_5 == _instBuffer_io_dataOut_13_idx
       | io_writeDataFloat_0_valid
       & _floatWriteIdxMap_T_60 == _instBuffer_io_dataOut_13_idx
       | io_writeDataFloat_1_valid
       & _floatWriteIdxMap_T_62 == _instBuffer_io_dataOut_13_idx
       | (&_instBuffer_io_dataOut_13_idx) | _instBuffer_io_dataOut_13_idx == 7'h7E
       & storeComplete_pipe_v & storeComplete_pipe_b == _instBuffer_io_dataOut_13_addr
       | currentTrap_13);
  wire        validBufferEntry_14 = _instBuffer_io_nEnqueued > 5'hE;
  wire        nextAddrValid_14 =
    _instBuffer_io_nEnqueued[4] | noFire0Fault | io_inst_0_valid;
  wire        newCfDone_14 =
    validBufferEntry_14 & (~_instBuffer_io_dataOut_14_isControlFlow | nextAddrValid_14);
  wire        currentTrap_14 =
    resultBuffer_14_bits_trap | io_fault_valid
    & _instBuffer_io_dataOut_14_addr == io_fault_bits_mepc | validBufferEntry_14
    & _instBuffer_io_dataOut_14_trap | _instBuffer_io_dataOut_14_isControlFlow
    & newCfDone_14
    & (~(nextAddrValid_14
         & ((_instBuffer_io_nEnqueued[4]
               ? _instBuffer_io_dataOut_15_linkOk
               : noFire0Fault
                   ? _faultLinkOk_T_75 | regLastIsBranch
                     & io_fault_bits_mepc == _faultLinkOk_T_76
                   : ~io_inst_0_valid | _lane0LinkOk_T_75 | regLastIsBranch
                     & io_inst_0_bits_addr == _faultLinkOk_T_76)
            | _instBuffer_io_dataOut_14_isBranch
            & (_instBuffer_io_nEnqueued[4]
                 ? _instBuffer_io_dataOut_15_addr
                 : noFire0Fault
                     ? io_fault_bits_mepc
                     : io_inst_0_valid
                         ? io_inst_0_bits_addr
                         : _instBuffer_io_dataOut_15_addr) == _instBuffer_io_dataOut_14_addr
            + 32'h4)) | noFire0Fault) & ~_instBuffer_io_dataOut_14_isMpause;
  wire        currentDataDone_14 =
    resultBuffer_14_valid | validBufferEntry_14 & ~resultBuffer_14_valid
    & (io_writeDataScalar_0_valid & _GEN_0 == _instBuffer_io_dataOut_14_idx
       | io_writeDataScalar_1_valid & _GEN_1 == _instBuffer_io_dataOut_14_idx
       | io_writeDataScalar_2_valid & _GEN_2 == _instBuffer_io_dataOut_14_idx
       | io_writeDataScalar_3_valid & _GEN_3 == _instBuffer_io_dataOut_14_idx
       | io_writeDataScalar_4_valid & _GEN_4 == _instBuffer_io_dataOut_14_idx
       | io_writeDataScalar_5_valid & _GEN_5 == _instBuffer_io_dataOut_14_idx
       | io_writeDataFloat_0_valid
       & _floatWriteIdxMap_T_60 == _instBuffer_io_dataOut_14_idx
       | io_writeDataFloat_1_valid
       & _floatWriteIdxMap_T_62 == _instBuffer_io_dataOut_14_idx
       | (&_instBuffer_io_dataOut_14_idx) | _instBuffer_io_dataOut_14_idx == 7'h7E
       & storeComplete_pipe_v & storeComplete_pipe_b == _instBuffer_io_dataOut_14_addr
       | currentTrap_14);
  wire        nextAddrValid_15 = noFire0Fault | io_inst_0_valid;
  wire        newCfDone_15 =
    _instBuffer_io_nEnqueued[4]
    & (~_instBuffer_io_dataOut_15_isControlFlow | nextAddrValid_15);
  wire        currentTrap_15 =
    resultBuffer_15_bits_trap | io_fault_valid
    & _instBuffer_io_dataOut_15_addr == io_fault_bits_mepc | _instBuffer_io_nEnqueued[4]
    & _instBuffer_io_dataOut_15_trap | _instBuffer_io_dataOut_15_isControlFlow
    & newCfDone_15
    & (~(nextAddrValid_15
         & ((noFire0Fault
               ? _faultLinkOk_T_75 | regLastIsBranch
                 & io_fault_bits_mepc == _faultLinkOk_T_76
               : ~io_inst_0_valid | _lane0LinkOk_T_75 | regLastIsBranch
                 & io_inst_0_bits_addr == _faultLinkOk_T_76)
            | _instBuffer_io_dataOut_15_isBranch
            & (noFire0Fault
                 ? io_fault_bits_mepc
                 : io_inst_0_valid
                     ? io_inst_0_bits_addr
                     : 32'h0) == _instBuffer_io_dataOut_15_addr + 32'h4)) | noFire0Fault)
    & ~_instBuffer_io_dataOut_15_isMpause;
  wire        currentDataDone_15 =
    resultBuffer_15_valid | _instBuffer_io_nEnqueued[4] & ~resultBuffer_15_valid
    & (io_writeDataScalar_0_valid & _GEN_0 == _instBuffer_io_dataOut_15_idx
       | io_writeDataScalar_1_valid & _GEN_1 == _instBuffer_io_dataOut_15_idx
       | io_writeDataScalar_2_valid & _GEN_2 == _instBuffer_io_dataOut_15_idx
       | io_writeDataScalar_3_valid & _GEN_3 == _instBuffer_io_dataOut_15_idx
       | io_writeDataScalar_4_valid & _GEN_4 == _instBuffer_io_dataOut_15_idx
       | io_writeDataScalar_5_valid & _GEN_5 == _instBuffer_io_dataOut_15_idx
       | io_writeDataFloat_0_valid
       & _floatWriteIdxMap_T_60 == _instBuffer_io_dataOut_15_idx
       | io_writeDataFloat_1_valid
       & _floatWriteIdxMap_T_62 == _instBuffer_io_dataOut_15_idx
       | (&_instBuffer_io_dataOut_15_idx) | _instBuffer_io_dataOut_15_idx == 7'h7E
       & storeComplete_pipe_v & storeComplete_pipe_b == _instBuffer_io_dataOut_15_addr
       | currentTrap_15);
  wire [47:0] shifted =
    {currentDataDone_15,
     currentTrap_15,
     resultBuffer_15_valid & resultBuffer_15_bits_cfDone | newCfDone_15,
     currentDataDone_14,
     currentTrap_14,
     resultBuffer_14_valid & resultBuffer_14_bits_cfDone | newCfDone_14,
     currentDataDone_13,
     currentTrap_13,
     resultBuffer_13_valid & resultBuffer_13_bits_cfDone | newCfDone_13,
     currentDataDone_12,
     currentTrap_12,
     resultBuffer_12_valid & resultBuffer_12_bits_cfDone | newCfDone_12,
     currentDataDone_11,
     currentTrap_11,
     resultBuffer_11_valid & resultBuffer_11_bits_cfDone | newCfDone_11,
     currentDataDone_10,
     currentTrap_10,
     resultBuffer_10_valid & resultBuffer_10_bits_cfDone | newCfDone_10,
     currentDataDone_9,
     currentTrap_9,
     resultBuffer_9_valid & resultBuffer_9_bits_cfDone | newCfDone_9,
     currentDataDone_8,
     currentTrap_8,
     resultBuffer_8_valid & resultBuffer_8_bits_cfDone | newCfDone_8,
     currentDataDone_7,
     currentTrap_7,
     currentCfDone_7,
     currentDataDone_6,
     currentTrap_6,
     currentCfDone_6,
     currentDataDone_5,
     currentTrap_5,
     currentCfDone_5,
     currentDataDone_4,
     currentTrap_4,
     currentCfDone_4,
     currentDataDone_3,
     currentTrap_3,
     currentCfDone_3,
     currentDataDone_2,
     currentTrap_2,
     currentCfDone_2,
     currentDataDone_1,
     currentTrap_1,
     currentCfDone_1,
     currentDataDone,
     hi,
     currentCfDone} >> {2'h0, deqReady} * 6'h3;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      storeComplete_pipe_v <= 1'h0;
      regLastTarget <= 32'h0;
      regLastAddr <= 32'h0;
      regLastIsBranch <= 1'h0;
      resultBuffer_0_valid <= 1'h0;
      resultBuffer_0_bits_trap <= 1'h0;
      resultBuffer_0_bits_cfDone <= 1'h0;
      resultBuffer_1_valid <= 1'h0;
      resultBuffer_1_bits_trap <= 1'h0;
      resultBuffer_1_bits_cfDone <= 1'h0;
      resultBuffer_2_valid <= 1'h0;
      resultBuffer_2_bits_trap <= 1'h0;
      resultBuffer_2_bits_cfDone <= 1'h0;
      resultBuffer_3_valid <= 1'h0;
      resultBuffer_3_bits_trap <= 1'h0;
      resultBuffer_3_bits_cfDone <= 1'h0;
      resultBuffer_4_valid <= 1'h0;
      resultBuffer_4_bits_trap <= 1'h0;
      resultBuffer_4_bits_cfDone <= 1'h0;
      resultBuffer_5_valid <= 1'h0;
      resultBuffer_5_bits_trap <= 1'h0;
      resultBuffer_5_bits_cfDone <= 1'h0;
      resultBuffer_6_valid <= 1'h0;
      resultBuffer_6_bits_trap <= 1'h0;
      resultBuffer_6_bits_cfDone <= 1'h0;
      resultBuffer_7_valid <= 1'h0;
      resultBuffer_7_bits_trap <= 1'h0;
      resultBuffer_7_bits_cfDone <= 1'h0;
      resultBuffer_8_valid <= 1'h0;
      resultBuffer_8_bits_trap <= 1'h0;
      resultBuffer_8_bits_cfDone <= 1'h0;
      resultBuffer_9_valid <= 1'h0;
      resultBuffer_9_bits_trap <= 1'h0;
      resultBuffer_9_bits_cfDone <= 1'h0;
      resultBuffer_10_valid <= 1'h0;
      resultBuffer_10_bits_trap <= 1'h0;
      resultBuffer_10_bits_cfDone <= 1'h0;
      resultBuffer_11_valid <= 1'h0;
      resultBuffer_11_bits_trap <= 1'h0;
      resultBuffer_11_bits_cfDone <= 1'h0;
      resultBuffer_12_valid <= 1'h0;
      resultBuffer_12_bits_trap <= 1'h0;
      resultBuffer_12_bits_cfDone <= 1'h0;
      resultBuffer_13_valid <= 1'h0;
      resultBuffer_13_bits_trap <= 1'h0;
      resultBuffer_13_bits_cfDone <= 1'h0;
      resultBuffer_14_valid <= 1'h0;
      resultBuffer_14_bits_trap <= 1'h0;
      resultBuffer_14_bits_cfDone <= 1'h0;
      resultBuffer_15_valid <= 1'h0;
      resultBuffer_15_bits_trap <= 1'h0;
      resultBuffer_15_bits_cfDone <= 1'h0;
      deqReady_reg <= 4'h0;
      retiredEcalls_reg <= 4'h0;
      io_trapPending_REG <= 1'h0;
    end
    else begin
      storeComplete_pipe_v <= io_storeComplete_valid;
      if (instFires_0 | instFires_1 | instFires_2 | instFires_3) begin
        regLastTarget <=
          instFires_3
            ? (io_inst_3_bits_inst[6:0] == 7'h67 ? io_jalrTargets_3 : io_targets_3)
            : instFires_2
                ? (io_inst_2_bits_inst[6:0] == 7'h67 ? io_jalrTargets_2 : io_targets_2)
                : instFires_1
                    ? (io_inst_1_bits_inst[6:0] == 7'h67
                         ? io_jalrTargets_1
                         : io_targets_1)
                    : io_inst_0_bits_inst[6:0] == 7'h67 ? io_jalrTargets_0 : io_targets_0;
        regLastAddr <=
          instFires_3
            ? io_inst_3_bits_addr
            : instFires_2
                ? io_inst_2_bits_addr
                : instFires_1 ? io_inst_1_bits_addr : io_inst_0_bits_addr;
        regLastIsBranch <=
          instFires_3
            ? io_branch_3
            : instFires_2 ? io_branch_2 : instFires_1 ? io_branch_1 : io_branch_0;
      end
      resultBuffer_0_valid <= ~trapRetired & shifted[2];
      resultBuffer_0_bits_trap <= ~trapRetired & shifted[1];
      resultBuffer_0_bits_cfDone <= ~trapRetired & shifted[0];
      resultBuffer_1_valid <= ~trapRetired & shifted[5];
      resultBuffer_1_bits_trap <= ~trapRetired & shifted[4];
      resultBuffer_1_bits_cfDone <= ~trapRetired & shifted[3];
      resultBuffer_2_valid <= ~trapRetired & shifted[8];
      resultBuffer_2_bits_trap <= ~trapRetired & shifted[7];
      resultBuffer_2_bits_cfDone <= ~trapRetired & shifted[6];
      resultBuffer_3_valid <= ~trapRetired & shifted[11];
      resultBuffer_3_bits_trap <= ~trapRetired & shifted[10];
      resultBuffer_3_bits_cfDone <= ~trapRetired & shifted[9];
      resultBuffer_4_valid <= ~trapRetired & shifted[14];
      resultBuffer_4_bits_trap <= ~trapRetired & shifted[13];
      resultBuffer_4_bits_cfDone <= ~trapRetired & shifted[12];
      resultBuffer_5_valid <= ~trapRetired & shifted[17];
      resultBuffer_5_bits_trap <= ~trapRetired & shifted[16];
      resultBuffer_5_bits_cfDone <= ~trapRetired & shifted[15];
      resultBuffer_6_valid <= ~trapRetired & shifted[20];
      resultBuffer_6_bits_trap <= ~trapRetired & shifted[19];
      resultBuffer_6_bits_cfDone <= ~trapRetired & shifted[18];
      resultBuffer_7_valid <= ~trapRetired & shifted[23];
      resultBuffer_7_bits_trap <= ~trapRetired & shifted[22];
      resultBuffer_7_bits_cfDone <= ~trapRetired & shifted[21];
      resultBuffer_8_valid <= ~trapRetired & shifted[26];
      resultBuffer_8_bits_trap <= ~trapRetired & shifted[25];
      resultBuffer_8_bits_cfDone <= ~trapRetired & shifted[24];
      resultBuffer_9_valid <= ~trapRetired & shifted[29];
      resultBuffer_9_bits_trap <= ~trapRetired & shifted[28];
      resultBuffer_9_bits_cfDone <= ~trapRetired & shifted[27];
      resultBuffer_10_valid <= ~trapRetired & shifted[32];
      resultBuffer_10_bits_trap <= ~trapRetired & shifted[31];
      resultBuffer_10_bits_cfDone <= ~trapRetired & shifted[30];
      resultBuffer_11_valid <= ~trapRetired & shifted[35];
      resultBuffer_11_bits_trap <= ~trapRetired & shifted[34];
      resultBuffer_11_bits_cfDone <= ~trapRetired & shifted[33];
      resultBuffer_12_valid <= ~trapRetired & shifted[38];
      resultBuffer_12_bits_trap <= ~trapRetired & shifted[37];
      resultBuffer_12_bits_cfDone <= ~trapRetired & shifted[36];
      resultBuffer_13_valid <= ~trapRetired & shifted[41];
      resultBuffer_13_bits_trap <= ~trapRetired & shifted[40];
      resultBuffer_13_bits_cfDone <= ~trapRetired & shifted[39];
      resultBuffer_14_valid <= ~trapRetired & shifted[44];
      resultBuffer_14_bits_trap <= ~trapRetired & shifted[43];
      resultBuffer_14_bits_cfDone <= ~trapRetired & shifted[42];
      resultBuffer_15_valid <= ~trapRetired & shifted[47];
      resultBuffer_15_bits_trap <= ~trapRetired & shifted[46];
      resultBuffer_15_bits_cfDone <= ~trapRetired & shifted[45];
      deqReady_reg <= deqReady;
      retiredEcalls_reg <=
        {1'h0,
         {1'h0,
          {1'h0, (|deqReady) & _instBuffer_io_dataOut_0_isEcall}
            + {1'h0, (|(deqReady[3:1])) & _instBuffer_io_dataOut_1_isEcall}}
           + {1'h0,
              {1'h0, deqReady > 4'h2 & _instBuffer_io_dataOut_2_isEcall}
                + {1'h0, (|(deqReady[3:2])) & _instBuffer_io_dataOut_3_isEcall}}}
        + {1'h0,
           {1'h0,
            {1'h0, deqReady > 4'h4 & _instBuffer_io_dataOut_4_isEcall}
              + {1'h0, deqReady > 4'h5 & _instBuffer_io_dataOut_5_isEcall}}
             + {1'h0,
                {1'h0, deqReady > 4'h6 & _instBuffer_io_dataOut_6_isEcall}
                  + {1'h0, deqReady[3] & _instBuffer_io_dataOut_7_isEcall}}};
      io_trapPending_REG <=
        (currentDataDone & hi | currentDataDone_1 & currentTrap_1 | currentDataDone_2
         & currentTrap_2 | currentDataDone_3 & currentTrap_3 | currentDataDone_4
         & currentTrap_4 | currentDataDone_5 & currentTrap_5 | currentDataDone_6
         & currentTrap_6 | currentDataDone_7 & currentTrap_7 | currentDataDone_8
         & currentTrap_8 | currentDataDone_9 & currentTrap_9 | currentDataDone_10
         & currentTrap_10 | currentDataDone_11 & currentTrap_11 | currentDataDone_12
         & currentTrap_12 | currentDataDone_13 & currentTrap_13 | currentDataDone_14
         & currentTrap_14 | currentDataDone_15 & currentTrap_15) & ~trapRetired;
    end
  end // always @(posedge, posedge)
  always @(posedge clock) begin
    if (io_storeComplete_valid)
      storeComplete_pipe_b <= io_storeComplete_bits;
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:5];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [2:0] i = 3'h0; i < 3'h6; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        storeComplete_pipe_v = _RANDOM[3'h0][0];
        storeComplete_pipe_b = {_RANDOM[3'h0][31:1], _RANDOM[3'h1][0]};
        regLastTarget = {_RANDOM[3'h1][31:1], _RANDOM[3'h2][0]};
        regLastAddr = {_RANDOM[3'h2][31:1], _RANDOM[3'h3][0]};
        regLastIsBranch = _RANDOM[3'h3][1];
        resultBuffer_0_valid = _RANDOM[3'h3][2];
        resultBuffer_0_bits_trap = _RANDOM[3'h3][3];
        resultBuffer_0_bits_cfDone = _RANDOM[3'h3][4];
        resultBuffer_1_valid = _RANDOM[3'h3][5];
        resultBuffer_1_bits_trap = _RANDOM[3'h3][6];
        resultBuffer_1_bits_cfDone = _RANDOM[3'h3][7];
        resultBuffer_2_valid = _RANDOM[3'h3][8];
        resultBuffer_2_bits_trap = _RANDOM[3'h3][9];
        resultBuffer_2_bits_cfDone = _RANDOM[3'h3][10];
        resultBuffer_3_valid = _RANDOM[3'h3][11];
        resultBuffer_3_bits_trap = _RANDOM[3'h3][12];
        resultBuffer_3_bits_cfDone = _RANDOM[3'h3][13];
        resultBuffer_4_valid = _RANDOM[3'h3][14];
        resultBuffer_4_bits_trap = _RANDOM[3'h3][15];
        resultBuffer_4_bits_cfDone = _RANDOM[3'h3][16];
        resultBuffer_5_valid = _RANDOM[3'h3][17];
        resultBuffer_5_bits_trap = _RANDOM[3'h3][18];
        resultBuffer_5_bits_cfDone = _RANDOM[3'h3][19];
        resultBuffer_6_valid = _RANDOM[3'h3][20];
        resultBuffer_6_bits_trap = _RANDOM[3'h3][21];
        resultBuffer_6_bits_cfDone = _RANDOM[3'h3][22];
        resultBuffer_7_valid = _RANDOM[3'h3][23];
        resultBuffer_7_bits_trap = _RANDOM[3'h3][24];
        resultBuffer_7_bits_cfDone = _RANDOM[3'h3][25];
        resultBuffer_8_valid = _RANDOM[3'h3][26];
        resultBuffer_8_bits_trap = _RANDOM[3'h3][27];
        resultBuffer_8_bits_cfDone = _RANDOM[3'h3][28];
        resultBuffer_9_valid = _RANDOM[3'h3][29];
        resultBuffer_9_bits_trap = _RANDOM[3'h3][30];
        resultBuffer_9_bits_cfDone = _RANDOM[3'h3][31];
        resultBuffer_10_valid = _RANDOM[3'h4][0];
        resultBuffer_10_bits_trap = _RANDOM[3'h4][1];
        resultBuffer_10_bits_cfDone = _RANDOM[3'h4][2];
        resultBuffer_11_valid = _RANDOM[3'h4][3];
        resultBuffer_11_bits_trap = _RANDOM[3'h4][4];
        resultBuffer_11_bits_cfDone = _RANDOM[3'h4][5];
        resultBuffer_12_valid = _RANDOM[3'h4][6];
        resultBuffer_12_bits_trap = _RANDOM[3'h4][7];
        resultBuffer_12_bits_cfDone = _RANDOM[3'h4][8];
        resultBuffer_13_valid = _RANDOM[3'h4][9];
        resultBuffer_13_bits_trap = _RANDOM[3'h4][10];
        resultBuffer_13_bits_cfDone = _RANDOM[3'h4][11];
        resultBuffer_14_valid = _RANDOM[3'h4][12];
        resultBuffer_14_bits_trap = _RANDOM[3'h4][13];
        resultBuffer_14_bits_cfDone = _RANDOM[3'h4][14];
        resultBuffer_15_valid = _RANDOM[3'h4][15];
        resultBuffer_15_bits_trap = _RANDOM[3'h4][16];
        resultBuffer_15_bits_cfDone = _RANDOM[3'h4][17];
        deqReady_reg = _RANDOM[3'h4][29:26];
        retiredEcalls_reg = {_RANDOM[3'h4][31:30], _RANDOM[3'h5][1:0]};
        io_trapPending_REG = _RANDOM[3'h5][2];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        storeComplete_pipe_v = 1'h0;
        regLastTarget = 32'h0;
        regLastAddr = 32'h0;
        regLastIsBranch = 1'h0;
        resultBuffer_0_valid = 1'h0;
        resultBuffer_0_bits_trap = 1'h0;
        resultBuffer_0_bits_cfDone = 1'h0;
        resultBuffer_1_valid = 1'h0;
        resultBuffer_1_bits_trap = 1'h0;
        resultBuffer_1_bits_cfDone = 1'h0;
        resultBuffer_2_valid = 1'h0;
        resultBuffer_2_bits_trap = 1'h0;
        resultBuffer_2_bits_cfDone = 1'h0;
        resultBuffer_3_valid = 1'h0;
        resultBuffer_3_bits_trap = 1'h0;
        resultBuffer_3_bits_cfDone = 1'h0;
        resultBuffer_4_valid = 1'h0;
        resultBuffer_4_bits_trap = 1'h0;
        resultBuffer_4_bits_cfDone = 1'h0;
        resultBuffer_5_valid = 1'h0;
        resultBuffer_5_bits_trap = 1'h0;
        resultBuffer_5_bits_cfDone = 1'h0;
        resultBuffer_6_valid = 1'h0;
        resultBuffer_6_bits_trap = 1'h0;
        resultBuffer_6_bits_cfDone = 1'h0;
        resultBuffer_7_valid = 1'h0;
        resultBuffer_7_bits_trap = 1'h0;
        resultBuffer_7_bits_cfDone = 1'h0;
        resultBuffer_8_valid = 1'h0;
        resultBuffer_8_bits_trap = 1'h0;
        resultBuffer_8_bits_cfDone = 1'h0;
        resultBuffer_9_valid = 1'h0;
        resultBuffer_9_bits_trap = 1'h0;
        resultBuffer_9_bits_cfDone = 1'h0;
        resultBuffer_10_valid = 1'h0;
        resultBuffer_10_bits_trap = 1'h0;
        resultBuffer_10_bits_cfDone = 1'h0;
        resultBuffer_11_valid = 1'h0;
        resultBuffer_11_bits_trap = 1'h0;
        resultBuffer_11_bits_cfDone = 1'h0;
        resultBuffer_12_valid = 1'h0;
        resultBuffer_12_bits_trap = 1'h0;
        resultBuffer_12_bits_cfDone = 1'h0;
        resultBuffer_13_valid = 1'h0;
        resultBuffer_13_bits_trap = 1'h0;
        resultBuffer_13_bits_cfDone = 1'h0;
        resultBuffer_14_valid = 1'h0;
        resultBuffer_14_bits_trap = 1'h0;
        resultBuffer_14_bits_cfDone = 1'h0;
        resultBuffer_15_valid = 1'h0;
        resultBuffer_15_bits_trap = 1'h0;
        resultBuffer_15_bits_cfDone = 1'h0;
        deqReady_reg = 4'h0;
        retiredEcalls_reg = 4'h0;
        io_trapPending_REG = 1'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  CircularBufferMulti_2 instBuffer (
    .clock                       (clock),
    .reset                       (reset),
    .io_enqValid
      ({1'h0,
        {1'h0,
         {1'h0, {1'h0, instFires_0} + {1'h0, instFires_1}}
           + {1'h0, {1'h0, instFires_2} + {1'h0, instFires_3}}}
          + {3'h0, decodeFaultValid | noFire0Fault}}),
    .io_enqData_0_addr
      (noFire0Fault ? io_fault_bits_mepc : io_inst_0_bits_addr),
    .io_enqData_0_idx
      (io_writeAddrFloat_valid
         ? {2'h0, io_writeAddrFloat_addr} + 7'h20
         : noFire0Fault
             ? (io_writeAddrScalar_0_valid & (|io_writeAddrScalar_0_addr)
                  ? _GEN
                  : {6'h3F,
                     ~(io_inst_0_bits_inst[6:0] == 7'h23
                       | io_inst_0_bits_inst[6:0] == 7'h27
                       & (io_inst_0_bits_inst[14:12] == 3'h1
                          | io_inst_0_bits_inst[14:12] == 3'h2
                          | io_inst_0_bits_inst[14:12] == 3'h3
                          | io_inst_0_bits_inst[14:12] == 3'h4))})
             : io_writeAddrScalar_0_valid & (|io_writeAddrScalar_0_addr)
                 ? _GEN
                 : {6'h3F,
                    ~(io_inst_0_bits_inst[6:0] == 7'h23
                      | io_inst_0_bits_inst[6:0] == 7'h27
                      & (io_inst_0_bits_inst[14:12] == 3'h1
                         | io_inst_0_bits_inst[14:12] == 3'h2
                         | io_inst_0_bits_inst[14:12] == 3'h3
                         | io_inst_0_bits_inst[14:12] == 3'h4))}),
    .io_enqData_0_trap
      (noFire0Fault | decodeFaultValid & io_fault_bits_mepc == io_inst_0_bits_addr),
    .io_enqData_0_isControlFlow  (io_jump_0 | io_branch_0),
    .io_enqData_0_isBranch       (io_branch_0),
    .io_enqData_0_isVector       (1'h0),
    .io_enqData_0_linkOk
      (noFire0Fault
         ? io_fault_bits_mepc == regLastTarget | regLastIsBranch
           & io_fault_bits_mepc == _faultLinkOk_T_76
         : _lane0LinkOk_T_75 | regLastIsBranch
           & io_inst_0_bits_addr == _faultLinkOk_T_76),
    .io_enqData_0_isEcall        (io_inst_0_bits_inst == 32'h73),
    .io_enqData_0_isMpause       (io_inst_0_bits_inst == 32'h8000073),
    .io_enqData_1_addr           (io_inst_1_bits_addr),
    .io_enqData_1_idx
      (io_writeAddrScalar_1_valid & (|io_writeAddrScalar_1_addr)
         ? {2'h0, io_writeAddrScalar_1_addr}
         : {6'h3F,
            ~(io_inst_1_bits_inst[6:0] == 7'h23 | io_inst_1_bits_inst[6:0] == 7'h27
              & (io_inst_1_bits_inst[14:12] == 3'h1 | io_inst_1_bits_inst[14:12] == 3'h2
                 | io_inst_1_bits_inst[14:12] == 3'h3
                 | io_inst_1_bits_inst[14:12] == 3'h4))}),
    .io_enqData_1_trap
      (decodeFaultValid & io_fault_bits_mepc == io_inst_1_bits_addr),
    .io_enqData_1_isControlFlow  (io_jump_1 | io_branch_1),
    .io_enqData_1_isBranch       (io_branch_1),
    .io_enqData_1_isVector       (1'h0),
    .io_enqData_1_linkOk
      (io_inst_1_bits_addr == (io_inst_0_bits_inst[6:0] == 7'h67
                                 ? io_jalrTargets_0
                                 : io_targets_0) | io_branch_0
       & io_inst_1_bits_addr == io_inst_0_bits_addr + 32'h4),
    .io_enqData_1_isEcall        (io_inst_1_bits_inst == 32'h73),
    .io_enqData_1_isMpause       (io_inst_1_bits_inst == 32'h8000073),
    .io_enqData_2_addr           (io_inst_2_bits_addr),
    .io_enqData_2_idx
      (io_writeAddrScalar_2_valid & (|io_writeAddrScalar_2_addr)
         ? {2'h0, io_writeAddrScalar_2_addr}
         : {6'h3F,
            ~(io_inst_2_bits_inst[6:0] == 7'h23 | io_inst_2_bits_inst[6:0] == 7'h27
              & (io_inst_2_bits_inst[14:12] == 3'h1 | io_inst_2_bits_inst[14:12] == 3'h2
                 | io_inst_2_bits_inst[14:12] == 3'h3
                 | io_inst_2_bits_inst[14:12] == 3'h4))}),
    .io_enqData_2_trap
      (decodeFaultValid & io_fault_bits_mepc == io_inst_2_bits_addr),
    .io_enqData_2_isControlFlow  (io_jump_2 | io_branch_2),
    .io_enqData_2_isBranch       (io_branch_2),
    .io_enqData_2_isVector       (1'h0),
    .io_enqData_2_linkOk
      (io_inst_2_bits_addr == (io_inst_1_bits_inst[6:0] == 7'h67
                                 ? io_jalrTargets_1
                                 : io_targets_1) | io_branch_1
       & io_inst_2_bits_addr == io_inst_1_bits_addr + 32'h4),
    .io_enqData_2_isEcall        (io_inst_2_bits_inst == 32'h73),
    .io_enqData_2_isMpause       (io_inst_2_bits_inst == 32'h8000073),
    .io_enqData_3_addr           (io_inst_3_bits_addr),
    .io_enqData_3_idx
      (io_writeAddrScalar_3_valid & (|io_writeAddrScalar_3_addr)
         ? {2'h0, io_writeAddrScalar_3_addr}
         : {6'h3F,
            ~(io_inst_3_bits_inst[6:0] == 7'h23 | io_inst_3_bits_inst[6:0] == 7'h27
              & (io_inst_3_bits_inst[14:12] == 3'h1 | io_inst_3_bits_inst[14:12] == 3'h2
                 | io_inst_3_bits_inst[14:12] == 3'h3
                 | io_inst_3_bits_inst[14:12] == 3'h4))}),
    .io_enqData_3_trap
      (decodeFaultValid & io_fault_bits_mepc == io_inst_3_bits_addr),
    .io_enqData_3_isControlFlow  (io_jump_3 | io_branch_3),
    .io_enqData_3_isBranch       (io_branch_3),
    .io_enqData_3_isVector       (1'h0),
    .io_enqData_3_linkOk
      (io_inst_3_bits_addr == (io_inst_2_bits_inst[6:0] == 7'h67
                                 ? io_jalrTargets_2
                                 : io_targets_2) | io_branch_2
       & io_inst_3_bits_addr == io_inst_2_bits_addr + 32'h4),
    .io_enqData_3_isEcall        (io_inst_3_bits_inst == 32'h73),
    .io_enqData_3_isMpause       (io_inst_3_bits_inst == 32'h8000073),
    .io_enqData_4_addr           (32'h0),
    .io_enqData_4_idx            (7'h0),
    .io_enqData_4_trap           (1'h0),
    .io_enqData_4_isControlFlow  (1'h0),
    .io_enqData_4_isBranch       (1'h0),
    .io_enqData_4_isVector       (1'h0),
    .io_enqData_4_linkOk         (1'h0),
    .io_enqData_4_isEcall        (1'h0),
    .io_enqData_4_isMpause       (1'h0),
    .io_enqData_5_addr           (32'h0),
    .io_enqData_5_idx            (7'h0),
    .io_enqData_5_trap           (1'h0),
    .io_enqData_5_isControlFlow  (1'h0),
    .io_enqData_5_isBranch       (1'h0),
    .io_enqData_5_isVector       (1'h0),
    .io_enqData_5_linkOk         (1'h0),
    .io_enqData_5_isEcall        (1'h0),
    .io_enqData_5_isMpause       (1'h0),
    .io_enqData_6_addr           (32'h0),
    .io_enqData_6_idx            (7'h0),
    .io_enqData_6_trap           (1'h0),
    .io_enqData_6_isControlFlow  (1'h0),
    .io_enqData_6_isBranch       (1'h0),
    .io_enqData_6_isVector       (1'h0),
    .io_enqData_6_linkOk         (1'h0),
    .io_enqData_6_isEcall        (1'h0),
    .io_enqData_6_isMpause       (1'h0),
    .io_enqData_7_addr           (32'h0),
    .io_enqData_7_idx            (7'h0),
    .io_enqData_7_trap           (1'h0),
    .io_enqData_7_isControlFlow  (1'h0),
    .io_enqData_7_isBranch       (1'h0),
    .io_enqData_7_isVector       (1'h0),
    .io_enqData_7_linkOk         (1'h0),
    .io_enqData_7_isEcall        (1'h0),
    .io_enqData_7_isMpause       (1'h0),
    .io_enqData_8_addr           (32'h0),
    .io_enqData_8_idx            (7'h0),
    .io_enqData_8_trap           (1'h0),
    .io_enqData_8_isControlFlow  (1'h0),
    .io_enqData_8_isBranch       (1'h0),
    .io_enqData_8_isVector       (1'h0),
    .io_enqData_8_linkOk         (1'h0),
    .io_enqData_8_isEcall        (1'h0),
    .io_enqData_8_isMpause       (1'h0),
    .io_enqData_9_addr           (32'h0),
    .io_enqData_9_idx            (7'h0),
    .io_enqData_9_trap           (1'h0),
    .io_enqData_9_isControlFlow  (1'h0),
    .io_enqData_9_isBranch       (1'h0),
    .io_enqData_9_isVector       (1'h0),
    .io_enqData_9_linkOk         (1'h0),
    .io_enqData_9_isEcall        (1'h0),
    .io_enqData_9_isMpause       (1'h0),
    .io_enqData_10_addr          (32'h0),
    .io_enqData_10_idx           (7'h0),
    .io_enqData_10_trap          (1'h0),
    .io_enqData_10_isControlFlow (1'h0),
    .io_enqData_10_isBranch      (1'h0),
    .io_enqData_10_isVector      (1'h0),
    .io_enqData_10_linkOk        (1'h0),
    .io_enqData_10_isEcall       (1'h0),
    .io_enqData_10_isMpause      (1'h0),
    .io_enqData_11_addr          (32'h0),
    .io_enqData_11_idx           (7'h0),
    .io_enqData_11_trap          (1'h0),
    .io_enqData_11_isControlFlow (1'h0),
    .io_enqData_11_isBranch      (1'h0),
    .io_enqData_11_isVector      (1'h0),
    .io_enqData_11_linkOk        (1'h0),
    .io_enqData_11_isEcall       (1'h0),
    .io_enqData_11_isMpause      (1'h0),
    .io_enqData_12_addr          (32'h0),
    .io_enqData_12_idx           (7'h0),
    .io_enqData_12_trap          (1'h0),
    .io_enqData_12_isControlFlow (1'h0),
    .io_enqData_12_isBranch      (1'h0),
    .io_enqData_12_isVector      (1'h0),
    .io_enqData_12_linkOk        (1'h0),
    .io_enqData_12_isEcall       (1'h0),
    .io_enqData_12_isMpause      (1'h0),
    .io_enqData_13_addr          (32'h0),
    .io_enqData_13_idx           (7'h0),
    .io_enqData_13_trap          (1'h0),
    .io_enqData_13_isControlFlow (1'h0),
    .io_enqData_13_isBranch      (1'h0),
    .io_enqData_13_isVector      (1'h0),
    .io_enqData_13_linkOk        (1'h0),
    .io_enqData_13_isEcall       (1'h0),
    .io_enqData_13_isMpause      (1'h0),
    .io_enqData_14_addr          (32'h0),
    .io_enqData_14_idx           (7'h0),
    .io_enqData_14_trap          (1'h0),
    .io_enqData_14_isControlFlow (1'h0),
    .io_enqData_14_isBranch      (1'h0),
    .io_enqData_14_isVector      (1'h0),
    .io_enqData_14_linkOk        (1'h0),
    .io_enqData_14_isEcall       (1'h0),
    .io_enqData_14_isMpause      (1'h0),
    .io_enqData_15_addr          (32'h0),
    .io_enqData_15_idx           (7'h0),
    .io_enqData_15_trap          (1'h0),
    .io_enqData_15_isControlFlow (1'h0),
    .io_enqData_15_isBranch      (1'h0),
    .io_enqData_15_isVector      (1'h0),
    .io_enqData_15_linkOk        (1'h0),
    .io_enqData_15_isEcall       (1'h0),
    .io_enqData_15_isMpause      (1'h0),
    .io_nEnqueued                (_instBuffer_io_nEnqueued),
    .io_nSpace                   (io_nSpace),
    .io_dataOut_0_addr           (_instBuffer_io_dataOut_0_addr),
    .io_dataOut_0_idx            (_instBuffer_io_dataOut_0_idx),
    .io_dataOut_0_trap           (_instBuffer_io_dataOut_0_trap),
    .io_dataOut_0_isControlFlow  (_instBuffer_io_dataOut_0_isControlFlow),
    .io_dataOut_0_isBranch       (_instBuffer_io_dataOut_0_isBranch),
    .io_dataOut_0_isVector       (/* unused */),
    .io_dataOut_0_linkOk         (/* unused */),
    .io_dataOut_0_isEcall        (_instBuffer_io_dataOut_0_isEcall),
    .io_dataOut_0_isMpause       (_instBuffer_io_dataOut_0_isMpause),
    .io_dataOut_1_addr           (_instBuffer_io_dataOut_1_addr),
    .io_dataOut_1_idx            (_instBuffer_io_dataOut_1_idx),
    .io_dataOut_1_trap           (_instBuffer_io_dataOut_1_trap),
    .io_dataOut_1_isControlFlow  (_instBuffer_io_dataOut_1_isControlFlow),
    .io_dataOut_1_isBranch       (_instBuffer_io_dataOut_1_isBranch),
    .io_dataOut_1_isVector       (/* unused */),
    .io_dataOut_1_linkOk         (_instBuffer_io_dataOut_1_linkOk),
    .io_dataOut_1_isEcall        (_instBuffer_io_dataOut_1_isEcall),
    .io_dataOut_1_isMpause       (_instBuffer_io_dataOut_1_isMpause),
    .io_dataOut_2_addr           (_instBuffer_io_dataOut_2_addr),
    .io_dataOut_2_idx            (_instBuffer_io_dataOut_2_idx),
    .io_dataOut_2_trap           (_instBuffer_io_dataOut_2_trap),
    .io_dataOut_2_isControlFlow  (_instBuffer_io_dataOut_2_isControlFlow),
    .io_dataOut_2_isBranch       (_instBuffer_io_dataOut_2_isBranch),
    .io_dataOut_2_isVector       (/* unused */),
    .io_dataOut_2_linkOk         (_instBuffer_io_dataOut_2_linkOk),
    .io_dataOut_2_isEcall        (_instBuffer_io_dataOut_2_isEcall),
    .io_dataOut_2_isMpause       (_instBuffer_io_dataOut_2_isMpause),
    .io_dataOut_3_addr           (_instBuffer_io_dataOut_3_addr),
    .io_dataOut_3_idx            (_instBuffer_io_dataOut_3_idx),
    .io_dataOut_3_trap           (_instBuffer_io_dataOut_3_trap),
    .io_dataOut_3_isControlFlow  (_instBuffer_io_dataOut_3_isControlFlow),
    .io_dataOut_3_isBranch       (_instBuffer_io_dataOut_3_isBranch),
    .io_dataOut_3_isVector       (/* unused */),
    .io_dataOut_3_linkOk         (_instBuffer_io_dataOut_3_linkOk),
    .io_dataOut_3_isEcall        (_instBuffer_io_dataOut_3_isEcall),
    .io_dataOut_3_isMpause       (_instBuffer_io_dataOut_3_isMpause),
    .io_dataOut_4_addr           (_instBuffer_io_dataOut_4_addr),
    .io_dataOut_4_idx            (_instBuffer_io_dataOut_4_idx),
    .io_dataOut_4_trap           (_instBuffer_io_dataOut_4_trap),
    .io_dataOut_4_isControlFlow  (_instBuffer_io_dataOut_4_isControlFlow),
    .io_dataOut_4_isBranch       (_instBuffer_io_dataOut_4_isBranch),
    .io_dataOut_4_isVector       (/* unused */),
    .io_dataOut_4_linkOk         (_instBuffer_io_dataOut_4_linkOk),
    .io_dataOut_4_isEcall        (_instBuffer_io_dataOut_4_isEcall),
    .io_dataOut_4_isMpause       (_instBuffer_io_dataOut_4_isMpause),
    .io_dataOut_5_addr           (_instBuffer_io_dataOut_5_addr),
    .io_dataOut_5_idx            (_instBuffer_io_dataOut_5_idx),
    .io_dataOut_5_trap           (_instBuffer_io_dataOut_5_trap),
    .io_dataOut_5_isControlFlow  (_instBuffer_io_dataOut_5_isControlFlow),
    .io_dataOut_5_isBranch       (_instBuffer_io_dataOut_5_isBranch),
    .io_dataOut_5_isVector       (/* unused */),
    .io_dataOut_5_linkOk         (_instBuffer_io_dataOut_5_linkOk),
    .io_dataOut_5_isEcall        (_instBuffer_io_dataOut_5_isEcall),
    .io_dataOut_5_isMpause       (_instBuffer_io_dataOut_5_isMpause),
    .io_dataOut_6_addr           (_instBuffer_io_dataOut_6_addr),
    .io_dataOut_6_idx            (_instBuffer_io_dataOut_6_idx),
    .io_dataOut_6_trap           (_instBuffer_io_dataOut_6_trap),
    .io_dataOut_6_isControlFlow  (_instBuffer_io_dataOut_6_isControlFlow),
    .io_dataOut_6_isBranch       (_instBuffer_io_dataOut_6_isBranch),
    .io_dataOut_6_isVector       (/* unused */),
    .io_dataOut_6_linkOk         (_instBuffer_io_dataOut_6_linkOk),
    .io_dataOut_6_isEcall        (_instBuffer_io_dataOut_6_isEcall),
    .io_dataOut_6_isMpause       (_instBuffer_io_dataOut_6_isMpause),
    .io_dataOut_7_addr           (_instBuffer_io_dataOut_7_addr),
    .io_dataOut_7_idx            (_instBuffer_io_dataOut_7_idx),
    .io_dataOut_7_trap           (_instBuffer_io_dataOut_7_trap),
    .io_dataOut_7_isControlFlow  (_instBuffer_io_dataOut_7_isControlFlow),
    .io_dataOut_7_isBranch       (_instBuffer_io_dataOut_7_isBranch),
    .io_dataOut_7_isVector       (/* unused */),
    .io_dataOut_7_linkOk         (_instBuffer_io_dataOut_7_linkOk),
    .io_dataOut_7_isEcall        (_instBuffer_io_dataOut_7_isEcall),
    .io_dataOut_7_isMpause       (_instBuffer_io_dataOut_7_isMpause),
    .io_dataOut_8_addr           (_instBuffer_io_dataOut_8_addr),
    .io_dataOut_8_idx            (_instBuffer_io_dataOut_8_idx),
    .io_dataOut_8_trap           (_instBuffer_io_dataOut_8_trap),
    .io_dataOut_8_isControlFlow  (_instBuffer_io_dataOut_8_isControlFlow),
    .io_dataOut_8_isBranch       (_instBuffer_io_dataOut_8_isBranch),
    .io_dataOut_8_isVector       (/* unused */),
    .io_dataOut_8_linkOk         (_instBuffer_io_dataOut_8_linkOk),
    .io_dataOut_8_isEcall        (/* unused */),
    .io_dataOut_8_isMpause       (_instBuffer_io_dataOut_8_isMpause),
    .io_dataOut_9_addr           (_instBuffer_io_dataOut_9_addr),
    .io_dataOut_9_idx            (_instBuffer_io_dataOut_9_idx),
    .io_dataOut_9_trap           (_instBuffer_io_dataOut_9_trap),
    .io_dataOut_9_isControlFlow  (_instBuffer_io_dataOut_9_isControlFlow),
    .io_dataOut_9_isBranch       (_instBuffer_io_dataOut_9_isBranch),
    .io_dataOut_9_isVector       (/* unused */),
    .io_dataOut_9_linkOk         (_instBuffer_io_dataOut_9_linkOk),
    .io_dataOut_9_isEcall        (/* unused */),
    .io_dataOut_9_isMpause       (_instBuffer_io_dataOut_9_isMpause),
    .io_dataOut_10_addr          (_instBuffer_io_dataOut_10_addr),
    .io_dataOut_10_idx           (_instBuffer_io_dataOut_10_idx),
    .io_dataOut_10_trap          (_instBuffer_io_dataOut_10_trap),
    .io_dataOut_10_isControlFlow (_instBuffer_io_dataOut_10_isControlFlow),
    .io_dataOut_10_isBranch      (_instBuffer_io_dataOut_10_isBranch),
    .io_dataOut_10_isVector      (/* unused */),
    .io_dataOut_10_linkOk        (_instBuffer_io_dataOut_10_linkOk),
    .io_dataOut_10_isEcall       (/* unused */),
    .io_dataOut_10_isMpause      (_instBuffer_io_dataOut_10_isMpause),
    .io_dataOut_11_addr          (_instBuffer_io_dataOut_11_addr),
    .io_dataOut_11_idx           (_instBuffer_io_dataOut_11_idx),
    .io_dataOut_11_trap          (_instBuffer_io_dataOut_11_trap),
    .io_dataOut_11_isControlFlow (_instBuffer_io_dataOut_11_isControlFlow),
    .io_dataOut_11_isBranch      (_instBuffer_io_dataOut_11_isBranch),
    .io_dataOut_11_isVector      (/* unused */),
    .io_dataOut_11_linkOk        (_instBuffer_io_dataOut_11_linkOk),
    .io_dataOut_11_isEcall       (/* unused */),
    .io_dataOut_11_isMpause      (_instBuffer_io_dataOut_11_isMpause),
    .io_dataOut_12_addr          (_instBuffer_io_dataOut_12_addr),
    .io_dataOut_12_idx           (_instBuffer_io_dataOut_12_idx),
    .io_dataOut_12_trap          (_instBuffer_io_dataOut_12_trap),
    .io_dataOut_12_isControlFlow (_instBuffer_io_dataOut_12_isControlFlow),
    .io_dataOut_12_isBranch      (_instBuffer_io_dataOut_12_isBranch),
    .io_dataOut_12_isVector      (/* unused */),
    .io_dataOut_12_linkOk        (_instBuffer_io_dataOut_12_linkOk),
    .io_dataOut_12_isEcall       (/* unused */),
    .io_dataOut_12_isMpause      (_instBuffer_io_dataOut_12_isMpause),
    .io_dataOut_13_addr          (_instBuffer_io_dataOut_13_addr),
    .io_dataOut_13_idx           (_instBuffer_io_dataOut_13_idx),
    .io_dataOut_13_trap          (_instBuffer_io_dataOut_13_trap),
    .io_dataOut_13_isControlFlow (_instBuffer_io_dataOut_13_isControlFlow),
    .io_dataOut_13_isBranch      (_instBuffer_io_dataOut_13_isBranch),
    .io_dataOut_13_isVector      (/* unused */),
    .io_dataOut_13_linkOk        (_instBuffer_io_dataOut_13_linkOk),
    .io_dataOut_13_isEcall       (/* unused */),
    .io_dataOut_13_isMpause      (_instBuffer_io_dataOut_13_isMpause),
    .io_dataOut_14_addr          (_instBuffer_io_dataOut_14_addr),
    .io_dataOut_14_idx           (_instBuffer_io_dataOut_14_idx),
    .io_dataOut_14_trap          (_instBuffer_io_dataOut_14_trap),
    .io_dataOut_14_isControlFlow (_instBuffer_io_dataOut_14_isControlFlow),
    .io_dataOut_14_isBranch      (_instBuffer_io_dataOut_14_isBranch),
    .io_dataOut_14_isVector      (/* unused */),
    .io_dataOut_14_linkOk        (_instBuffer_io_dataOut_14_linkOk),
    .io_dataOut_14_isEcall       (/* unused */),
    .io_dataOut_14_isMpause      (_instBuffer_io_dataOut_14_isMpause),
    .io_dataOut_15_addr          (_instBuffer_io_dataOut_15_addr),
    .io_dataOut_15_idx           (_instBuffer_io_dataOut_15_idx),
    .io_dataOut_15_trap          (_instBuffer_io_dataOut_15_trap),
    .io_dataOut_15_isControlFlow (_instBuffer_io_dataOut_15_isControlFlow),
    .io_dataOut_15_isBranch      (_instBuffer_io_dataOut_15_isBranch),
    .io_dataOut_15_isVector      (/* unused */),
    .io_dataOut_15_linkOk        (_instBuffer_io_dataOut_15_linkOk),
    .io_dataOut_15_isEcall       (/* unused */),
    .io_dataOut_15_isMpause      (_instBuffer_io_dataOut_15_isMpause),
    .io_deqReady                 ({1'h0, deqReady}),
    .io_flush                    (trapRetired)
  );
  assign io_nRetired = deqReady_reg - retiredEcalls_reg;
  assign io_empty = _instBuffer_io_nEnqueued == 5'h0;
  assign io_trapPending = io_trapPending_REG;
endmodule

