// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1
module SRAM_2048x128(
  input          clock,
  input  [10:0]  io_addr,
  input          io_enable,
                 io_write,
  input  [127:0] io_wdata,
  input  [15:0]  io_wmask,
  output [127:0] io_rdata
);

  Sram #(
    .GLOBAL_BASE_ADDR(65536),
    .NUM_ENTRIES(2048)
  ) sramModules_0 (
    .clock  (clock),
    .enable (io_enable),
    .write  (io_write),
    .addr   (io_addr),
    .wdata  (io_wdata),
    .wmask  (io_wmask),
    .rdata  (io_rdata),
    .rvalid (/* unused */)
  );
endmodule

