`ifndef SYNTHESIS // Added by Core.scala Verification Wrapper

// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module Alu_Verification_Assert(
  input io_rs1_valid,
        _GEN,
        valid,
        reset,
        io_rs2_valid,
        _rs1Only_WIRE_5,
        _rs1Only_WIRE_4,
        _rs1Only_WIRE_7,
        _rs1Only_WIRE_6,
        _rs1Only_WIRE_1,
        _rs1Only_WIRE_0,
        _rs1Only_WIRE_3,
        _rs1Only_WIRE_2,
        clock
);

  `ifndef SYNTHESIS
    always @(posedge clock) begin
      if (~reset & valid & ~io_rs1_valid & ~_GEN) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Alu.scala:164\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & valid & ~io_rs2_valid
          & {_rs1Only_WIRE_7,
             _rs1Only_WIRE_6,
             _rs1Only_WIRE_5,
             _rs1Only_WIRE_4,
             _rs1Only_WIRE_3,
             _rs1Only_WIRE_2,
             _rs1Only_WIRE_1,
             _rs1Only_WIRE_0} == 8'h0) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Alu.scala:165\n");
        if (`STOP_COND_)
          $fatal;
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
endmodule


`endif // Added by Core.scala Verification Wrapper
