`ifndef SYNTHESIS // Added by Core.scala Verification Wrapper

// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module FabricMux_Verification_Assert(
  input io_source_readDataAddr_valid,
        io_source_writeDataAddr_valid,
        reset,
        _GEN,
        _GEN_0,
        _GEN_1,
        _GEN_2,
        _GEN_3,
        _GEN_4,
        _GEN_5,
        _GEN_6,
        _GEN_7,
        _GEN_8,
        _GEN_9,
        _GEN_10,
        _GEN_11,
        _GEN_12,
        _GEN_13,
        _GEN_14,
        _GEN_15,
        clock
);

  `ifndef SYNTHESIS
    wire [1:0] _GEN_16 = {1'h0, _GEN};
    always @(posedge clock) begin
      if (~reset & io_source_readDataAddr_valid & io_source_writeDataAddr_valid) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Fabric.scala:76\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, io_source_readDataAddr_valid}
          + {1'h0, io_source_writeDataAddr_valid} > _GEN_16) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_2} + {1'h0, _GEN_0} + {1'h0, _GEN_1} > _GEN_16) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Fabric.scala:98\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_6} + {1'h0, _GEN_5}
          + {1'h0, _GEN_3 & _GEN_4} > _GEN_16) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_9} + {1'h0, _GEN_7} + {1'h0, _GEN_8} > _GEN_16) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_12} + {1'h0, _GEN_10} + {1'h0, _GEN_11} > _GEN_16) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, _GEN_15} + {1'h0, _GEN_13} + {1'h0, _GEN_14} > _GEN_16) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
endmodule


`endif // Added by Core.scala Verification Wrapper
