`ifndef SYNTHESIS // Added by Core.scala Verification Wrapper

// Generated by CIRCT firtool-1.114.0-2-g6cf2492e1

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module LsuSuperSlot_Verification_Assert(
  input         _GEN,
                _GEN_0,
                _GEN_1,
                _GEN_2,
                reset,
                _GEN_3,
                _GEN_4,
                _GEN_5,
                _GEN_6,
                _GEN_7,
                _GEN_8,
                _GEN_9,
                _GEN_10,
                _GEN_11,
                _GEN_12,
                _GEN_13,
                _GEN_14,
                _GEN_15,
                _GEN_16,
                _GEN_17,
                _GEN_18,
                _GEN_19,
                _GEN_20,
                _GEN_21,
                _GEN_22,
                _GEN_23,
                _GEN_24,
                _GEN_25,
                _GEN_26,
                _GEN_27,
                _GEN_28,
                _GEN_29,
                _GEN_30,
                _GEN_31,
                _GEN_32,
                _GEN_33,
                _GEN_34,
                _GEN_35,
                _GEN_36,
                _GEN_37,
                _GEN_38,
                _GEN_39,
                _GEN_40,
                _GEN_41,
                _GEN_42,
                _GEN_43,
                _GEN_44,
                _GEN_45,
                _GEN_46,
                _GEN_47,
                _GEN_48,
                _GEN_49,
                _GEN_50,
                _GEN_51,
                _GEN_52,
                _GEN_53,
                _GEN_54,
                _GEN_55,
                _GEN_56,
                _GEN_57,
                _GEN_58,
                _GEN_59,
                _GEN_60,
                _GEN_61,
                _GEN_62,
                _GEN_63,
  input [127:0] io_busReq_out_bits_wdata,
  input [15:0]  io_busReq_out_bits_wmask,
  input [27:0]  io_busReq_out_bits_rowAddr,
  input         io_busReq_out_bits_write,
  input [127:0] io_busReq_prevBits_wdata,
  input [15:0]  io_busReq_prevBits_wmask,
  input [27:0]  io_busReq_prevBits_rowAddr,
  input         io_busReq_prevBits_write,
  input [127:0] io_busReq_prevBits_1_wdata,
  input [15:0]  io_busReq_prevBits_1_wmask,
  input [27:0]  io_busReq_prevBits_1_rowAddr,
  input         io_busReq_prevBits_1_write,
                _GEN_64,
                _GEN_65,
                _GEN_66,
                _GEN_67,
                _GEN_68,
                _GEN_69,
                _GEN_70,
                _GEN_71,
                _GEN_72,
                _GEN_73,
                _GEN_74,
                _GEN_75,
                _GEN_76,
                _GEN_77,
                _GEN_78,
                _GEN_79,
                _GEN_80,
                _GEN_81,
                _GEN_82,
                _GEN_83,
                _GEN_84,
                _GEN_85,
                _GEN_86,
                _GEN_87,
                _GEN_88,
                _GEN_89,
                _GEN_90,
                _GEN_91,
                _GEN_92,
                _GEN_93,
                _GEN_94,
                _GEN_95,
                _GEN_96,
                _GEN_97,
                _GEN_98,
                _GEN_99,
                _GEN_100,
                _GEN_101,
                _GEN_102,
                _GEN_103,
                _GEN_104,
                _GEN_105,
                _GEN_106,
                _GEN_107,
                _GEN_108,
                _GEN_109,
                _GEN_110,
                _GEN_111,
                _GEN_112,
                _GEN_113,
                _GEN_114,
                _GEN_115,
                _GEN_116,
                _GEN_117,
                _GEN_118,
                _GEN_119,
                _GEN_120,
                _GEN_121,
                _GEN_122,
                _GEN_123,
                _GEN_124,
                _GEN_125,
                _GEN_126,
                _GEN_127,
                _GEN_128,
                _GEN_129,
                _GEN_130,
                _GEN_131,
                _GEN_132,
                _GEN_133,
                _GEN_134,
                _GEN_135,
                _GEN_136,
                _GEN_137,
                _GEN_138,
                _GEN_139,
                _GEN_140,
                _GEN_141,
                _GEN_142,
                _GEN_143,
                _GEN_144,
                clock,
                io_busReq_prevPending,
                io_busReq_out_valid,
                io_busReq_prevPending_1,
                _GEN_145,
                _GEN_146,
                _GEN_147,
                _GEN_148
);

  `ifndef SYNTHESIS
    wire [2:0] _GEN_149 = {2'h0, _GEN_3};
    wire [4:0] _GEN_150 = {4'h0, _GEN_3};
    always @(posedge clock) begin
      if (~reset & {1'h0, {1'h0, _GEN_1} + {1'h0, _GEN_2}}
          + {1'h0, {1'h0, _GEN} + {1'h0, _GEN_0}} > _GEN_149) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_6} + {1'h0, _GEN_7}}
          + {1'h0, {1'h0, _GEN_4} + {1'h0, _GEN_5}} > _GEN_149) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_10} + {1'h0, _GEN_11}}
          + {1'h0, {1'h0, _GEN_8} + {1'h0, _GEN_9}} > _GEN_149) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_14} + {1'h0, _GEN_15}}
          + {1'h0, {1'h0, _GEN_12} + {1'h0, _GEN_13}} > _GEN_149) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_18} + {1'h0, _GEN_19}}
          + {1'h0, {1'h0, _GEN_16} + {1'h0, _GEN_17}} > _GEN_149) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_22} + {1'h0, _GEN_23}}
          + {1'h0, {1'h0, _GEN_20} + {1'h0, _GEN_21}} > _GEN_149) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_26} + {1'h0, _GEN_27}}
          + {1'h0, {1'h0, _GEN_24} + {1'h0, _GEN_25}} > _GEN_149) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_30} + {1'h0, _GEN_31}}
          + {1'h0, {1'h0, _GEN_28} + {1'h0, _GEN_29}} > _GEN_149) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_34} + {1'h0, _GEN_35}}
          + {1'h0, {1'h0, _GEN_32} + {1'h0, _GEN_33}} > _GEN_149) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_38} + {1'h0, _GEN_39}}
          + {1'h0, {1'h0, _GEN_36} + {1'h0, _GEN_37}} > _GEN_149) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_42} + {1'h0, _GEN_43}}
          + {1'h0, {1'h0, _GEN_40} + {1'h0, _GEN_41}} > _GEN_149) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_46} + {1'h0, _GEN_47}}
          + {1'h0, {1'h0, _GEN_44} + {1'h0, _GEN_45}} > _GEN_149) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_50} + {1'h0, _GEN_51}}
          + {1'h0, {1'h0, _GEN_48} + {1'h0, _GEN_49}} > _GEN_149) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_54} + {1'h0, _GEN_55}}
          + {1'h0, {1'h0, _GEN_52} + {1'h0, _GEN_53}} > _GEN_149) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_58} + {1'h0, _GEN_59}}
          + {1'h0, {1'h0, _GEN_56} + {1'h0, _GEN_57}} > _GEN_149) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & {1'h0, {1'h0, _GEN_62} + {1'h0, _GEN_63}}
          + {1'h0, {1'h0, _GEN_60} + {1'h0, _GEN_61}} > _GEN_149) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (io_busReq_prevPending & ~reset & ~io_busReq_out_valid) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: IrrevocableIO violation: valid dropped\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (io_busReq_prevPending & ~reset
          & {io_busReq_out_bits_rowAddr,
             io_busReq_out_bits_write,
             io_busReq_out_bits_wdata,
             io_busReq_out_bits_wmask} != {io_busReq_prevBits_rowAddr,
                                           io_busReq_prevBits_write,
                                           io_busReq_prevBits_wdata,
                                           io_busReq_prevBits_wmask}) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: IrrevocableIO violation: bits changed\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (io_busReq_prevPending_1 & ~reset & ~io_busReq_out_valid) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: IrrevocableIO violation: valid dropped\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (io_busReq_prevPending_1 & ~reset
          & {io_busReq_out_bits_rowAddr,
             io_busReq_out_bits_write,
             io_busReq_out_bits_wdata,
             io_busReq_out_bits_wmask} != {io_busReq_prevBits_1_rowAddr,
                                           io_busReq_prevBits_1_write,
                                           io_busReq_prevBits_1_wdata,
                                           io_busReq_prevBits_1_wmask}) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: IrrevocableIO violation: bits changed\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _GEN_64 > _GEN_3) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0,
              {1'h0, {1'h0, _GEN_67} + {1'h0, _GEN_68}}
                + {1'h0, {1'h0, _GEN_65} + {1'h0, _GEN_66}}}
               + {1'h0,
                  {1'h0, {1'h0, _GEN_71} + {1'h0, _GEN_72}}
                    + {1'h0, {1'h0, _GEN_69} + {1'h0, _GEN_70}}}}
          + {1'h0,
             {1'h0,
              {1'h0, {1'h0, _GEN_75} + {1'h0, _GEN_76}}
                + {1'h0, {1'h0, _GEN_73} + {1'h0, _GEN_74}}}
               + {1'h0,
                  {1'h0, {1'h0, _GEN_79} + {1'h0, _GEN_80}}
                    + {1'h0, {1'h0, _GEN_77} + {1'h0, _GEN_78}}}} > _GEN_150) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & ~_GEN_145) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Lsu.scala:1362\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0, {1'h0, _GEN_83} + {1'h0, _GEN_81} + {1'h0, _GEN_82}} > _GEN_149) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _GEN_84 > _GEN_3) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0,
              {1'h0, {1'h0, _GEN_87} + {1'h0, _GEN_88}}
                + {1'h0, {1'h0, _GEN_85} + {1'h0, _GEN_86}}}
               + {1'h0,
                  {1'h0, {1'h0, _GEN_91} + {1'h0, _GEN_92}}
                    + {1'h0, {1'h0, _GEN_89} + {1'h0, _GEN_90}}}}
          + {1'h0,
             {1'h0,
              {1'h0, {1'h0, _GEN_95} + {1'h0, _GEN_96}}
                + {1'h0, {1'h0, _GEN_93} + {1'h0, _GEN_94}}}
               + {1'h0,
                  {1'h0, {1'h0, _GEN_99} + {1'h0, _GEN_100}}
                    + {1'h0, {1'h0, _GEN_97} + {1'h0, _GEN_98}}}} > _GEN_150) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & ~_GEN_146) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Lsu.scala:1362\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, _GEN_103} + {1'h0, _GEN_101} + {1'h0, _GEN_102}} > _GEN_149) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _GEN_104 > _GEN_3) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0,
              {1'h0, {1'h0, _GEN_107} + {1'h0, _GEN_108}}
                + {1'h0, {1'h0, _GEN_105} + {1'h0, _GEN_106}}}
               + {1'h0,
                  {1'h0, {1'h0, _GEN_111} + {1'h0, _GEN_112}}
                    + {1'h0, {1'h0, _GEN_109} + {1'h0, _GEN_110}}}}
          + {1'h0,
             {1'h0,
              {1'h0, {1'h0, _GEN_115} + {1'h0, _GEN_116}}
                + {1'h0, {1'h0, _GEN_113} + {1'h0, _GEN_114}}}
               + {1'h0,
                  {1'h0, {1'h0, _GEN_119} + {1'h0, _GEN_120}}
                    + {1'h0, {1'h0, _GEN_117} + {1'h0, _GEN_118}}}} > _GEN_150) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & ~_GEN_147) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Lsu.scala:1362\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, _GEN_123} + {1'h0, _GEN_121} + {1'h0, _GEN_122}} > _GEN_149) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _GEN_124 > _GEN_3) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0,
              {1'h0, {1'h0, _GEN_127} + {1'h0, _GEN_128}}
                + {1'h0, {1'h0, _GEN_125} + {1'h0, _GEN_126}}}
               + {1'h0,
                  {1'h0, {1'h0, _GEN_131} + {1'h0, _GEN_132}}
                    + {1'h0, {1'h0, _GEN_129} + {1'h0, _GEN_130}}}}
          + {1'h0,
             {1'h0,
              {1'h0, {1'h0, _GEN_135} + {1'h0, _GEN_136}}
                + {1'h0, {1'h0, _GEN_133} + {1'h0, _GEN_134}}}
               + {1'h0,
                  {1'h0, {1'h0, _GEN_139} + {1'h0, _GEN_140}}
                    + {1'h0, {1'h0, _GEN_137} + {1'h0, _GEN_138}}}} > _GEN_150) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & ~_GEN_148) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Lsu.scala:1362\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset
          & {1'h0,
             {1'h0, _GEN_143} + {1'h0, _GEN_141} + {1'h0, _GEN_142}} > _GEN_149) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
      if (~reset & _GEN_144 > _GEN_3) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at Library.scala:235\n");
        if (`STOP_COND_)
          $fatal;
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
endmodule


`endif // Added by Core.scala Verification Wrapper
